TableData = {
	growth = { 1, 1, 1, 1, 1, 1, 2, 2, 3, 4, 3, 4, 2, 2, 3, 4, 3, 4, 2, 2, 3, 4, 3, 4 },
	attack = { 2, 2, 3, 4, 3, 4, 1, 1, 1, 1, 1, 1, 3, 4, 2, 2, 4, 3, 3, 4, 2, 2, 4, 3 },
	effort = { 3, 4, 2, 2, 4, 3, 3, 4, 2, 2, 4, 3, 1, 1, 1, 1, 1, 1, 4, 3, 4, 3, 2, 2 },
	misc   = { 4, 3, 4, 3, 2, 2, 4, 3, 4, 3, 2, 2, 4, 3, 4, 3, 2, 2, 1, 1, 1, 1, 1, 1 }
}

BagPocket = {
	PC = 0,
	Items = 1,
	KeyItems = 2,
	Pokeballs = 3,
	TMHM = 4,
	Berries = 5,
}

HealingType = {
	Constant = 0,
	Percentage = 1,
}

StatusType = {
	Poison = 0,
	Burn = 1,
	Freeze = 2,
	Sleep = 3,
	Paralyze = 4,
	Confuse = 5,
	All = 100,
}

MiscData = {
	nature = {
		"Hardy", "Lonely", "Brave", "Adamant", "Naughty",
		"Bold", "Docile", "Relaxed", "Impish", "Lax",
		"Timid", "Hasty", "Serious", "Jolly", "Naive",
		"Modest", "Mild", "Quiet", "Bashful", "Rash",
		"Calm", "Gentle", "Sassy", "Careful", "Quirky"
	},
	type = {
		"Fighting", "Flying", "Poison", "Ground",
		"Rock", "Bug", "Ghost", "Steel",
		"Fire", "Water", "Grass", "Electric",
		"Psychic", "Ice", "Dragon", "Dark"
	},
	status = {
		"None", "Sleep", "Poison", "Burn", "Freeze",
		"Paralysis", "Bad Poison"
	},
	items_gen4 = {},
	item = {
		"---", 
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb",
		--113 - 134 are "Unknown"
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Adamant Orb",
		"Lustrous Orb",
		"Grass Mail",
		"Flame Mail",
		"Bubble Mail",
		"Bloom Mail",
		"Tunnel Mail",
		"Steel Mail",
		"Heart Mail",
		"Snow Mail",
		"Space Mail",
		"Air Mail",
		"Mosaic Mail",
		"Brick Mail",
		"Chery Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebla Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"HM07",
		"HM08",
	},
	items_gen5 = {
		"---", 
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb",

		"unknown",
		"unknown",
		"unknown",
		"Douse Drive",
		"Shock Drive",
		"Burn Drive",
		"Chill Drive",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Sweet Heart",
		"Adamant Orb",
		"Lustrous Orb",
		"Greet Mail",
		"Favored Mail",
		"RSVP Mail",
		"Thanks Mail",
		"Inquiry Mail",
		"Like Mail",
		"Reply Mail",
		"BridgeMail S",
		"BridgeMail D",
		"BridgeMail T",
		"BridgeMail V",
		"BridgeMail M",
		"Cheri Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebla Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"HM07",
		"HM08",
	},
	healingItems_GEN4 = {
		[17] = {
			id = 17,
			name = "Potion",
			amount = 20,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[23] = {
			id = 23,
			name = "Full Restore",
			amount = 100,
			type = HealingType.Percentage,
			pocket = BagPocket.Items,
		},
		[24] = {
			id = 24,
			name = "Max Potion",
			amount = 100,
			type = HealingType.Percentage,
			pocket = BagPocket.Items,
		},
		[25] = {
			id = 25,
			name = "Hyper Potion",
			amount = 200,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[26] = {
			id = 26,
			name = "Super Potion",
			amount = 60,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[30] = {
			id = 30,
			name = "Fresh Water",
			amount = 50,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[31] = {
			id = 31,
			name = "Soda Pop",
			amount = 60,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[32] = {
			id = 32,
			name = "Lemonade",
			amount = 80,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[33] = {
			id = 29,
			name = "Moomoo Milk",
			amount = 100,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[34] = {
			id = 30,
			name = "EnergyPowder",
			amount = 50,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[35] = {
			id = 31,
			name = "Energy Root",
			amount = 200,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[43] = {
			id = 44,
			name = "Berry Juice",
			amount = 20,
			type = HealingType.Constant,
			pocket = BagPocket.Items,
		},
		[155] = {
			id = 139,
			name = "Oran Berry",
			amount = 10,
			type = HealingType.Constant,
			pocket = BagPocket.Berries,
		},
		[158] = {
			id = 142,
			name = "Sitrus Berry",
			amount = 30,
			type = HealingType.Constant,
			pocket = BagPocket.Berries,
		},
		[159] = {
			id = 143,
			name = "Figy Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
		[160] = {
			id = 144,
			name = "Wiki Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
		[161] = {
			id = 145,
			name = "Mago Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
		[162] = {
			id = 146,
			name = "Aguav Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
		[163] = {
			id = 147,
			name = "Iapapa Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
		[208] = {
			id = 175,
			name = "Enigma Berry",
			amount = 12.5,
			type = HealingType.Percentage,
			pocket = BagPocket.Berries,
		},
	},
	ability = {
		"---",
		"Stench",
		"Drizzle",
		"Speed Boost",
		"Battle Armor",
		"Sturdy",
		"Damp",
		"Limber",
		"Sand Veil",
		"Static",
		"Volt Absorb",
		"Water Absorb",
		"Oblivious",
		"Cloud Nine",
		"Compound Eyes",
		"Insomnia",
		"Color Change",
		"Immunity",
		"Flash Fire",
		"Shield Dust",
		"Own Tempo",
		"Suction Cups",
		"Intimidate",
		"Shadow Tag",
		"Rough Skin",
		"Wonder Guard",
		"Levitate",
		"Effect Spore",
		"Synchronize",
		"Clear Body",
		"Natural Cure",
		"Lightning Rod",
		"Serene Grace",
		"Swift Swim",
		"Chlorophyll",
		"Illuminate",
		"Trace",
		"Huge Power",
		"Poison Point",
		"Inner Focus",
		"Magma Armor",
		"Water Veil",
		"Magnet Pull",
		"Soundproof",
		"Rain Dish",
		"Sand Stream",
		"Pressure",
		"Thick Fat",
		"Early Bird",
		"Flame Body",
		"Run Away",
		"Keen Eye",
		"Hyper Cutter",
		"Pickup",
		"Truant",
		"Hustle",
		"Cute Charm",
		"Plus",
		"Minus",
		"Forecast",
		"Sticky Hold",
		"Shed Skin",
		"Guts",
		"Marvel Scale",
		"Liquid Ooze",
		"Overgrow",
		"Blaze",
		"Torrent",
		"Swarm",
		"Rock Head",
		"Drought",
		"Arena Trap",
		"Vital Spirit",
		"White Smoke",
		"Pure Power",
		"Shell Armor",
		"Air Lock",
		"Tangled Feet",
		"Motor Drive",
		"Rivalry",
		"Steadfast",
		"Snow Cloak",
		"Gluttony",
		"Anger Point",
		"Unburden",
		"Heatproof",
		"Simple",
		"Dry Skin",
		"Download",
		"Iron Fist",
		"Poison Heal",
		"Adaptability",
		"Skill Link",
		"Hydration",
		"Solar Power",
		"Quick Feet",
		"Normalize",
		"Sniper",
		"Magic Guard",
		"No Guard",
		"Stall",
		"Technician",
		"Leaf Guard",
		"Klutz",
		"Mold Breaker",
		"Super Luck",
		"Aftermath",
		"Anticipation",
		"Forewarn",
		"Unaware",
		"Tinted Lens",
		"Filter",
		"Slow Start",
		"Scrappy",
		"Storm Drain",
		"Ice Body",
		"Solid Rock",
		"Snow Warning",
		"Honey Gather",
		"Frisk",
		"Reckless",
		"Multitype",
		"Flower Gift",
		"Bad Dreams",
		"Pickpocket",
		"Sheer Force",
		"Contrary",
		"Unnerve",
		"Defiant",
		"Defeatist",
		"Cursed Body",
		"Healer",
		"Friend Guard",
		"Weak Armor",
		"Heavy Metal",
		"Light Metal",
		"Multiscale",
		"Toxic Boost",
		"Flare Boost",
		"Harvest",
		"Telepathy",
		"Moody",
		"Overcoat",
		"Poison Touch",
		"Regenerator",
		"Big Pecks",
		"Sand Rush",
		"Wonder Skin",
		"Analytic",
		"Illusion",
		"Imposter",
		"Infiltrator",
		"Mummy",
		"Moxie",
		"Justified",
		"Rattled",
		"Magic Bounce",
		"Sap Sipper",
		"Prankster",
		"Sand Force",
		"Iron Barbs",
		"Zen Mode",
		"Victory Star",
		"Turboblaze",
		"Teravolt"
	}
}

EffectiveData = {
	normal = { rock = 0.5, ghost = 0, steel = 0.5 },
	fire = { fire = 0.5, water = 0.5, grass = 2, ice = 2, bug = 2, rock = 0.5, dragon = 0.5, steel = 2 },
	water = { fire = 2, water = 0.5, grass = 0.5, ground = 2, rock = 2, dragon = 0.5 },
	grass = { fire = 0.5, water = 2, grass = 0.5, poison = 0.5, ground = 2, flying = 0.5, bug = 0.5, rock = 2, dragon = 0.5, steel = 0.5 },
	electric = { water = 2, grass = 0.5, electric = 0.5, ground = 0, flying = 2, dragon = 0.5 },
	ice = { fire = 0.5, water = 0.5, grass = 2, ice = 0.5, ground = 2, flying = 2, dragon = 2, steel = 0.5 },
	fighting = { normal = 2, ice = 2, poison = 0.5, flying = 0.5, psychic = 0.5, bug = 0.5, rock = 2, ghost = 0, dark = 2, steel = 2 },
	poison = { grass = 2, poison = 0.5, ground = 0.5, rock = 0.5, ghost = 0.5, steel = 0 },
	ground = { fire = 2, grass = 0.5, electric = 2, poison = 2, flying = 0, bug = 0.5, rock = 2, steel = 2 },
	flying = { grass = 2, electric = 0.5, fighting = 2, bug = 2, rock = 0.5, steel = 0.5 },
	psychic = { fighting = 2, poison = 2, psychic = 0.5, dark = 0, steel = 0.5 },
	bug = { fire = 0.5, grass = 2, fighting = 0.5, poison = 0.5, flying = 0.5, psychic = 2, ghost = 0.5, dark = 2, steel = 0.5 },
	rock = { fire = 2, ice = 2, fighting = 0.5, ground = 0.5, flying = 2, bug = 2, steel = 0.5 },
	ghost = { normal = 0, psychic = 2, ghost = 2, dark = 0.5, steel = 0.5 },
	dragon = { dragon = 2, steel = 0.5 },
	dark = { fighting = 0.5, psychic = 2, ghost = 2, dark = 0.5, steel = 0.5 },
	steel = { fire = 0.5, water = 0.5, ice = 2, rock = 2, steel = 0.5, electric = 0.5 },
}

