local function BrowsManager(settings, ui, frameCounters, program, screen)
	local FrameCounter = dofile(Paths.FOLDERS.DATA_FOLDER .. "/FrameCounter.lua")
	local Box = dofile(Paths.FOLDERS.UI_BASE_CLASSES .. "/Box.lua")
	local Component = dofile(Paths.FOLDERS.UI_BASE_CLASSES .. "/Component.lua")
	local ImageLabel = dofile(Paths.FOLDERS.UI_BASE_CLASSES .. "/ImageLabel.lua")
	local ImageField = dofile(Paths.FOLDERS.UI_BASE_CLASSES .. "/ImageField.lua")

	local browsVisible = false
	local browsUp = false
	local defaultFrames = 8
	local fileEnding = ".png"
	local currentPokemon = nil
	local maxBrows = 6
	local browsControls = {}
	local currentScreen = nil
	local frameUIPath = nil
	local needReset = false

	local self = {}

	local browsOptions = {
		[1] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Left"}, {x = 3, y = 2, file = "Brows25Right"}}},
		[2] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows25Right"}}},
		[3] = {direction = 0, brows = {{x = 3, y = 9, file = "Brows20Left"}, {x = 8, y = 9, file = "Brows20Right"}}},
		[4] = {direction = 0, brows = {{x = 5, y = 3, file = "Brows20Left"}, {x = 9, y = 3, file = "Brows20Right"}}},
		[5] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows25Right"}}},
		[6] = {direction = 0, brows = {{x = -1, y = -4, file = "Brows25Right"}}},
		[7] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows15Left"}, {x = -1, y = 1, file = "Brows25Right"}}},
		[8] = {direction = 0, brows = {{x = -3, y = 7, file = "Brows25LeftTall"}, {x = 2, y = 7, file = "Brows25RightTall"}}},
		[9] = {direction = 0, brows = {{x = -3, y = -2, file = "Brows25Right"}}},
		[10] = {direction = 0, brows = {{x = 3, y = -4, file = "Brows30Right"}}},
		[11] = {direction = 0, brows = {{x = 10, y = 0, file = "Brows25Left"}}},
		[12] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows30LeftFlat"}, {x = -3, y = -2, file = "Brows30Right"}}},
		[13] = {direction = 1, brows = {{x = 7, y = 2, file = "Brows15Left"}, {x = 16, y = 7, file = "Brows15Left"}}},
		[14] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows15Left"}, {x = -3, y = 3, file = "Brows25Right"}}},
		[15] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows15Left"}, {x = -6, y = -1, file = "Brows30Right"}}},
		[16] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		[17] = {direction = 0, brows = {{x = -3, y = 7, file = "Brows25RightTall"}}},
		[18] = {direction = 0, brows = {{x = -5, y = 3, file = "Brows25Right"}}},
		[19] = {direction = 0, brows = {{x = -3, y = 3, file = "Brows25Right"}}},
		[20] = {direction = 0, brows = {{x = -3, y = 0, file = "Brows25Right"}}},
		[21] = {direction = 0, brows = {{x = -2, y = 0, file = "Brows25Right"}}},
		[22] = {direction = 0, brows = {{x = 0, y = 3, file = "Brows25Right"}}},
		[23] = {direction = 0, brows = {{x = 1, y = -2, file = "Brows25Right"}}},
		[24] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows25RightTall"}}},
		[25] = {direction = 0, brows = {{x = -1, y = 3, file = "Brows25Left"}, {x = 0, y = 2, file = "Brows25Right"}}},
		[26] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows25"}}},
		[27] = {direction = 0, brows = {{x = 3, y = 8, file = "Brows15Left"}, {x = 4, y = 4, file = "Brows25Right"}}},
		[28] = {direction = 0, brows = {{x = -2, y = 6, file = "Brows25Left"}, {x = -1, y = 5, file = "Brows25Right"}}},
		[29] = {direction = 0, brows = {{x = -1, y = -2, file = "Brows25Right"}}},
		[30] = {direction = 0, brows = {{x = 3, y = 12, file = "Brows15Left"}, {x = 1, y = 10, file = "Brows25Right"}}},
		[31] = {direction = 0, brows = {{x = -1, y = -1, file = "Brows25Right"}}},
		[32] = {direction = 0, brows = {{x = 4, y = 7, file = "Brows25RightTall"}}},
		[33] = {direction = 0, brows = {{x = 5, y = 8, file = "Brows25RightTall"}}},
		[34] = {direction = 2, brows = {{x = 7, y = 9, file = "Brows15Right"}}},
		[35] = {direction = 0, brows = {{x = 8, y = 8, file = "Brows20"}}},
		[36] = {direction = 0, brows = {{x = 11, y = 7, file = "Brows20Left"}, {x = 9, y = 9, file = "Brows20RightFlat"}}},
		[37] = {direction = 0, brows = {{x = -4, y = 7, file = "Brows25Right"}}},
		[38] = {direction = 0, brows = {{x = -3, y = 7, file = "Brows20Right"}}},
		[39] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows30Left"}, {x = 4, y = 6, file = "Brows30RightFlat"}}},
		[40] = {direction = 0, brows = {{x = 2, y = 3, file = "Brows30Left"}, {x = -2, y = 3, file = "Brows30Right"}}},
		[41] = {direction = 2, brows = {{x = -3, y = 7, file = "Brows20Right"}, {x = 3, y = 4, file = "Brows20Right"}}},
		[42] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows15Left"}, {x = 3, y = 1, file = "Brows20Right"}}},
		[43] = {direction = 0, brows = {{x = 1, y = 7, file = "Brows25LeftTall"}, {x = 1, y = 9, file = "Brows25RightFlat"}}},
		[44] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows25"}}},
		[45] = {direction = 0, brows = {{x = 8, y = 12, file = "Brows15Right"}}},
		[46] = {direction = 0, brows = {{x = 0, y = 6, file = "Brows25Left"}, {x = 0, y = 10, file = "Brows25RightFlat"}}},
		[47] = {direction = 0, brows = {{x = 9, y = 8, file = "Brows20Left"}, {x = 7, y = 8, file = "Brows20Right"}}},
		[48] = {direction = 0, brows = {{x = 3, y = 1, file = "Brows25LeftTall"}, {x = -1, y = 3, file = "Brows25RightFlat"}}},
		[49] = {direction = 0, brows = {{x = 4, y = 6, file = "Brows25LeftFlat"}, {x = 0, y = 4, file = "Brows25Right"}}},
		[50] = {direction = 0, brows = {{x = 4, y = 2, file = "Brows20Left"}, {x = 3, y = 2, file = "Brows20Right"}}},
		[51] = {
			direction = 0,
			brows = {
				{x = 3, y = 7, file = "Brows15Left"},
				{x = 0, y = 7, file = "Brows15Right"},
				{x = 14, y = -4, file = "Brows15Left"},
				{x = 11, y = -4, file = "Brows15Right"},
				{x = 20, y = 13, file = "Brows15Left"},
				{x = 17, y = 14, file = "Brows15Right"}
			}
		},
		[52] = {direction = 0, brows = {{x = 5, y = 4, file = "Brows25Left"}, {x = 6, y = 7, file = "Brows25RightFlat"}}},
		[53] = {direction = 0, brows = {{x = 1, y = 7, file = "Brows25LeftTall"}, {x = 3, y = 7, file = "Brows25RightTall"}}},
		[54] = {direction = 0, brows = {{x = 6, y = -1, file = "Brows25Left"}, {x = 4, y = 2, file = "Brows25RightFlat"}}},
		[55] = {direction = 0, brows = {{x = -2, y = 1, file = "Brows25Right"}}},
		[56] = {direction = 0, brows = {{x = 5, y = 10, file = "Brows25LeftTall"}, {x = 3, y = 9, file = "Brows25Right"}}},
		[57] = {direction = 2, brows = {{x = -9, y = 8, file = "Brows25Right"}, {x = -1, y = 3, file = "Brows25Right"}}},
		[58] = {direction = 0, brows = {{x = -4, y = 5, file = "Brows25Right"}}},
		[59] = {direction = 0, brows = {{x = 8, y = 6, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20Right"}}},
		[60] = {direction = 0, brows = {{x = 5, y = -4, file = "Brows25Left"}, {x = 4, y = -4, file = "Brows25Right"}}},
		[61] = {direction = 0, brows = {{x = 7, y = -5, file = "Brows25Left"}, {x = 8, y = -4, file = "Brows25Right"}}},
		[62] = {direction = 0, brows = {{x = 4, y = -5, file = "Brows25Left"}, {x = 5, y = -5, file = "Brows25Right"}}},
		[63] = {direction = 0, brows = {{x = 5, y = 10, file = "Brows20Left"}, {x = 4, y = 10, file = "Brows20Right"}}},
		[64] = {direction = 0, brows = {{x = -6, y = 1, file = "Brows25Right"}}},
		[65] = {direction = 0, brows = {{x = 7, y = 8, file = "Brows20Left"}, {x = 5, y = 10, file = "Brows20RightFlat"}}},
		[66] = {direction = 2, brows = {{x = 4, y = 7, file = "Brows20LeftFlat"}, {x = 3, y = 2, file = "Brows25RightTall"}}},
		[67] = {direction = 0, brows = {{x = -2, y = -1, file = "Brows25Right"}}},
		[68] = {direction = 0, brows = {{x = 5, y = 10, file = "Brows15Left"}, {x = 1, y = 8, file = "Brows20Right"}}},
		[69] = {direction = 0, brows = {{x = 5, y = 3, file = "Brows15Right"}}},
		[70] = {direction = 0, brows = {{x = 7, y = -1, file = "Brows20Left"}, {x = 5, y = -1, file = "Brows20Right"}}},
		[71] = {direction = 0, brows = {{x = 7, y = 11, file = "Brows25LeftFlat"}, {x = 5, y = 9, file = "Brows25RightTall"}}},
		[72] = {direction = 0, brows = {{x = -4, y = 8, file = "Brows25Right"}}},
		[73] = {direction = 0, brows = {{x = 3, y = 7, file = "Brows25Left"}, {x = 2, y = 7, file = "Brows25Right"}}},
		[74] = {direction = 0, brows = {{x = 5, y = 8, file = "Brows25LeftFlat"}, {x = 2, y = 5, file = "Brows25Right"}}},
		[75] = {direction = 0, brows = {{x = 7, y = 9, file = "Brows25LeftFlat"}, {x = 3, y = 6, file = "Brows25Right"}}},
		[76] = {direction = 0, brows = {{x = -4, y = 1, file = "Brows25Right"}}},
		[77] = {direction = 0, brows = {{x = 0, y = 10, file = "Brows20Right"}}},
		[78] = {direction = 0, brows = {{x = 1, y = 8, file = "Brows20Right"}}},
		[79] = {direction = 0, brows = {{x = 3, y = -2, file = "Brows25Left"}, {x = 2, y = -1, file = "Brows25Right"}}},
		[80] = {direction = 0, brows = {{x = 3, y = -1, file = "Brows25Left"}, {x = 2, y = -1, file = "Brows25Right"}}},
		[81] = {direction = 0, brows = {{x = 1, y = 1, file = "Unibrow30"}}},
		[82] = {
			direction = 0,
			brows = {{x = 7, y = 4, file = "Unibrow20"}, {x = -7, y = 18, file = "Unibrow20"}, {x = 18, y = 19, file = "Unibrow20"}}
		},
		[83] = {direction = 0, brows = {{x = 3, y = 4, file = "Brows25"}}},
		[84] = {direction = 0, brows = {{x = 20, y = -1, file = "Brows15Left"}, {x = -3, y = 3, file = "Brows15Right"}}},
		[85] = {direction = 0, brows = {{x = -10, y = 10, file = "Brows20Right"}, {x = 6, y = -2, file = "Brows20Right"}}},
		[86] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows25"}}},
		[87] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20RightFlat"}}},
		[88] = {direction = 0, brows = {{x = 6, y = -2, file = "Brows20Left"}, {x = 5, y = -1, file = "Brows20Right"}}},
		[89] = {direction = 1, brows = {{x = 14, y = 1, file = "Brows20LeftFlat"}}},
		[90] = {direction = 0, brows = {{x = -1, y = 0, file = "Brows30"}}},
		[91] = {direction = 0, brows = {{x = 7, y = 8, file = "Brows25Left"}, {x = 4, y = 7, file = "Brows25Right"}}},
		[92] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows30LeftTall"}, {x = -4, y = 2, file = "Brows30Right"}}},
		[93] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows25LeftTall"}, {x = 1, y = 4, file = "Brows25Right"}}},
		[94] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows25LeftTall"}, {x = 6, y = 6, file = "Brows25RightTall"}}},
		[95] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows25Left"}, {x = -2, y = 3, file = "Brows25RightFlat"}}},
		[96] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows25RightFlat"}}},
		[97] = {direction = 0, brows = {{x = 6, y = 7, file = "Brows15Left"}, {x = 2, y = 7, file = "Brows25RightFlat"}}},
		[98] = {direction = 0, brows = {{x = 5, y = 4, file = "Brows25Left"}, {x = 2, y = 4, file = "Brows25Right"}}},
		[99] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows25Left"}, {x = 0, y = 4, file = "Brows25Right"}}},
		[100] = {direction = 0, brows = {{x = -8, y = 2, file = "Brows30Right"}}},
		[101] = {direction = 0, brows = {{x = 1, y = -3, file = "Brows30"}}},
		[102] = {
			direction = 0,
			brows = {
				{x = 0, y = 12, file = "Brows15Left"},
				{x = -5, y = 12, file = "Brows15Right"},
				{x = 18, y = 0, file = "Brows15Left"},
				{x = 15, y = 0, file = "Brows15Right"},
				{x = 24, y = 16, file = "Brows15Left"}
			}
		},
		[103] = {
			direction = 0,
			brows = {
				{x = -5, y = 3, file = "Brows15Right"},
				{x = 8, y = 7, file = "Brows15Left"},
				{x = 4, y = 7, file = "Brows15Right"},
				{x = 26, y = 5, file = "Brows15Left"}
			}
		},
		[104] = {direction = 0, brows = {{x = 0, y = 5, file = "Brows25Right"}}},
		[105] = {direction = 0, brows = {{x = -1, y = 5, file = "Brows25Right"}}},
		[106] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows25Right"}}},
		[107] = {direction = 0, brows = {{x = 6, y = 4, file = "Brows25LeftTall"}, {x = 4, y = 4, file = "Brows25Right"}}},
		[108] = {direction = 0, brows = {{x = 5, y = -1, file = "Brows20Left"}, {x = 7, y = -1, file = "Brows20Right"}}},
		[109] = {direction = 0, brows = {{x = 7, y = 1, file = "Brows20Left"}, {x = 8, y = 1, file = "Brows20Right"}}},
		[110] = {direction = 0, brows = {{x = -2, y = 4, file = "Brows25LeftFlat"}, {x = -2, y = 0, file = "Brows25Right"}}},
		[111] = {direction = 0, brows = {{x = 3, y = 8, file = "Brows20Left"}, {x = 9, y = 8, file = "Brows20Right"}}},
		[112] = {direction = 0, brows = {{x = 4, y = 4, file = "Brows20Right"}}},
		[113] = {direction = 0, brows = {{x = 11, y = 0, file = "Brows15Left"}, {x = 8, y = 1, file = "Brows15Right"}}},
		[114] = {direction = 0, brows = {{x = 8, y = 2, file = "Brows25"}}},
		[115] = {direction = 0, brows = {{x = -1, y = -5, file = "Brows25Right"}}},
		[116] = {direction = 0, brows = {{x = -2, y = -1, file = "Brows25Right"}}},
		[117] = {direction = 0, brows = {{x = -3, y = 4, file = "Brows25Right"}}},
		[118] = {direction = 0, brows = {{x = -4, y = 5, file = "Brows25Right"}}},
		[119] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25Right"}}},
		[120] = {direction = 0, brows = {{x = 7, y = 11, file = "Unibrow20"}}},
		[121] = {direction = 0, brows = {{x = 4, y = 6, file = "Unibrow30"}}},
		[122] = {direction = 0, brows = {{x = 14, y = 3, file = "Brows20Left"}, {x = 11, y = 3, file = "Brows20Right"}}},
		[123] = {direction = 0, brows = {{x = 7, y = 8, file = "Brows20Left"}, {x = 5, y = 11, file = "Brows20RightFlat"}}},
		[124] = {direction = 0, brows = {{x = 7, y = 0, file = "Brows25Left"}, {x = 3, y = 0, file = "Brows25Right"}}},
		[125] = {direction = 0, brows = {{x = 8, y = 9, file = "Brows15Left"}, {x = 6, y = 9, file = "Brows15Right"}}},
		[126] = {direction = 0, brows = {{x = 7, y = 7, file = "Brows20"}}},
		[127] = {direction = 0, brows = {{x = 5, y = 5, file = "Brows25LeftFlat"}, {x = 3, y = 2, file = "Brows25RightTall"}}},
		[128] = {direction = 0, brows = {{x = 1, y = 11, file = "Brows15Right"}}},
		[129] = {direction = 0, brows = {{x = -2, y = -2, file = "Brows25Right"}}},
		[130] = {direction = 0, brows = {{x = -5, y = -1, file = "Brows25Right"}}},
		[131] = {direction = 0, brows = {{x = -1, y = 5, file = "Brows25Right"}}},
		[132] = {direction = 0, brows = {{x = 11, y = 4, file = "Brows20Left"}, {x = 11, y = 7, file = "Brows20RightFlat"}}},
		[133] = {direction = 0, brows = {{x = 4, y = 5, file = "Brows25Left"}, {x = 3, y = 8, file = "Brows25RightFlat"}}},
		[134] = {direction = 0, brows = {{x = 4, y = 3, file = "Brows25LeftTall"}, {x = 3, y = 5, file = "Brows25RightFlat"}}},
		[135] = {direction = 0, brows = {{x = -7, y = 2, file = "Brows25RightFlat"}}},
		[136] = {direction = 0, brows = {{x = -4, y = 6, file = "Brows25Right"}}},
		[137] = {direction = 0, brows = {{x = -1, y = -2, file = "Brows30Right"}}},
		[138] = {direction = 0, brows = {{x = 6, y = 5, file = "Brows25Left"}, {x = 3, y = 5, file = "Brows25Right"}}},
		[139] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows25"}}},
		[140] = {direction = 0, brows = {{x = 5, y = 5, file = "Brows25"}}},
		[141] = {direction = 0, brows = {{x = -1, y = 8, file = "Brows25Right"}}},
		[142] = {direction = 0, brows = {{x = 3, y = -4, file = "Brows20Right"}}},
		[143] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows25"}}},
		[144] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows20Right"}}},
		[145] = {direction = 0, brows = {{x = 11, y = 7, file = "Brows15Left"}, {x = 9, y = 7, file = "Brows15Right"}}},
		[146] = {direction = 0, brows = {{x = 0, y = 13, file = "Brows15Right"}}},
		[147] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows25RightFlat"}}},
		[148] = {direction = 0, brows = {{x = 3, y = 4, file = "Brows20Right"}}},
		[149] = {direction = 0, brows = {{x = 2, y = 3, file = "Brows25RightTall"}}},
		[150] = {direction = 0, brows = {{x = -2, y = 8, file = "Brows25Right"}}},
		[151] = {direction = 0, brows = {{x = 4, y = 5, file = "Brows25"}}},
		[152] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows25"}}},
		[153] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Right"}}},
		[154] = {direction = 2, brows = {{x = -2, y = -1, file = "Brows25Right"}}},
		[155] = {direction = 0, brows = {{x = 3, y = 2, file = "Brows25Right"}}},
		[156] = {direction = 0, brows = {{x = -4, y = 8, file = "Brows25RightTall"}}},
		[157] = {direction = 0, brows = {{x = -1, y = -1, file = "Brows20RightFlat"}}},
		[158] = {direction = 0, brows = {{x = 5, y = 4, file = "Brows20RightFlat"}}},
		[159] = {direction = 0, brows = {{x = 0, y = 2, file = "Brows25RightTall"}}},
		[160] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows25Right"}}},
		[161] = {direction = 0, brows = {{x = 11, y = 2, file = "Brows15Left"}, {x = 7, y = 2, file = "Brows15Right"}}},
		[162] = {direction = 0, brows = {{x = 0, y = 3, file = "Brows20Left"}, {x = 0, y = 5, file = "Brows20RightFlat"}}},
		[163] = {direction = 0, brows = {{x = 4, y = -4, file = "Brows30Left"}, {x = 0, y = -4, file = "Brows30Right"}}},
		[164] = {direction = 0, brows = {{x = 6, y = 6, file = "Brows25Left"}, {x = 4, y = 9, file = "Brows25RightFlat"}}},
		[165] = {direction = 0, brows = {{x = 4, y = -2, file = "Brows25"}}},
		[166] = {direction = 0, brows = {{x = -10, y = -1, file = "Brows30Right"}}},
		[167] = {direction = 0, brows = {{x = 5, y = 7, file = "Brows20Left"}, {x = 7, y = 8, file = "Brows20Right"}}},
		[168] = {direction = 0, brows = {{x = -2, y = 9, file = "Brows25Right"}}},
		[169] = {direction = 0, brows = {{x = 3, y = 4, file = "Brows20LeftFlat"}, {x = 1, y = 1, file = "Brows20Right"}}},
		[170] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25LeftTall"}, {x = -1, y = 8, file = "Brows25RightFlat"}}},
		[171] = {direction = 0, brows = {{x = -5, y = 2, file = "Brows25Right"}}},
		[172] = {direction = 0, brows = {{x = 2, y = 3, file = "Brows25LeftTall"}, {x = 6, y = 3, file = "Brows25Right"}}},
		[173] = {direction = 0, brows = {{x = 9, y = 8, file = "Brows15Left"}, {x = 7, y = 8, file = "Brows15Right"}}},
		[174] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows25"}}},
		[175] = {direction = 0, brows = {{x = 13, y = 7, file = "Brows15Left"}, {x = 12, y = 7, file = "Brows15Right"}}},
		[176] = {direction = 2, brows = {{x = -9, y = 14, file = "Brows15Right"}, {x = 0, y = 10, file = "Brows15Right"}}},
		[177] = {direction = 0, brows = {{x = 1, y = 3, file = "Brows30RightFlat"}}},
		[178] = {direction = 0, brows = {{x = -1, y = 0, file = "Brows30RightFlat"}}},
		[179] = {direction = 0, brows = {{x = 4, y = 5, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20Right"}}},
		[180] = {direction = 0, brows = {{x = 4, y = 8, file = "Brows20Left"}, {x = 3, y = 8, file = "Brows20Right"}}},
		[181] = {direction = 0, brows = {{x = 0, y = 7, file = "Brows20Right"}}},
		[182] = {direction = 0, brows = {{x = 5, y = 8, file = "Brows20LeftFlat"}, {x = 3, y = 5, file = "Brows20Right"}}},
		[183] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows20Left"}, {x = 9, y = 6, file = "Brows20Right"}}},
		[184] = {direction = 0, brows = {{x = 5, y = 0, file = "Brows25Left"}, {x = 4, y = 4, file = "Brows25RightFlat"}}},
		[185] = {direction = 0, brows = {{x = 12, y = 3, file = "Brows20Left"}, {x = 10, y = 3, file = "Brows20Right"}}},
		[186] = {direction = 0, brows = {{x = 6, y = 0, file = "Brows25Right"}}},
		[187] = {direction = 0, brows = {{x = 7, y = 9, file = "Brows15Left"}, {x = 8, y = 9, file = "Brows15Right"}}},
		[188] = {direction = 0, brows = {{x = 6, y = 7, file = "Brows20Left"}, {x = 8, y = 12, file = "Brows20RightFlat"}}},
		[189] = {direction = 0, brows = {{x = 2, y = 6, file = "Brows15Left"}, {x = 4, y = 6, file = "Brows15Right"}}},
		[190] = {direction = 0, brows = {{x = 2, y = 6, file = "Brows25Left"}, {x = 5, y = 10, file = "Brows25RightFlat"}}},
		[191] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows30Left"}, {x = 0, y = 1, file = "Brows30Right"}}},
		[192] = {direction = 0, brows = {{x = 7, y = 0, file = "Brows20Left"}, {x = 5, y = 2, file = "Brows20RightFlat"}}},
		[193] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows25Right"}}},
		[194] = {direction = 0, brows = {{x = 6, y = 3, file = "Brows20Left"}, {x = 11, y = 3, file = "Brows20Right"}}},
		[195] = {direction = 0, brows = {{x = 0, y = 3, file = "Brows15Left"}, {x = 12, y = 0, file = "Brows15Right"}}},
		[196] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25LeftTall"}, {x = 0, y = 10, file = "Brows25RightFlat"}}},
		[197] = {direction = 0, brows = {{x = -8, y = 5, file = "Brows30Right"}}},
		[198] = {direction = 0, brows = {{x = 9, y = 10, file = "Brows15Left"}, {x = 3, y = 7, file = "Brows25Right"}}},
		[199] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25Left"}, {x = 1, y = 6, file = "Brows25RightFlat"}}},
		[200] = {direction = 2, brows = {{x = -8, y = 6, file = "Brows25RightTall"}, {x = 1, y = -1, file = "Brows25RightFlat"}}},
		[201] = {direction = 0, brows = {{x = 1, y = 2, file = "Unibrow30"}}},
		[202] = {direction = 1, brows = {{x = 8, y = -5, file = "Brows25Left"}, {x = 19, y = 1, file = "Brows25Left"}}},
		[203] = {direction = 0, brows = {{x = 0, y = 3, file = "Brows25Right"}}},
		[204] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows25Left"}, {x = 3, y = 1, file = "Brows25Right"}}},
		[205] = {direction = 0, brows = {{x = 9, y = 5, file = "Brows25Left"}, {x = 6, y = 5, file = "Brows25Right"}}},
		[206] = {direction = 0, brows = {{x = -6, y = 1, file = "Brows30Right"}}},
		[207] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows25LeftTall"}, {x = 7, y = 3, file = "Brows25RightFlat"}}},
		[208] = {direction = 0, brows = {{x = -6, y = -4, file = "Brows30Right"}}},
		[209] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows20Left"}, {x = 10, y = 9, file = "Brows20RightFlat"}}},
		[210] = {direction = 0, brows = {{x = 10, y = 1, file = "Brows15Left"}, {x = 8, y = 2, file = "Brows15Right"}}},
		[211] = {direction = 0, brows = {{x = 0, y = 4, file = "Brows25LeftFlat"}, {x = 1, y = 0, file = "Brows25Right"}}},
		[212] = {direction = 0, brows = {{x = 6, y = 9, file = "Brows25Left"}, {x = 6, y = 8, file = "Brows25Right"}}},
		[213] = {direction = 0, brows = {{x = -3, y = 2, file = "Brows25LeftTall"}, {x = -4, y = 4, file = "Brows25RightFlat"}}},
		[214] = {direction = 0, brows = {{x = 2, y = 6, file = "Brows25"}}},
		[215] = {direction = 0, brows = {{x = -1, y = 9, file = "Brows25LeftTall"}, {x = 0, y = 9, file = "Brows25Right"}}},
		[216] = {direction = 0, brows = {{x = 5, y = 7, file = "Brows20Left"}, {x = 7, y = 9, file = "Brows20RightFlat"}}},
		[217] = {direction = 0, brows = {{x = -1, y = -2, file = "Brows25Right"}}},
		[218] = {direction = 0, brows = {{x = 0, y = -5, file = "Brows30Left"}, {x = -2, y = -5, file = "Brows30Right"}}},
		[219] = {direction = 0, brows = {{x = 4, y = -8, file = "Brows30Left"}, {x = 2, y = -7, file = "Brows30Right"}}},
		[220] = {direction = 0, brows = {{x = 0, y = 8, file = "Brows20LeftFlat"}, {x = 0, y = 6, file = "Brows20Right"}}},
		[221] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows25"}}},
		[222] = {direction = 0, brows = {{x = 5, y = 11, file = "Brows15Left"}, {x = 5, y = 12, file = "Brows15Right"}}},
		[223] = {direction = 0, brows = {{x = 0, y = 4, file = "Brows25Right"}}},
		[224] = {direction = 0, brows = {{x = -3, y = -4, file = "Brows30Right"}}},
		[225] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows25Left"}, {x = 2, y = 1, file = "Brows25Right"}}},
		[226] = {direction = 0, brows = {{x = 3, y = -1, file = "Brows25RightTall"}}},
		[227] = {direction = 0, brows = {{x = 3, y = 7, file = "Brows20Right"}}},
		[228] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows20Right"}}},
		[229] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows25Right"}}},
		[230] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25RightFlat"}}},
		[231] = {direction = 0, brows = {{x = 11, y = 5, file = "Brows20Right"}}},
		[232] = {direction = 0, brows = {{x = 9, y = 3, file = "Brows20Right"}}},
		[233] = {direction = 0, brows = {{x = 2, y = -2, file = "Brows30Right"}}},
		[234] = {direction = 0, brows = {{x = 5, y = 5, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20Right"}}},
		[235] = {direction = 0, brows = {{x = -2, y = 1, file = "Brows30Right"}}},
		[236] = {direction = 0, brows = {{x = 2, y = 8, file = "Brows15Left"}, {x = -4, y = 4, file = "Brows25Right"}}},
		[237] = {direction = 0, brows = {{x = 4, y = 12, file = "ReverseBrows25"}}},
		[238] = {direction = 0, brows = {{x = 4, y = 2, file = "Brows30Left"}, {x = 2, y = 1, file = "Brows30Right"}}},
		[239] = {direction = 0, brows = {{x = 3, y = 7, file = "Brows25LeftTall"}, {x = 2, y = 6, file = "Brows25Right"}}},
		[240] = {direction = 0, brows = {{x = 13, y = 10, file = "Brows20Left"}, {x = -6, y = 8, file = "Brows20Right"}}},
		[241] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Right"}}},
		[242] = {direction = 0, brows = {{x = 16, y = 2, file = "Brows15Left"}, {x = 12, y = 2, file = "Brows15Right"}}},
		[243] = {direction = 0, brows = {{x = -2, y = -2, file = "Brows25Right"}}},
		[244] = {direction = 0, brows = {{x = -4, y = -2, file = "Brows25Right"}}},
		[245] = {direction = 0, brows = {{x = -5, y = 1, file = "Brows25Right"}}},
		[246] = {direction = 0, brows = {{x = -1, y = 8, file = "Brows25RightTall"}}},
		[247] = {direction = 0, brows = {{x = -6, y = 1, file = "Brows30Right"}}},
		[248] = {direction = 0, brows = {{x = -5, y = -4, file = "Brows25RightFlat"}}},
		[249] = {direction = 0, brows = {{x = -8, y = 0, file = "Brows25Right"}}},
		[250] = {direction = 0, brows = {{x = 3, y = 4, file = "Brows25RightFlat"}}},
		[251] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows30LeftTall"}, {x = 1, y = 8, file = "Brows30RightTall"}}},
		[252] = {direction = 0, brows = {{x = -2, y = -1, file = "Brows30Right"}}},
		[253] = {direction = 0, brows = {{x = -2, y = -1, file = "Brows25RightFlat"}}},
		[254] = {direction = 0, brows = {{x = -5, y = 4, file = "Brows30RightFlat"}}},
		[255] = {direction = 0, brows = {{x = -2, y = 6, file = "Brows25"}}},
		[256] = {direction = 0, brows = {{x = -3, y = 1, file = "Brows25Right"}}},
		[257] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows20Right"}}},
		[258] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows20Left"}, {x = 4, y = 6, file = "Brows20Right"}}},
		[259] = {direction = 0, brows = {{x = 3, y = 2, file = "Brows20Left"}, {x = 5, y = 1, file = "Brows20Right"}}},
		[260] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows20Left"}, {x = -2, y = 5, file = "Brows20Right"}}},
		[261] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		[262] = {direction = 0, brows = {{x = -5, y = 5, file = "Brows25Right"}}},
		[263] = {direction = 0, brows = {{x = -6, y = 3, file = "Brows25Right"}}},
		[264] = {direction = 0, brows = {{x = -5, y = 4, file = "Brows25Right"}}},
		[265] = {direction = 0, brows = {{x = 6, y = 3, file = "Brows25Right"}}},
		[266] = {direction = 0, brows = {{x = -2, y = 3, file = "Brows30Right"}}},
		[267] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows25Right"}}},
		[268] = {direction = 0, brows = {{x = -5, y = 5, file = "Brows30Right"}}},
		[269] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows25LeftTall"}, {x = 0, y = 6, file = "Brows25Right"}}},
		[270] = {direction = 0, brows = {{x = 9, y = 13, file = "Brows20Right"}}},
		[271] = {direction = 1, brows = {{x = 13, y = 5, file = "Brows25Left"}}},
		[272] = {direction = 0, brows = {{x = 11, y = -1, file = "Brows20Left"}, {x = 8, y = 2, file = "Brows20RightFlat"}}},
		[273] = {direction = 0, brows = {{x = 0, y = -2, file = "Brows30Left"}, {x = -1, y = 3, file = "Brows30RightFlat"}}},
		[274] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows25"}}},
		[275] = {direction = 0, brows = {{x = 0, y = 6, file = "Brows20Right"}}},
		[276] = {direction = 0, brows = {{x = 5, y = 3, file = "Brows15Left"}, {x = -4, y = -1, file = "Brows30Right"}}},
		[277] = {direction = 0, brows = {{x = -3, y = -1, file = "Brows25Right"}}},
		[278] = {direction = 1, brows = {{x = 15, y = 5, file = "Brows15Left"}, {x = 21, y = 9, file = "Brows15Left"}}},
		[279] = {direction = 0, brows = {{x = 11, y = 0, file = "Brows20Right"}}},
		[280] = {direction = 0, brows = {{x = 3, y = 2, file = "Brows25"}}},
		[281] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows25Right"}}},
		[282] = {direction = 0, brows = {{x = -3, y = 6, file = "Brows25Right"}}},
		[283] = {direction = 0, brows = {{x = 7, y = 9, file = "Brows20Left"}, {x = 9, y = 11, file = "Brows20RightFlat"}}},
		[284] = {direction = 0, brows = {{x = 6, y = 8, file = "Brows20Left"}, {x = 7, y = 9, file = "Brows20Right"}}},
		[285] = {direction = 0, brows = {{x = 5, y = 7, file = "Unibrow20"}, {x = 12, y = 7, file = "Unibrow20"}}},
		[286] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows20Right"}}},
		[287] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows25Left"}, {x = 2, y = 9, file = "Brows25RightFlat"}}},
		[288] = {direction = 0, brows = {{x = -5, y = 3, file = "Brows25RightTall"}}},
		[289] = {direction = 1, brows = {{x = 7, y = 3, file = "Brows20Left"}, {x = 13, y = 9, file = "Brows20Left"}}},
		[290] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows25Right"}}},
		[291] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows20Left"}, {x = 9, y = 5, file = "Brows20Right"}}},
		[292] = {direction = 0, brows = {{x = 3, y = -1, file = "Brows30Right"}}},
		[293] = {direction = 0, brows = {{x = 8, y = 6, file = "Brows20Left"}, {x = 9, y = 7, file = "Brows20Right"}}},
		[294] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows20LeftFlat"}, {x = 5, y = -1, file = "Brows20Right"}}},
		[295] = {direction = 0, brows = {{x = -4, y = -1, file = "Brows25Right"}}},
		[296] = {direction = 0, brows = {{x = 9, y = 5, file = "Brows20Left"}, {x = 7, y = 8, file = "Brows20RightFlat"}}},
		[297] = {direction = 0, brows = {{x = 3, y = 6, file = "Brows25Right"}}},
		[298] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows20"}}},
		[299] = {direction = 0, brows = {{x = 4, y = 2, file = "Brows25RightFlat"}}},
		[300] = {direction = 0, brows = {{x = 4, y = 9, file = "Brows20"}}},
		[301] = {direction = 0, brows = {{x = 5, y = 8, file = "Brows25LeftTall"}, {x = 4, y = 7, file = "Brows25Right"}}},
		[302] = {direction = 0, brows = {{x = 4, y = 0, file = "Brows25Left"}, {x = 1, y = 4, file = "Brows25RightFlat"}}},
		[303] = {direction = 0, brows = {{x = 22, y = 5, file = "Brows20Left"}}},
		[304] = {direction = 0, brows = {{x = -10, y = -1, file = "Brows30Right"}}},
		[305] = {direction = 2, brows = {{x = 3, y = 7, file = "Brows25RightTall"}}},
		[306] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows25Right"}}},
		[307] = {direction = 0, brows = {{x = 6, y = 8, file = "Brows25Left"}, {x = 4, y = 7, file = "Brows25Right"}}},
		[308] = {direction = 0, brows = {{x = 6, y = 6, file = "Brows25Left"}, {x = 5, y = 7, file = "Brows25Right"}}},
		[309] = {direction = 0, brows = {{x = -3, y = 2, file = "Brows25Right"}}},
		[310] = {direction = 0, brows = {{x = 0, y = 6, file = "Brows20Right"}}},
		[311] = {direction = 0, brows = {{x = 1, y = 7, file = "Brows20LeftFlat"}, {x = 3, y = 3, file = "Brows20Right"}}},
		[312] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows20Left"}, {x = 8, y = 7, file = "Brows20Right"}}},
		[313] = {direction = 1, brows = {{x = 6, y = 3, file = "Brows20Left"}, {x = 16, y = 7, file = "Brows20Left"}}},
		[314] = {direction = 0, brows = {{x = 5, y = 5, file = "Brows25LeftTall"}, {x = 6, y = 5, file = "Brows25RightTall"}}},
		[315] = {direction = 0, brows = {{x = 8, y = 5, file = "Brows20Left"}, {x = 6, y = 5, file = "Brows20Right"}}},
		[316] = {direction = 0, brows = {{x = 7, y = 3, file = "Brows15Left"}, {x = 12, y = 4, file = "Brows15Right"}}},
		[317] = {direction = 0, brows = {{x = 9, y = -1, file = "Brows20Right"}}},
		[318] = {direction = 0, brows = {{x = -4, y = 1, file = "Brows30Right"}}},
		[319] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows25Right"}}},
		[320] = {direction = 0, brows = {{x = 4, y = 3, file = "Brows15Left"}, {x = 8, y = 2, file = "Brows15Right"}}},
		[321] = {direction = 0, brows = {{x = 10, y = 4, file = "Brows15Right"}}},
		[322] = {direction = 0, brows = {{x = 2, y = 1, file = "Brows25Right"}}},
		[323] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25RightTall"}}},
		[324] = {direction = 0, brows = {{x = 1, y = -4, file = "Brows30Right"}}},
		[325] = {direction = 1, brows = {{x = 10, y = 5, file = "Brows20Left"}, {x = 9, y = 8, file = "Brows20RightFlat"}}},
		[326] = {direction = 0, brows = {{x = 0, y = -1, file = "Brows25Right"}, {x = 0, y = -1, file = "Brows25Right"}}},
		[327] = {direction = 1, brows = {{x = 7, y = 3, file = "Brows25Left"}, {x = 19, y = 8, file = "Brows25LeftFlat"}}},
		[328] = {direction = 0, brows = {{x = 17, y = 8, file = "Brows15Right"}}},
		[329] = {direction = 0, brows = {{x = -4, y = 5, file = "Brows30Right"}}},
		[330] = {direction = 0, brows = {{x = 0, y = -2, file = "Brows30"}}},
		[331] = {direction = 0, brows = {{x = 6, y = -1, file = "Brows25Left"}, {x = 5, y = -1, file = "Brows25Right"}}},
		[332] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows25Right"}}},
		[333] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20RightFlat"}}},
		[334] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows20Left"}, {x = 5, y = 5, file = "Brows20Right"}}},
		[335] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows25Left"}, {x = 0, y = 7, file = "Brows25RightFlat"}}},
		[336] = {direction = 0, brows = {{x = -1, y = 0, file = "Brows25Right"}}},
		[337] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows30Right"}}},
		[338] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25Left"}, {x = 5, y = 6, file = "Brows25RightFlat"}}},
		[339] = {direction = 0, brows = {{x = 9, y = 6, file = "Brows15Right"}}},
		[340] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows25Right"}}},
		[341] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows20Left"}, {x = 3, y = 0, file = "Brows25Right"}}},
		[342] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Right"}}},
		[343] = {direction = 0, brows = {{x = -2, y = 1, file = "Brows30Left"}, {x = -2, y = 6, file = "Brows30RightFlat"}}},
		[344] = {
			direction = 0,
			brows = {{x = 8, y = 6, file = "Unibrow20"}, {x = -1, y = 5, file = "Unibrow20"}, {x = 19, y = 8, file = "Unibrow20"}}
		},
		[345] = {direction = 0, brows = {{x = 9, y = -1, file = "Brows25"}}},
		[346] = {direction = 0, brows = {{x = 9, y = 8, file = "Brows25RightTall"}}},
		[347] = {direction = 1, brows = {{x = 2, y = 1, file = "Brows20Left"}, {x = 23, y = 11, file = "Brows20Left"}}},
		[348] = {direction = 0, brows = {{x = -2, y = -4, file = "Brows25Left"}, {x = 8, y = -3, file = "Brows25Right"}}},
		[349] = {direction = 0, brows = {{x = -1, y = -2, file = "Brows30Right"}}},
		[350] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows25RightTall"}}},
		[351] = {direction = 0, brows = {{x = 4, y = 7, file = "Brows15Left"}, {x = 3, y = 8, file = "Brows20RightFlat"}}},
		[352] = {direction = 0, brows = {{x = 6, y = 9, file = "Brows20Right"}}},
		[353] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows30Left"}, {x = 2, y = 6, file = "Brows30RightTall"}}},
		[354] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows25Left"}, {x = 5, y = 5, file = "Brows25Right"}}},
		[355] = {direction = 0, brows = {{x = -9, y = -1, file = "Brows30Right"}}},
		[356] = {direction = 0, brows = {{x = 9, y = 3, file = "Unibrow20"}}},
		[357] = {direction = 0, brows = {{x = -4, y = 7, file = "Brows20Right"}}},
		[358] = {direction = 0, brows = {{x = 2, y = 6, file = "Brows20LeftFlat"}, {x = 3, y = 2, file = "Brows20Right"}}},
		[359] = {direction = 0, brows = {{x = 6, y = 9, file = "Brows20Left"}, {x = 4, y = 10, file = "Brows20Right"}}},
		[360] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Left"}, {x = 0, y = 1, file = "Brows25Right"}}},
		[361] = {direction = 0, brows = {{x = 6, y = 3, file = "Brows20Left"}, {x = 8, y = 3, file = "Brows20Right"}}},
		[362] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows30Left"}, {x = -1, y = 0, file = "Brows30Right"}}},
		[363] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows20Left"}, {x = 5, y = 4, file = "Brows20RightFlat"}}},
		[364] = {direction = 0, brows = {{x = 5, y = 0, file = "Brows20Left"}, {x = 5, y = 0, file = "Brows20Right"}}},
		[365] = {direction = 0, brows = {{x = 7, y = -2, file = "Brows20Right"}}},
		[366] = {direction = 0, brows = {{x = 10, y = 1, file = "Brows20"}}},
		[367] = {direction = 0, brows = {{x = 7, y = 1, file = "Brows20Right"}}},
		[368] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows25Right"}}},
		[369] = {direction = 0, brows = {{x = -4, y = -2, file = "Brows25Right"}}},
		[370] = {direction = 0, brows = {{x = 4, y = 4, file = "Brows20Right"}}},
		[371] = {direction = 0, brows = {{x = 0, y = 5, file = "Brows25Right"}}},
		[372] = {direction = 0, brows = {{x = 7, y = 8, file = "Brows20Left"}, {x = 4, y = 10, file = "Brows20RightFlat"}}},
		[373] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows20Right"}}},
		[374] = {direction = 0, brows = {{x = -4, y = 8, file = "Unibrow20"}}},
		[375] = {direction = 0, brows = {{x = 2, y = -3, file = "Brows25Right"}}},
		[376] = {direction = 0, brows = {{x = 3, y = 7, file = "Brows25LeftTall"}, {x = 8, y = 6, file = "Brows25Right"}}},
		[377] = {direction = 0, brows = {{x = 4, y = 2, file = "Unibrow30"}}},
		[378] = {direction = 0, brows = {{x = -1, y = 7, file = "Unibrow30"}}},
		[379] = {direction = 0, brows = {{x = 4, y = 4, file = "Unibrow30"}}},
		[380] = {direction = 0, brows = {{x = -7, y = 8, file = "Brows25RightFlat"}}},
		[381] = {direction = 0, brows = {{x = -5, y = 17, file = "Brows20RightFlat"}}},
		[382] = {direction = 0, brows = {{x = 2, y = 11, file = "Brows20Right"}}},
		[383] = {direction = 0, brows = {{x = -1, y = 7, file = "Brows25RightTall"}}},
		[384] = {direction = 0, brows = {{x = -4, y = 3, file = "Brows25Right"}}},
		[385] = {direction = 0, brows = {{x = 4, y = 6, file = "Brows25"}}},
		[386] = {direction = 0, brows = {{x = 1, y = 8, file = "Brows25LeftTall"}, {x = 3, y = 8, file = "Brows25RightTall"}}},
		[387] = {direction = 0, brows = {{x = -2, y = 3, file = "Brows25Right"}}},
		[388] = {direction = 0, brows = {{x = 0, y = 10, file = "Brows20Right"}}},
		[389] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows25RightFlat"}}},
		[390] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25Left"}, {x = -1, y = 5, file = "Brows25Right"}}},
		[391] = {direction = 0, brows = {{x = 1, y = 10, file = "Brows20Left"}, {x = 2, y = 9, file = "Brows20Right"}}},
		[392] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows25"}}},
		[393] = {direction = 0, brows = {{x = -4, y = 5, file = "Brows25Right"}}},
		[394] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows25Left"}, {x = -1, y = 6, file = "Brows25Right"}}},
		[395] = {direction = 0, brows = {{x = 3, y = 8, file = "Brows20Left"}, {x = 2, y = 8, file = "Brows20Right"}}},
		[396] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows25Right"}}},
		[397] = {direction = 0, brows = {{x = 4, y = 4, file = "Brows20Right"}}},
		[398] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows20Right"}}},
		[399] = {direction = 0, brows = {{x = 5, y = 2, file = "Brows20Left"}, {x = 9, y = 3, file = "Brows20Right"}}},
		[400] = {direction = 0, brows = {{x = 5, y = -3, file = "Brows25Left"}, {x = 2, y = -3, file = "Brows25Right"}}},
		[401] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows20Left"}, {x = 4, y = 6, file = "Brows20Right"}}},
		[402] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows20Left"}, {x = 11, y = 2, file = "Brows20Right"}}},
		[403] = {direction = 0, brows = {{x = -1, y = 2, file = "Brows25LeftTall"}, {x = 5, y = 4, file = "Brows25RightFlat"}}},
		[404] = {direction = 0, brows = {{x = 2, y = 7, file = "Brows25LeftTall"}, {x = 8, y = 7, file = "Brows25RightTall"}}},
		[405] = {direction = 2, brows = {{x = -1, y = 10, file = "Brows25RightTall"}}},
		[406] = {direction = 0, brows = {{x = 10, y = 8, file = "Brows15Left"}, {x = 14, y = 8, file = "Brows15Right"}}},
		[407] = {direction = 0, brows = {{x = 5, y = 3, file = "Brows25LeftFlat"}, {x = 2, y = 0, file = "Brows25Right"}}},
		[408] = {direction = 0, brows = {{x = 4, y = 10, file = "Brows25RightTall"}}},
		[409] = {direction = 0, brows = {{x = 0, y = 11, file = "Brows25RightTall"}}},
		[410] = {direction = 0, brows = {{x = -1, y = 5, file = "Brows25LeftTall"}, {x = 2, y = 7, file = "Brows25RightFlat"}}},
		[411] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows25LeftTall"}, {x = 6, y = 9, file = "Brows25RightFlat"}}},
		[412] = {direction = 0, brows = {{x = 8, y = 3, file = "Brows15"}}},
		[413] = {direction = 0, brows = {{x = 12, y = 5, file = "Brows15Left"}, {x = 11, y = 5, file = "Brows15Right"}}},
		[414] = {direction = 0, brows = {{x = 7, y = 4, file = "Brows20Left"}, {x = 5, y = 4, file = "Brows20Right"}}},
		[415] = {
			direction = 0,
			brows = {
				{x = 3, y = 1, file = "Brows15Left"},
				{x = 1, y = 2, file = "Brows15Right"},
				{x = 18, y = 2, file = "Brows15Left"},
				{x = 15, y = 3, file = "Brows15Right"},
				{x = 10, y = 15, file = "Brows15Left"},
				{x = 7, y = 15, file = "Brows15Right"}
			}
		},
		[416] = {direction = 0, brows = {{x = 11, y = 7, file = "Brows20Left"}, {x = 9, y = 7, file = "Brows20Right"}}},
		[417] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows20Left"}, {x = 5, y = 8, file = "Brows20RightFlat"}}},
		[418] = {direction = 0, brows = {{x = -2, y = 3, file = "Brows25Right"}}},
		[419] = {direction = 0, brows = {{x = -2, y = 0, file = "Brows25Right"}}},
		[420] = {direction = 0, brows = {{x = 4, y = 9, file = "Brows20Left"}, {x = 8, y = 9, file = "Brows20Right"}}},
		[421] = {direction = 0, brows = {{x = 8, y = 8, file = "Brows25"}}},
		[422] = {direction = 0, brows = {{x = 0, y = 2, file = "Brows25Right"}}},
		[423] = {
			direction = 0,
			brows = {{x = 7, y = 6, file = "Brows15Left"}, {x = 11, y = 1, file = "Brows15Right"}, {x = 6, y = 2, file = "Unibrow20"}}
		},
		[424] = {direction = 0, brows = {{x = 6, y = 7, file = "Brows20Left"}, {x = 12, y = 7, file = "Brows20Right"}}},
		[425] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows20Left"}, {x = 8, y = 5, file = "Brows20Right"}}},
		[426] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows15Left"}, {x = 13, y = 7, file = "Brows15Right"}}},
		[427] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows20Left"}, {x = 2, y = 11, file = "Brows20RightFlat"}}},
		[428] = {direction = 0, brows = {{x = 4, y = 5, file = "Brows25Right"}}},
		[429] = {direction = 0, brows = {{x = 3, y = 2, file = "Brows25Left"}, {x = 2, y = 1, file = "Brows25Right"}}},
		[430] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows25Right"}}},
		[431] = {direction = 2, brows = {{x = -3, y = -2, file = "Brows30Right"}}},
		[432] = {direction = 0, brows = {{x = 4, y = 4, file = "Brows25Left"}, {x = 7, y = 4, file = "Brows25Right"}}},
		[433] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows20Left"}, {x = 16, y = 11, file = "Brows20LeftFlat"}}},
		[434] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25LeftTall"}, {x = 2, y = 2, file = "Brows25RightTall"}}},
		[435] = {direction = 0, brows = {{x = -3, y = 4, file = "Brows25Right"}}},
		[436] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows25Left"}, {x = 7, y = 2, file = "Brows25Right"}}},
		[437] = {direction = 0, brows = {{x = 4, y = 3, file = "Brows25Left"}, {x = 7, y = 4, file = "Brows25Right"}}},
		[438] = {direction = 0, brows = {{x = 7, y = 5, file = "Brows20Left"}, {x = 6, y = 9, file = "Brows20RightFlat"}}},
		[439] = {direction = 0, brows = {{x = 6, y = 6, file = "Brows20Left"}, {x = 9, y = 7, file = "Brows20Right"}}},
		[440] = {direction = 0, brows = {{x = 11, y = 4, file = "Brows15Left"}, {x = 9, y = 4, file = "Brows15Right"}}},
		[441] = {direction = 0, brows = {{x = -1, y = 5, file = "Brows25RightFlat"}}},
		[442] = {direction = 0, brows = {{x = 12, y = 5, file = "Brows20Left"}, {x = 9, y = 5, file = "Brows20Right"}}},
		[443] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows20Right"}}},
		[444] = {direction = 0, brows = {{x = -4, y = 5, file = "Brows25Right"}}},
		[445] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows20Right"}}},
		[446] = {direction = 0, brows = {{x = 4, y = 0, file = "Brows25Left"}, {x = 1, y = 1, file = "Brows25Right"}}},
		[447] = {direction = 0, brows = {{x = -1, y = 1, file = "Brows30LeftTall"}, {x = -1, y = 1, file = "Brows30RightTall"}}},
		[448] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		[449] = {direction = 0, brows = {{x = 19, y = -4, file = "Brows15Left"}, {x = 16, y = -4, file = "Brows15Right"}}},
		[450] = {direction = 0, brows = {{x = 13, y = 3, file = "Brows20RightFlat"}}},
		[451] = {direction = 0, brows = {{x = 2, y = -5, file = "Brows30"}}},
		[452] = {direction = 0, brows = {{x = -3, y = -2, file = "Brows25LeftTall"}, {x = 7, y = -3, file = "Brows25RightTall"}}},
		[453] = {direction = 0, brows = {{x = 0, y = -4, file = "Brows25Left"}, {x = 1, y = -4, file = "Brows25Right"}}},
		[454] = {direction = 0, brows = {{x = 4, y = 4, file = "Brows25Right"}}},
		[455] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows25LeftFlat"}, {x = 4, y = -1, file = "Brows25Right"}}},
		[456] = {direction = 0, brows = {{x = -4, y = 6, file = "Brows25Right"}}},
		[457] = {direction = 0, brows = {{x = -2, y = -1, file = "Brows25Right"}}},
		[458] = {direction = 0, brows = {{x = -1, y = 2, file = "Brows25Left"}, {x = -1, y = 1, file = "Brows25Right"}}},
		[459] = {direction = 0, brows = {{x = 6, y = 0, file = "Brows20Left"}, {x = 6, y = 0, file = "Brows20Right"}}},
		[460] = {direction = 0, brows = {{x = 9, y = 0, file = "Brows20Left"}, {x = 6, y = 0, file = "Brows20Right"}}},
		[461] = {direction = 0, brows = {{x = 6, y = 7, file = "Brows25Left"}, {x = 5, y = 8, file = "Brows25Right"}}},
		[462] = {direction = 0, brows = {{x = 5, y = 3, file = "Unibrow30"}, {x = -5, y = 10, file = "Unibrow20"}}},
		[463] = {direction = 0, brows = {{x = 9, y = 1, file = "Brows15Left"}, {x = 12, y = 1, file = "Brows15Right"}}},
		[464] = {direction = 0, brows = {{x = -1, y = 3, file = "Brows25Right"}}},
		[465] = {direction = 0, brows = {{x = 12, y = 7, file = "Brows15Left"}, {x = 9, y = 7, file = "Brows15Right"}}},
		[466] = {direction = 0, brows = {{x = 9, y = 9, file = "Brows20LeftFlat"}, {x = 8, y = 7, file = "Brows20Right"}}},
		[467] = {direction = 0, brows = {{x = 3, y = 6, file = "Brows25"}}},
		[468] = {direction = 0, brows = {{x = -3, y = 6, file = "Brows20Right"}}},
		[469] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows30Left"}, {x = 1, y = 6, file = "Brows30RightFlat"}}},
		[470] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows25Left"}, {x = 0, y = 6, file = "Brows25Right"}}},
		[471] = {direction = 0, brows = {{x = 4, y = 9, file = "Brows15Left"}, {x = -3, y = 8, file = "Brows25RightFlat"}}},
		[472] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows25Left"}, {x = 4, y = 1, file = "Brows25Right"}}},
		[473] = {direction = 0, brows = {{x = 6, y = -1, file = "Brows20Left"}, {x = 7, y = -1, file = "Brows20Right"}}},
		[474] = {direction = 0, brows = {{x = 1, y = -1, file = "Brows30Right"}}},
		[475] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows25Right"}}},
		[476] = {direction = 0, brows = {{x = 8, y = -1, file = "Brows20RightFlat"}}},
		[477] = {direction = 0, brows = {{x = 4, y = 9, file = "Unibrow30"}}},
		[478] = {direction = 0, brows = {{x = -4, y = 1, file = "Brows25Right"}}},
		[479] = {direction = 0, brows = {{x = 0, y = 0, file = "Brows25LeftTall"}, {x = 2, y = 3, file = "Brows25RightFlat"}}},
		[480] = {direction = 0, brows = {{x = 0, y = 7, file = "Brows25Left"}, {x = 1, y = 7, file = "Brows25RightTall"}}},
		[481] = {direction = 0, brows = {{x = 2, y = 3, file = "Brows30LeftTall"}, {x = 2, y = 2, file = "Brows30Right"}}},
		[482] = {direction = 0, brows = {{x = -1, y = 3, file = "Brows30"}}},
		[483] = {direction = 0, brows = {{x = -5, y = 2, file = "Brows25Right"}}},
		[484] = {direction = 0, brows = {{x = -1, y = 3, file = "Brows25RightFlat"}}},
		[485] = {direction = 0, brows = {{x = 0, y = 1, file = "Brows25LeftTall"}, {x = 5, y = 1, file = "Brows25Right"}}},
		[486] = {direction = 0, brows = {{x = 2, y = -1, file = "Unibrow30"}}},
		[487] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows25Right"}}},
		[488] = {direction = 0, brows = {{x = 2, y = 8, file = "Brows20Right"}}},
		[489] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows25LeftTall"}, {x = 7, y = 8, file = "Brows25RightFlat"}}},
		[490] = {direction = 0, brows = {{x = 0, y = 2, file = "Brows25Left"}, {x = 8, y = 7, file = "Brows25RightFlat"}}},
		[491] = {direction = 0, brows = {{x = -6, y = 4, file = "Brows30Right"}}},
		[492] = {direction = 0, brows = {{x = -1, y = 8, file = "Brows15Right"}}},
		[493] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		[494] = {direction = 0, brows = {{x = -2, y = -3, file = "Brows30Left"}, {x = -3, y = -2, file = "Brows30Right"}}},
		[495] = {direction = 0, brows = {{x = 3, y = -3, file = "Brows30RightFlat"}}},
		[496] = {direction = 2, brows = {{x = -5, y = 3, file = "Brows30RightTall"}}},
		[497] = {direction = 0, brows = {{x = 1, y = -4, file = "Brows30RightFlat"}}},
		[498] = {direction = 0, brows = {{x = -4, y = -4, file = "Brows30Right"}}},
		[499] = {direction = 0, brows = {{x = 4, y = 0, file = "Brows25Left"}, {x = 5, y = 0, file = "Brows25Right"}}},
		[500] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows20Left"}, {x = 8, y = 7, file = "Brows20Right"}}},
		[501] = {direction = 0, brows = {{x = 3, y = 5, file = "Brows20Left"}, {x = 13, y = 8, file = "Brows20RightFlat"}}},
		[502] = {direction = 0, brows = {{x = 5, y = 9, file = "Brows20Left"}, {x = 7, y = 9, file = "Brows20Right"}}},
		[503] = {direction = 0, brows = {{x = -3, y = 0, file = "Brows25Right"}}},
		[504] = {direction = 0, brows = {{x = 4, y = 0, file = "Brows25Left"}, {x = 4, y = 0, file = "Brows25RightTall"}}},
		[505] = {direction = 0, brows = {{x = 1, y = -2, file = "Brows30LeftTall"}, {x = -1, y = -2, file = "Brows30RightTall"}}},
		[506] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows25Left"}, {x = 4, y = 1, file = "Brows25Right"}}},
		[507] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows25Left"}, {x = 2, y = 4, file = "Brows25RightFlat"}}},
		[508] = {direction = 0, brows = {{x = 4, y = 6, file = "Brows20LeftFlat"}, {x = 0, y = 1, file = "Brows25Right"}}},
		[509] = {direction = 0, brows = {{x = 2, y = 8, file = "Brows25Left"}, {x = 3, y = 8, file = "Brows25Right"}}},
		[510] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25Right"}}},
		[511] = {direction = 0, brows = {{x = 6, y = 0, file = "Brows25Left"}, {x = 6, y = 3, file = "Brows25RightFlat"}}},
		[512] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows25"}}},
		[513] = {direction = 0, brows = {{x = -7, y = 7, file = "Brows20RightFlat"}, {x = 16, y = 9, file = "Brows20LeftFlat"}}},
		[514] = {direction = 0, brows = {{x = 6, y = 8, file = "Brows20Left"}, {x = 7, y = 8, file = "Brows20Right"}}},
		[515] = {direction = 0, brows = {{x = 4, y = 2, file = "Brows20Left"}, {x = 5, y = 3, file = "Brows20RightFlat"}}},
		[516] = {direction = 0, brows = {{x = 9, y = 6, file = "Brows20Left"}, {x = 9, y = 8, file = "Brows20RightFlat"}}},
		[517] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows25Right"}}},
		[518] = {direction = 3, brows = {{x = 12, y = 8, file = "Brows15Left"}}},
		[519] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows25RightFlat"}}},
		[520] = {direction = 2, brows = {{x = 2, y = 4, file = "Brows25RightTall"}}},
		[521] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows25Right"}}},
		["521-f"] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25RightTall"}}},
		[522] = {direction = 0, brows = {{x = -1, y = 3, file = "Brows25Right"}}},
		[523] = {direction = 0, brows = {{x = -4, y = 2, file = "Brows30Right"}}},
		[524] = {direction = 0, brows = {{x = 0, y = 8, file = "Unibrow30"}}},
		[525] = {direction = 0, brows = {{x = 8, y = 2, file = "Brows25Left"}, {x = 5, y = 2, file = "Brows25Right"}}},
		[526] = {direction = 0, brows = {{x = -1, y = 6, file = "Brows30RightTall"}}},
		[527] = {direction = 0, brows = {{x = 4, y = 6, file = "Brows20Left"}, {x = 14, y = 5, file = "Brows20Right"}}},
		[528] = {direction = 0, brows = {{x = 2, y = 9, file = "Brows15Left"}, {x = 6, y = 3, file = "Brows20Right"}}},
		[529] = {direction = 0, brows = {{x = 10, y = 3, file = "Brows20RightFlat"}}},
		[530] = {direction = 0, brows = {{x = 2, y = 3, file = "Brows25RightTall"}}},
		[531] = {direction = 0, brows = {{x = 6, y = 1, file = "Brows25LeftTall"}, {x = 9, y = 3, file = "Brows25RightFlat"}}},
		[532] = {direction = 2, brows = {{x = -8, y = 12, file = "Brows15Right"}, {x = -2, y = 5, file = "Brows25RightTall"}}},
		[533] = {direction = 2, brows = {{x = 3, y = 4, file = "Brows20Right"}, {x = -5, y = 12, file = "Brows15Right"}}},
		[534] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25RightFlat"}}},
		[535] = {direction = 0, brows = {{x = 15, y = 2, file = "Brows25LeftTall"}, {x = -3, y = 0, file = "Brows25RightFlat"}}},
		[536] = {direction = 0, brows = {{x = 6, y = 4, file = "Brows25Left"}, {x = 5, y = 5, file = "Brows25Right"}}},
		[537] = {direction = 0, brows = {{x = 17, y = 7, file = "Brows25LeftFlat"}, {x = -7, y = 6, file = "Brows25RightFlat"}}},
		[538] = {direction = 0, brows = {{x = 2, y = 7, file = "Brows25LeftFlat"}, {x = 1, y = 5, file = "Brows25Right"}}},
		[539] = {direction = 0, brows = {{x = 9, y = 6, file = "Brows15Left"}, {x = 4, y = 3, file = "Brows25Right"}}},
		[540] = {direction = 0, brows = {{x = 2, y = 7, file = "Brows20Left"}, {x = 7, y = 7, file = "Brows20Right"}}},
		[541] = {direction = 0, brows = {{x = 0, y = 4, file = "Brows25Left"}, {x = 3, y = 4, file = "Brows25Right"}}},
		[542] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows25LeftTall"}, {x = 7, y = 9, file = "Brows25RightFlat"}}},
		[543] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows30"}}},
		[544] = {direction = 0, brows = {{x = -3, y = 6, file = "Unibrow30"}}},
		[545] = {direction = 2, brows = {{x = -3, y = 2, file = "Brows25Right"}}},
		[546] = {direction = 0, brows = {{x = 5, y = 4, file = "Brows20Left"}, {x = 9, y = 3, file = "Brows20Right"}}},
		[547] = {direction = 0, brows = {{x = 7, y = 8, file = "Brows20LeftFlat"}, {x = 6, y = 5, file = "Brows20Right"}}},
		[548] = {direction = 0, brows = {{x = 6, y = 8, file = "Brows20Left"}, {x = 7, y = 8, file = "Brows20Right"}}},
		[549] = {direction = 0, brows = {{x = 6, y = 4, file = "Brows20Left"}, {x = 6, y = 7, file = "Brows20RightFlat"}}},
		[550] = {direction = 0, brows = {{x = 0, y = -1, file = "Brows25Right"}}},
		[551] = {direction = 0, brows = {{x = 7, y = -7, file = "Brows25Left"}, {x = 7, y = -5, file = "Brows25Right"}}},
		[552] = {direction = 0, brows = {{x = 9, y = -5, file = "Brows25Left"}, {x = 7, y = -5, file = "Brows25Right"}}},
		[553] = {direction = 0, brows = {{x = 1, y = 3, file = "Brows25LeftTall"}, {x = 3, y = 3, file = "Brows25Right"}}},
		[554] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25LeftFlat"}, {x = 5, y = 1, file = "Brows25RightTall"}}},
		[555] = {direction = 0, brows = {{x = 0, y = 1, file = "Brows25LeftTall"}, {x = 0, y = 1, file = "Brows25Right"}}},
		[556] = {direction = 0, brows = {{x = -1, y = 7, file = "Brows25LeftFlat"}, {x = 2, y = 3, file = "Brows25RightTall"}}},
		[557] = {direction = 0, brows = {{x = 4, y = -7, file = "Brows25Left"}, {x = 3, y = -7, file = "Brows25Right"}}},
		[558] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows25LeftFlat"}, {x = 2, y = 2, file = "Brows25RightFlat"}}},
		[559] = {direction = 0, brows = {{x = 0, y = 2, file = "Brows20Left"}, {x = 12, y = 2, file = "Brows20Right"}}},
		[560] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows15Left"}, {x = 7, y = 1, file = "Brows25Right"}}},
		[561] = {direction = 0, brows = {{x = 3, y = 6, file = "Unibrow20"}}},
		[562] = {direction = 0, brows = {{x = -2, y = 0, file = "Brows25RightFlat"}}},
		[563] = {direction = 0, brows = {{x = 6, y = 4, file = "Brows20LeftFlat"}, {x = 4, y = 2, file = "Brows20Right"}}},
		[564] = {direction = 0, brows = {{x = 2, y = 5, file = "Brows25Right"}}},
		[565] = {direction = 0, brows = {{x = -3, y = 4, file = "Brows25Right"}}},
		[566] = {direction = 0, brows = {{x = 4, y = -2, file = "Brows25Right"}}},
		[567] = {direction = 0, brows = {{x = -1, y = 1, file = "Brows25RightTall"}}},
		[568] = {direction = 0, brows = {{x = 0, y = 1, file = "Brows25Left"}, {x = 8, y = 5, file = "Brows25RightFlat"}}},
		[569] = {direction = 0, brows = {{x = 2, y = 1, file = "Brows25Left"}, {x = 7, y = 4, file = "Brows25RightFlat"}}},
		[570] = {direction = 0, brows = {{x = 0, y = 6, file = "Brows25LeftTall"}, {x = 4, y = 4, file = "Brows25Right"}}},
		[571] = {direction = 0, brows = {{x = -2, y = 10, file = "Brows25RightTall"}}},
		[572] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25Left"}, {x = 6, y = 3, file = "Brows25Right"}}},
		[573] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows25Left"}, {x = 3, y = 4, file = "Brows25Right"}}},
		[574] = {direction = 0, brows = {{x = 2, y = -1, file = "Brows25Left"}, {x = 6, y = 2, file = "Brows25RightFlat"}}},
		[575] = {direction = 0, brows = {{x = 0, y = 5, file = "Brows25LeftFlat"}, {x = -2, y = 1, file = "Brows25Right"}}},
		[576] = {direction = 0, brows = {{x = -2, y = 1, file = "Brows30Left"}, {x = -4, y = 2, file = "Brows30Right"}}},
		[577] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows20Left"}, {x = 9, y = 7, file = "Brows20RightFlat"}}},
		[578] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows20Left"}, {x = 6, y = 2, file = "Brows20Right"}}},
		[579] = {direction = 0, brows = {{x = -2, y = 6, file = "Brows20Left"}, {x = 11, y = 9, file = "Brows20RightFlat"}}},
		[580] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows20Left"}, {x = 10, y = 4, file = "Brows20RightFlat"}}},
		[581] = {direction = 0, brows = {{x = 3, y = 9, file = "Brows20Right"}}},
		[582] = {direction = 0, brows = {{x = 4, y = 2, file = "Brows25Left"}, {x = 3, y = 2, file = "Brows25Right"}}},
		[583] = {direction = 0, brows = {{x = 10, y = 2, file = "Brows20LeftFlat"}, {x = 16, y = 4, file = "Brows20LeftFlat"}}},
		[584] = {
			direction = 1,
			brows = {
				{x = 0, y = -1, file = "Brows20Left"},
				{x = 6, y = 3, file = "Brows20LeftFlat"},
				{x = 19, y = 6, file = "Brows20Left"},
				{x = 26, y = 9, file = "Brows20LeftFlat"}
			}
		},
		[585] = {direction = 1, brows = {{x = 8, y = 7, file = "Brows25LeftTall"}}},
		[586] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		[587] = {direction = 0, brows = {{x = 1, y = 7, file = "Brows20LeftFlat"}, {x = 6, y = 3, file = "Brows20Right"}}},
		[588] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows25LeftTall"}, {x = 4, y = 0, file = "Brows25Right"}}},
		[589] = {direction = 0, brows = {{x = 1, y = 4, file = "Brows20Right"}}},
		[590] = {direction = 0, brows = {{x = 8, y = 5, file = "Brows15Left"}, {x = 7, y = 7, file = "Brows15Right"}}},
		[591] = {direction = 0, brows = {{x = 5, y = 8, file = "Brows20LeftFlat"}, {x = 3, y = 6, file = "Brows20Right"}}},
		[592] = {direction = 0, brows = {{x = 1, y = 1, file = "Brows25Left"}, {x = -1, y = 1, file = "Brows25Right"}}},
		[593] = {direction = 0, brows = {{x = 5, y = 2, file = "Brows20Left"}, {x = 6, y = 2, file = "Brows20Right"}}},
		[594] = {direction = 0, brows = {{x = -2, y = 0, file = "Brows25RightFlat"}}},
		[595] = {direction = 0, brows = {{x = 1, y = 5, file = "Brows25LeftTall"}, {x = 4, y = 5, file = "Brows25Right"}}},
		[596] = {direction = 0, brows = {{x = 1, y = 7, file = "Brows15Left"}, {x = 4, y = 7, file = "Brows25RightFlat"}}},
		[597] = {direction = 0, brows = {{x = 2, y = 2, file = "Brows25Left"}, {x = 1, y = 2, file = "Brows25Right"}}},
		[598] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows25LeftFlat"}, {x = 4, y = 1, file = "Brows25RightFlat"}}},
		[599] = {direction = 0, brows = {{x = 2, y = -3, file = "Brows15Left"}, {x = 8, y = 15, file = "Brows15Right"}}},
		[600] = {direction = 0, brows = {{x = 5, y = 1, file = "Brows15Left"}}},
		[601] = {direction = 0, brows = {{x = 7, y = -1, file = "Brows15Left"}}},
		[602] = {direction = 0, brows = {{x = -3, y = 2, file = "Brows25Right"}}},
		[603] = {direction = 0, brows = {{x = 5, y = 4, file = "Brows20Right"}}},
		[604] = {direction = 1, brows = {{x = -1, y = 4, file = "Brows20Right"}}},
		[605] = {direction = 0, brows = {{x = 0, y = 12, file = "Brows25LeftFlat"}, {x = 2, y = 9, file = "Brows25RightTall"}}},
		[606] = {direction = 0, brows = {{x = 1, y = 10, file = "Brows25LeftFlat"}, {x = 0, y = 7, file = "Brows25Right"}}},
		[607] = {direction = 0, brows = {{x = 10, y = 14, file = "Brows15Right"}}},
		[608] = {direction = 2, brows = {{x = -9, y = 11, file = "Brows20RightFlat"}, {x = 9, y = 3, file = "Brows20Right"}}},
		[609] = {direction = 0, brows = {{x = 4, y = 1, file = "Brows25Right"}}},
		[610] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows25Right"}}},
		[611] = {direction = 0, brows = {{x = -3, y = -1, file = "Brows25Right"}}},
		[612] = {direction = 2, brows = {{x = 1, y = 6, file = "Brows15Right"}}},
		[613] = {direction = 0, brows = {{x = 5, y = 6, file = "Brows20Right"}}},
		[614] = {direction = 0, brows = {{x = 0, y = -3, file = "Brows25Right"}}},
		[615] = {direction = 0, brows = {{x = 0, y = 5, file = "Brows25LeftFlat"}, {x = 3, y = 1, file = "Brows25Right"}}},
		[616] = {direction = 0, brows = {{x = 4, y = 8, file = "Brows30RightFlat"}}},
		[617] = {direction = 0, brows = {{x = -1, y = 9, file = "Brows25Right"}}},
		[618] = {direction = 1, brows = {{x = 5, y = 6, file = "Brows20LeftFlat"}, {x = 10, y = 8, file = "Brows20RightFlat"}}},
		[619] = {direction = 0, brows = {{x = 1, y = 10, file = "Brows15Left"}, {x = -6, y = 10, file = "Brows25RightFlat"}}},
		[620] = {direction = 1, brows = {{x = 10, y = 5, file = "Brows20LeftFlat"}}},
		[621] = {direction = 0, brows = {{x = -3, y = -1, file = "Brows25Right"}}},
		[622] = {direction = 0, brows = {{x = 6, y = 0, file = "Brows25Left"}, {x = 3, y = 0, file = "Brows25Right"}}},
		[623] = {direction = 0, brows = {{x = 7, y = 1, file = "Brows20Left"}, {x = 4, y = 1, file = "Brows20Right"}}},
		[624] = {direction = 2, brows = {{x = -1, y = 7, file = "Brows30Right"}}},
		[625] = {direction = 0, brows = {{x = 4, y = 12, file = "Brows20Right"}}},
		[626] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows25Right"}}},
		[627] = {direction = 1, brows = {{x = 5, y = 4, file = "Brows20Left"}, {x = 5, y = 7, file = "Brows20RightFlat"}}},
		[628] = {direction = 0, brows = {{x = -3, y = 8, file = "Brows20Right"}}},
		[629] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows20Left"}, {x = 6, y = 4, file = "Brows20RightFlat"}}},
		[630] = {direction = 0, brows = {{x = -3, y = 0, file = "Brows30Right"}}},
		[631] = {direction = 0, brows = {{x = -5, y = -4, file = "Brows30Right"}}},
		[632] = {direction = 0, brows = {{x = 0, y = 4, file = "Brows25"}}},
		[633] = {direction = 0, brows = {{x = 0, y = 1, file = "Brows25Right"}}},
		[634] = {direction = 0, brows = {{x = 16, y = 4, file = "Brows20Left"}, {x = -6, y = 4, file = "Brows20Right"}}},
		[635] = {direction = 0, brows = {{x = -2, y = 3, file = "Brows25RightTall"}}},
		[636] = {direction = 0, brows = {{x = 7, y = 4, file = "Brows20Right"}}},
		[637] = {direction = 0, brows = {{x = 6, y = 7, file = "Brows20Left"}, {x = 6, y = 6, file = "Brows20Right"}}},
		[638] = {direction = 0, brows = {{x = -5, y = 2, file = "Brows25Right"}}},
		[639] = {direction = 0, brows = {{x = -1, y = 0, file = "Brows25Right"}}},
		[640] = {direction = 0, brows = {{x = -2, y = 5, file = "Brows25RightFlat"}}},
		[641] = {direction = 2, brows = {{x = -7, y = 6, file = "Brows15Right"}, {x = 1, y = 2, file = "Brows15Right"}}},
		[642] = {direction = 0, brows = {{x = 5, y = 3, file = "Brows20Left"}, {x = 4, y = 2, file = "Brows20Right"}}},
		[643] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows25RightFlat"}}},
		[644] = {direction = 0, brows = {{x = -2, y = 2, file = "Brows20Right"}}},
		[645] = {direction = 0, brows = {{x = 8, y = 4, file = "Brows20Left"}, {x = 6, y = 4, file = "Brows20Right"}}},
		[646] = {direction = 0, brows = {{x = -2, y = 8, file = "Brows20Right"}}},
		[647] = {direction = 2, brows = {{x = -1, y = 6, file = "Brows25RightTall"}}},
		[648] = {direction = 0, brows = {{x = 2, y = 7, file = "Brows20LeftFlat"}, {x = 0, y = 3, file = "Brows25RightTall"}}},
		[649] = {direction = 2, brows = {{x = -4, y = 3, file = "Brows30Right"}}},
		["Arceus-1"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-2"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-3"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-4"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-5"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-6"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-7"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-8"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-9"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-10"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-11"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-12"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-13"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-14"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-15"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Arceus-16"] = {direction = 0, brows = {{x = -6, y = 7, file = "Brows25Right"}}},
		["Basculin R-1"] = {direction = 0, brows = {{x = -9, y = 1, file = "Brows30RightTall"}}},
		["Burmy P-1"] = {direction = 0, brows = {{x = 7, y = 3, file = "Brows15Left"}, {x = 9, y = 3, file = "Brows15Right"}}},
		["Burmy P-2"] = {direction = 0, brows = {{x = 7, y = 3, file = "Brows15Left"}, {x = 9, y = 3, file = "Brows15Right"}}},
		["Castform-1"] = {direction = 1, brows = {{x = 9, y = 4, file = "Brows20Left"}, {x = 20, y = 8, file = "Brows20Left"}}},
		["Castform-2"] = {direction = 0, brows = {{x = 7, y = 6, file = "Brows20Left"}, {x = 8, y = 6, file = "Brows20Right"}}},
		["Castform-3"] = {direction = 0, brows = {{x = 6, y = 8, file = "Brows20Left"}, {x = 5, y = 8, file = "Brows20Right"}}},
		["Cherrim O-1"] = {
			direction = 0,
			brows = {{x = 7, y = 5, file = "Brows20Left"}, {x = 9, y = 7, file = "Brows20RightFlat"}}
		},
		["Darmanitan-1"] = {
			direction = 0,
			brows = {{x = 3, y = 5, file = "Brows20LeftFlat"}, {x = 1, y = 3, file = "Brows25RightFlat"}}
		},
		["Deerling-1"] = {direction = 0, brows = {{x = 9, y = 5, file = "Brows25Left"}}},
		["Deerling-2"] = {direction = 0, brows = {{x = 9, y = 5, file = "Brows25Left"}}},
		["Deerling-3"] = {direction = 0, brows = {{x = 9, y = 5, file = "Brows25Left"}}},
		["Deoxys-1"] = {direction = 0, brows = {{x = -4, y = 6, file = "Brows25Right"}}},
		["Deoxys-2"] = {direction = 0, brows = {{x = -1, y = 4, file = "Brows25Right"}}},
		["Deoxys-3"] = {direction = 0, brows = {{x = -7, y = 8, file = "Brows25Right"}}},
		["Frillish M-1"] = {direction = 0, brows = {{x = 3, y = 6, file = "Brows20Left"}, {x = 5, y = 6, file = "Brows20Right"}}},
		["Gastrodon W-1"] = {
			direction = 1,
			brows = {
				{x = 5, y = 4, file = "Brows15Left"},
				{x = 3, y = 4, file = "Brows25RightFlat"},
				{x = 6, y = 1, file = "Unibrow20"}
			}
		},
		["Giratina A-1"] = {direction = 0, brows = {{x = 1, y = 6, file = "Brows20Right"}}},
		["Jellicent M-1"] = {
			direction = 0,
			brows = {{x = 0, y = 4, file = "Brows20LeftFlat"}, {x = 5, y = -2, file = "Brows20Right"}}
		},
		["Keldeo-1"] = {direction = 0, brows = {{x = 3, y = 4, file = "Brows25RightTall"}}},
		["Kyurem-1"] = {direction = 0, brows = {{x = -3, y = 9, file = "Brows20Right"}}},
		["Kyurem-2"] = {direction = 0, brows = {{x = -5, y = 10, file = "Brows20Right"}}},
		["Landorus-1"] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows25LeftTall"}, {x = 0, y = 3, file = "Brows25Right"}}},
		["Meloetta A-1"] = {direction = 0, brows = {{x = 0, y = 7, file = "Brows25Left"}, {x = -1, y = 7, file = "Brows25Right"}}},
		["Rotom-1"] = {direction = 0, brows = {{x = 5, y = 2, file = "Brows20Left"}, {x = 9, y = 1, file = "Brows20Right"}}},
		["Rotom-2"] = {direction = 0, brows = {{x = 3, y = 0, file = "Brows20LeftFlat"}, {x = 8, y = -3, file = "Brows20Right"}}},
		["Rotom-3"] = {direction = 0, brows = {{x = 7, y = 0, file = "Brows20Left"}, {x = 9, y = 0, file = "Brows20Right"}}},
		["Rotom-4"] = {direction = 0, brows = {{x = 5, y = 7, file = "Brows20"}}},
		["Rotom-5"] = {direction = 0, brows = {{x = 6, y = 2, file = "Brows20Left"}, {x = 9, y = 6, file = "Brows20RightFlat"}}},
		["Sawsbuck-1"] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		["Sawsbuck-2"] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		["Sawsbuck-3"] = {direction = 0, brows = {{x = -3, y = 5, file = "Brows25Right"}}},
		["Shaymin L-1"] = {direction = 0, brows = {{x = 2, y = 4, file = "Brows20Right"}}},
		["Shellos W-1"] = {direction = 0, brows = {{x = -4, y = 6, file = "Brows20Right"}}},
		["Thundurus-1"] = {direction = 0, brows = {{x = 1, y = 2, file = "Brows20Right"}}},
		["Tornadus-1"] = {direction = 0, brows = {{x = -6, y = 6, file = "Brows20Right"}}},
		["Unfezant M-1"] = {direction = 0, brows = {{x = 3, y = 3, file = "Brows25RightTall"}}},
		["Wormadam P-1"] = {direction = 0, brows = {{x = 13, y = 2, file = "Brows15Left"}, {x = 12, y = 3, file = "Brows15Right"}}},
		["Wormadam P-2"] = {direction = 0, brows = {{x = 12, y = 3, file = "Brows15Left"}, {x = 12, y = 3, file = "Brows15Right"}}}
	}

	local function perPokemonBrows()
		local defaultReturn = {direction = 0, brows = {x = 0, y = 0, file = ""}}
		if currentPokemon == nil then
			return defaultReturn
		end
		local imageID = currentPokemon.pokemonID
		if currentPokemon.baseFormData ~= nil then
			imageID = currentPokemon.baseFormData.baseFormName .. "-" .. currentPokemon.baseFormData.alternateFormIndex
		end
		if browsOptions[imageID] ~= nil then
			return browsOptions[imageID]
		else
			return defaultReturn
		end
	end

	local function updateBrows(skipRedraw)
		if not browsVisible or currentPokemon == nil then
			return
		end
		browsUp = not browsUp
		local browsData = perPokemonBrows()
		local offsetAdjust = browsData.brows
		local direction = browsData.direction
		local numControls = #browsControls
		local prefix = "brows"
		for i = 1, numControls, 1 do
			frameUIPath.removeControl(browsControls[i])
			browsControls[i] = nil
		end
		for i = 1, numControls, 1 do
			local controlID = prefix .. i
			local offset = {x = 0, y = 0}
			if currentScreen == program.UI_SCREENS.MAIN_SCREEN then
				offset.y = offset.y - 56 - ((i - 1) * 30)
			elseif currentScreen == program.UI_SCREENS.LOG_VIEWER_SCREEN then
				offset.y = offset.y - 2
				offset.x = offset.x - 105 - ((i - 1) * 33)
			end
			if browsUp then
				if direction == 0 then
					offset.y = offset.y - 3
				elseif direction == 1 then
					offset.x = offset.x + 2
					offset.y = offset.y - 2
				elseif direction == 2 then
					offset.x = offset.x - 2
					offset.y = offset.y - 2
				elseif direction == 3 then
					offset.x = offset.x - 3
				end
			end
			local filepath = ""
			if offsetAdjust[i] ~= nil then
				offset.x = offset.x + offsetAdjust[i].x
				offset.y = offset.y + offsetAdjust[i].y
				filepath = Paths.FOLDERS.BROWS_IMAGES_FOLDER .. "/" .. offsetAdjust[i].file .. fileEnding
			end
			ui.controls[controlID] =
				ImageLabel(
				Component(frameUIPath, Box({x = 0, y = 0}, {width = 30, height = 30}, nil, nil, nil, nil, nil, 2)),
				ImageField(filepath, offset, nil),
				browsVisible
			)
			browsControls[i] = ui.controls[controlID]
		end
		if skipRedraw == false then
			return
		end
		program.drawCurrentScreens()
	end

	function self.initialize()
		currentScreen = screen
		if currentScreen == program.UI_SCREENS.MAIN_SCREEN then
			frameUIPath = ui.frames.pokemonImageTypeFrame
		elseif currentScreen == program.UI_SCREENS.LOG_VIEWER_SCREEN then
			frameUIPath = ui.frames.navNameFrame
		end
		if tonumber(settings.extras.BROWS_FRAMES) then
			defaultFrames = tonumber(settings.extras.BROWS_FRAMES)
		end
		frameCounters["browCounter"] = FrameCounter(defaultFrames, updateBrows, nil, true)
		if frameUIPath ~= nil then
			local prefix = "brows"
			for i = 1, maxBrows, 1 do
				ui.controls[prefix .. i] =
					ImageLabel(
					Component(frameUIPath, Box({x = 0, y = 0}, {width = 30, height = 30}, nil, nil)),
					ImageField("", {x = 0, y = 0}, nil),
					browsVisible
				)
				browsControls[i] = ui.controls[prefix .. i]
			end
		end
	end

	function self.setCurrentPokemon(pokemon)
		needReset = currentPokemon == nil or pokemon == nil or currentPokemon.pokemonID ~= pokemon.pokemonID
		currentPokemon = pokemon
	end

	function self.show()
		local currentIconSet = IconSets.SETS[settings.appearance.ICON_SET_INDEX]
		if currentScreen == program.UI_SCREENS.LOG_VIEWER_SCREEN then
		--figure something out here if display doesn't quite work
		end
		browsVisible = settings.extras.BROWS_ENABLED and currentIconSet and currentIconSet.NAME == "Stadium"
		for i = 1, #browsControls, 1 do
			browsControls[i].setVisibility(browsVisible)
		end
		if browsVisible and needReset then
			browsUp = not browsUp
			updateBrows(false)
			needReset = false
		end
	end

	return self
end
return BrowsManager
