LocationData = {}

LocationData.LOCATION_DATA = {
    --d/p/platinum
    [0x45555043] = {
        locations = {
            [0] = {name = "Mystery Zone"},
            [1] = {name = "Mystery Zone"},
            [2] = {name = "Mystery Zone"},
            [3] = {name = "Jubilife City"},
            [4] = {name = "Jubilife City"},
            [5] = {name = "Jubilife City's gym"},
            [6] = {name = "Jubilife City"},
            [7] = {name = "Jubilife City"},
            [8] = {name = "Pok" .. Chars.accentedE .. "tch Co."},
            [9] = {name = "Pok" .. Chars.accentedE .. "tch Co."},
            [10] = {name = "Pok" .. Chars.accentedE .. "tch Co."},
            [11] = {name = "Jubilife TV"},
            [12] = {name = "Jubilife TV"},
            [13] = {name = "Jubilife TV"},
            [14] = {name = "Jubilife TV"},
            [15] = {name = "Jubilife TV"},
            [16] = {name = "Jubilife TV"},
            [17] = {name = "Jubilife TV"},
            [18] = {name = "Jubilife TV"},
            [19] = {name = "Jubilife City"},
            [20] = {name = "Jubilife City"},
            [21] = {name = "Jubilife City"},
            [22] = {name = "Jubilife City"},
            [23] = {name = "Jubilife City"},
            [24] = {name = "Jubilife City"},
            [25] = {name = "Jubilife City"},
            [26] = {name = "Jubilife City"},
            [27] = {name = "Jubilife City"},
            [28] = {name = "Global Terminal"},
            [29] = {name = "Trainers' School"},
            [30] = {name = "Jubilife City"},
            [31] = {name = "Jubilife City"},
            [32] = {name = "Jubilife City"},
            [33] = {name = "Canalave City"},
            [34] = {name = "Canalave City"},
            [35] = {name = "Canalave City's gym"},
            [36] = {name = "Canalave City"},
            [37] = {name = "Canalave City"},
            [38] = {name = "Canalave Library"},
            [39] = {name = "Canalave Library"},
            [40] = {name = "Canalave Library"},
            [41] = {name = "Canalave City"},
            [42] = {name = "Canalave City"},
            [43] = {name = "Canalave City"},
            [44] = {name = "Canalave City"},
            [45] = {name = "Oreburgh City"},
            [46] = {name = "Oreburgh City"},
            [47] = {name = "Oreburgh City's gym"},
            [48] = {name = "Oreburgh City"},
            [49] = {name = "Oreburgh City"},
            [50] = {name = "Oreburgh City"},
            [51] = {name = "Oreburgh City"},
            [52] = {name = "Oreburgh City"},
            [53] = {name = "Oreburgh City"},
            [54] = {name = "Oreburgh City"},
            [55] = {name = "Oreburgh City"},
            [56] = {name = "Oreburgh City"},
            [57] = {name = "Oreburgh City"},
            [58] = {name = "Oreburgh City"},
            [59] = {name = "Mining Museum"},
            [60] = {name = "Oreburgh City"},
            [61] = {name = "Oreburgh City"},
            [62] = {name = "Oreburgh City"},
            [63] = {name = "Oreburgh City"},
            [64] = {name = "Oreburgh City"},
            [65] = {name = "Eterna City"},
            [66] = {name = "Eterna City"},
            [67] = {name = "Eterna City's gym"},
            [68] = {name = "Eterna City's gym"},
            [69] = {name = "Eterna City"},
            [70] = {name = "Eterna City"},
            [71] = {name = "Cycle Shop"},
            [72] = {name = "T.G. Eterna Bldg"},
            [73] = {name = "T.G. Eterna Bldg"},
            [74] = {name = "T.G. Eterna Bldg"},
            [75] = {name = "T.G. Eterna Bldg"},
            [76] = {name = "Eterna City"},
            [77] = {name = "Eterna City"},
            [78] = {name = "Eterna City"},
            [79] = {name = "Eterna City"},
            [80] = {name = "Route 206"},
            [81] = {name = "Eterna City"},
            [82] = {name = "Eterna City"},
            [83] = {name = "Eterna City"},
            [84] = {name = "Eterna City"},
            [85] = {name = "Eterna City"},
            [86] = {name = "Hearthome City"},
            [87] = {name = "Hearthome City"},
            [88] = {name = "Hearthome City's gym"},
            [89] = {name = "Hearthome City's gym"},
            [90] = {name = "Hearthome City's gym"},
            [91] = {name = "Hearthome City's gym"},
            [92] = {name = "Hearthome City's gym"},
            [93] = {name = "Hearthome City's gym"},
            [94] = {name = "Hearthome City's gym"},
            [95] = {name = "Hearthome City's gym"},
            [96] = {name = "Hearthome City's gym"},
            [97] = {name = "Hearthome City's gym"},
            [98] = {name = "Hearthome City's gym"},
            [99] = {name = "Hearthome City's gym"},
            [100] = {name = "Hearthome City's gym"},
            [101] = {name = "Hearthome City"},
            [102] = {name = "Hearthome City"},
            [103] = {name = "Hearthome City"},
            [104] = {name = "Hearthome City"},
            [105] = {name = "Hearthome City"},
            [106] = {name = "Hearthome City"},
            [107] = {name = "Hearthome City"},
            [108] = {name = "Hearthome City"},
            [109] = {name = "Route 208"},
            [110] = {name = "Route 209"},
            [111] = {name = "Route 212"},
            [112] = {name = "Hearthome City"},
            [113] = {name = "Hearthome City"},
            [114] = {name = "Hearthome City"},
            [115] = {name = "Hearthome City"},
            [116] = {name = "Poffin House"},
            [117] = {name = "Contest Hall"},
            [118] = {name = "Contest Hall"},
            [119] = {name = "Foreign Building"},
            [120] = {name = "Pastoria City"},
            [121] = {name = "Pastoria City"},
            [122] = {name = "Pastoria City's gym"},
            [123] = {name = "Pastoria City"},
            [124] = {name = "Pastoria City"},
            [125] = {name = "Pastoria City"},
            [126] = {name = "Pastoria City"},
            [127] = {name = "Pastoria City"},
            [128] = {name = "Pastoria City"},
            [129] = {name = "Pastoria City"},
            [130] = {name = "Pastoria City"},
            [131] = {name = "Pastoria City"},
            [132] = {name = "Veilstone City"},
            [133] = {name = "Veilstone City's gym"},
            [134] = {name = "Veilstone City"},
            [135] = {name = "Veilstone City"},
            [136] = {name = "Game Corner"},
            [137] = {name = "Veilstone Store"},
            [138] = {name = "Veilstone Store"},
            [139] = {name = "Veilstone Store"},
            [140] = {name = "Veilstone Store"},
            [141] = {name = "Veilstone Store"},
            [142] = {name = "Veilstone Store"},
            [143] = {name = "Veilstone City"},
            [144] = {name = "Veilstone City"},
            [145] = {name = "Veilstone City"},
            [146] = {name = "Veilstone City"},
            [147] = {name = "Veilstone City"},
            [148] = {name = "Veilstone City"},
            [149] = {name = "Route 215"},
            [150] = {name = "Sunyshore City"},
            [151] = {name = "Sunyshore City"},
            [152] = {name = "Sunyshore City"},
            [153] = {name = "Sunyshore City"},
            [154] = {name = "Sunyshore City's gym"},
            [155] = {name = "Sunyshore City's gym"},
            [156] = {name = "Sunyshore City's gym"},
            [157] = {name = "Sunyshore Market"},
            [158] = {name = "Sunyshore City"},
            [159] = {name = "Sunyshore City"},
            [160] = {name = "Sunyshore City"},
            [161] = {name = "Sunyshore City"},
            [162] = {name = "Sunyshore City"},
            [163] = {name = "Sunyshore City"},
            [164] = {name = "Vista Lighthouse"},
            [165] = {name = "Snowpoint City"},
            [166] = {name = "Snowpoint City"},
            [167] = {name = "Snowpoint City's gym"},
            [168] = {name = "Snowpoint City"},
            [169] = {name = "Snowpoint City"},
            [170] = {name = "Snowpoint City"},
            [171] = {name = "Snowpoint City"},
            [172] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [173] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [174] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [175] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [176] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [177] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [178] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [179] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [180] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [181] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [182] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [183] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [184] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [185] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [186] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [187] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [188] = {name = "Fight Area"},
            [189] = {name = "Fight Area"},
            [190] = {name = "Fight Area"},
            [191] = {name = "Fight Area"},
            [192] = {name = "Battle Park"},
            [193] = {name = "Route 225"},
            [194] = {name = "Fight Area"},
            [195] = {name = "Fight Area"},
            [196] = {name = "Mystery Zone"},
            [197] = {name = "Oreburgh Mine"},
            [198] = {name = "Oreburgh Mine"},
            [199] = {name = "Oreburgh Mine"},
            [200] = {name = "Valley Windworks"},
            [201] = {name = "Valley Windworks"},
            [202] = {name = "Eterna Forest"},
            [203] = {name = "Eterna Forest"},
            [204] = {name = "Fuego Ironworks"},
            [205] = {name = "Fuego Ironworks"},
            [206] = {name = "Mystery Zone"},
            [207] = {name = "Mt. Coronet"},
            [208] = {name = "Mt. Coronet"},
            [209] = {name = "Mt. Coronet"},
            [210] = {name = "Mt. Coronet"},
            [211] = {name = "Mt. Coronet"},
            [212] = {name = "Mt. Coronet"},
            [213] = {name = "Mt. Coronet"},
            [214] = {name = "Mt. Coronet"},
            [215] = {name = "Mt. Coronet"},
            [216] = {name = "Mt. Coronet"},
            [217] = {name = "Mt. Coronet"},
            [218] = {name = "Mt. Coronet"},
            [219] = {name = "Mt. Coronet"},
            [220] = {name = "Spear Pillar"},
            [221] = {name = "Spear Pillar"},
            [222] = {name = "Mystery Zone"},
            [223] = {name = "Pastoria City"},
            [224] = {name = "Mystery Zone"},
            [225] = {name = "Solaceon Ruins"},
            [226] = {name = "Solaceon Ruins"},
            [227] = {name = "Solaceon Ruins"},
            [228] = {name = "Solaceon Ruins"},
            [229] = {name = "Solaceon Ruins"},
            [230] = {name = "Solaceon Ruins"},
            [231] = {name = "Solaceon Ruins"},
            [232] = {name = "Solaceon Ruins"},
            [233] = {name = "Solaceon Ruins"},
            [234] = {name = "Solaceon Ruins"},
            [235] = {name = "Solaceon Ruins"},
            [236] = {name = "Solaceon Ruins"},
            [237] = {name = "Solaceon Ruins"},
            [238] = {name = "Solaceon Ruins"},
            [239] = {name = "Solaceon Ruins"},
            [240] = {name = "Solaceon Ruins"},
            [241] = {name = "Solaceon Ruins"},
            [242] = {name = "Solaceon Ruins"},
            [243] = {name = "Mystery Zone"},
            [244] = {name = "Victory Road"},
            [245] = {name = "Victory Road"},
            [246] = {name = "Victory Road"},
            [247] = {name = "Victory Road"},
            [248] = {name = "Victory Road"},
            [249] = {name = "Victory Road"},
            [250] = {name = "Mystery Zone"},
            [251] = {name = "Pal Park"},
            [252] = {name = "Mystery Zone"},
            [253] = {name = "Amity Square"},
            [254] = {name = "Ravaged Path"},
            [255] = {name = "Mystery Zone"},
            [256] = {name = "Floaroma Meadow"},
            [257] = {name = "Floaroma Meadow"},
            [258] = {name = "Oreburgh Gate"},
            [259] = {name = "Oreburgh Gate"},
            [260] = {name = "Fullmoon Island"},
            [261] = {name = "Fullmoon Island"},
            [262] = {name = "Stark Mountain"},
            [263] = {name = "Stark Mountain"},
            [264] = {name = "Stark Mountain"},
            [265] = {name = "Stark Mountain"},
            [266] = {name = "Mystery Zone"},
            [267] = {name = "Sendoff Spring"},
            [268] = {name = "Turnback Cave"},
            [269] = {name = "Turnback Cave"},
            [270] = {name = "Turnback Cave"},
            [271] = {name = "Turnback Cave"},
            [272] = {name = "Turnback Cave"},
            [273] = {name = "Turnback Cave"},
            [274] = {name = "Flower Paradise"},
            [275] = {name = "Mystery Zone"},
            [276] = {name = "Mystery Zone"},
            [277] = {name = "Mystery Zone"},
            [278] = {name = "Snowpoint Temple"},
            [279] = {name = "Snowpoint Temple"},
            [280] = {name = "Snowpoint Temple"},
            [281] = {name = "Snowpoint Temple"},
            [282] = {name = "Snowpoint Temple"},
            [283] = {name = "Snowpoint Temple"},
            [284] = {name = "Wayward Cave"},
            [285] = {name = "Wayward Cave"},
            [286] = {name = "Ruin Maniac Cave"},
            [287] = {name = "Trophy Garden"},
            [288] = {name = "Iron Island"},
            [289] = {name = "Iron Island"},
            [290] = {name = "Iron Island"},
            [291] = {name = "Iron Island"},
            [292] = {name = "Iron Island"},
            [293] = {name = "Iron Island"},
            [294] = {name = "Iron Island"},
            [295] = {name = "Old Chateau"},
            [296] = {name = "Old Chateau"},
            [297] = {name = "Old Chateau"},
            [298] = {name = "Old Chateau"},
            [299] = {name = "Old Chateau"},
            [300] = {name = "Old Chateau"},
            [301] = {name = "Old Chateau"},
            [302] = {name = "Old Chateau"},
            [303] = {name = "Old Chateau"},
            [304] = {name = "Mystery Zone"},
            [305] = {name = "Galactic HQ"},
            [306] = {name = "Galactic HQ"},
            [307] = {name = "Galactic HQ"},
            [308] = {name = "Galactic HQ"},
            [309] = {name = "Galactic HQ"},
            [310] = {name = "Galactic HQ"},
            [311] = {name = "Lake Verity"},
            [312] = {name = "Lake Verity"},
            [313] = {name = "Verity Cavern"},
            [314] = {name = "Lake Valor"},
            [315] = {name = "Lake Valor"},
            [316] = {name = "Verity Cavern"},
            [317] = {name = "Lake Acuity"},
            [318] = {name = "Lake Acuity"},
            [319] = {name = "Acuity Cavern"},
            [320] = {name = "Newmoon Island"},
            [321] = {name = "Newmoon Island"},
            [322] = {name = "Battle Park"},
            [323] = {name = "Battle Park"},
            [324] = {name = "Mystery Zone"},
            [325] = {name = "Mystery Zone"},
            [326] = {name = "Battle Tower"},
            [327] = {name = "Battle Tower"},
            [328] = {name = "Battle Tower"},
            [329] = {name = "Battle Tower"},
            [330] = {name = "Battle Tower"},
            [331] = {name = "Battle Tower"},
            [332] = {name = "Mystery Zone"},
            [333] = {name = "Mystery Zone"},
            [334] = {name = "Verity Lakefront"},
            [335] = {name = "Verity Lakefront"},
            [336] = {name = "Verity Lakefront"},
            [337] = {name = "Restaurant"},
            [338] = {name = "Grand Lake"},
            [339] = {name = "Grand Lake"},
            [340] = {name = "Acuity Lakefront"},
            [341] = {name = "Spring Path"},
            [342] = {name = "Route 201"},
            [343] = {name = "Route 202"},
            [344] = {name = "Route 203"},
            [345] = {name = "Route 204"},
            [346] = {name = "Route 204"},
            [347] = {name = "Route 205"},
            [348] = {name = "Route 205"},
            [349] = {name = "Route 205"},
            [350] = {name = "Route 206"},
            [351] = {name = "Route 206"},
            [352] = {name = "Mystery Zone"},
            [353] = {name = "Route 207"},
            [354] = {name = "Route 208"},
            [355] = {name = "Route 208"},
            [356] = {name = "Route 209"},
            [357] = {name = "Route 209"},
            [358] = {name = "Route 209"},
            [359] = {name = "Route 209"},
            [360] = {name = "Route 209"},
            [361] = {name = "Route 209"},
            [362] = {name = "Route 210"},
            [363] = {name = "Route 210"},
            [364] = {name = "Route 210"},
            [365] = {name = "Route 211"},
            [366] = {name = "Route 211"},
            [367] = {name = "Route 212"},
            [368] = {name = "Pok" .. Chars.accentedE .. "mon Mansion"},
            [369] = {name = "Pok" .. Chars.accentedE .. "mon Mansion"},
            [370] = {name = "Pok" .. Chars.accentedE .. "mon Mansion"},
            [371] = {name = "Route 212"},
            [372] = {name = "Route 212"},
            [373] = {name = "Route 213"},
            [374] = {name = "Route 213"},
            [375] = {name = "Footstep House"},
            [376] = {name = "Grand Lake"},
            [377] = {name = "Grand Lake"},
            [378] = {name = "Grand Lake"},
            [379] = {name = "Grand Lake"},
            [380] = {name = "Route 214"},
            [381] = {name = "Route 214"},
            [382] = {name = "Route 215"},
            [383] = {name = "Route 216"},
            [384] = {name = "Route 216"},
            [385] = {name = "Route 217"},
            [386] = {name = "Route 217"},
            [387] = {name = "Route 217"},
            [388] = {name = "Route 218"},
            [389] = {name = "Route 218"},
            [390] = {name = "Route 218"},
            [391] = {name = "Route 219"},
            [392] = {name = "Route 221"},
            [393] = {name = "Pal Park"},
            [394] = {name = "Route 221"},
            [395] = {name = "Route 222"},
            [396] = {name = "Route 222"},
            [397] = {name = "Route 222"},
            [398] = {name = "Route 222"},
            [399] = {name = "Route 224"},
            [400] = {name = "Route 225"},
            [401] = {name = "Mystery Zone"},
            [402] = {name = "Mystery Zone"},
            [403] = {name = "Route 227"},
            [404] = {name = "Mystery Zone"},
            [405] = {name = "Mystery Zone"},
            [406] = {name = "Route 228"},
            [407] = {name = "Route 229"},
            [408] = {name = "Mystery Zone"},
            [409] = {name = "Mystery Zone"},
            [410] = {name = "Mystery Zone"},
            [411] = {name = "Twinleaf Town"},
            [412] = {name = "Twinleaf Town"},
            [413] = {name = "Twinleaf Town"},
            [414] = {name = "Twinleaf Town"},
            [415] = {name = "Twinleaf Town"},
            [416] = {name = "Twinleaf Town"},
            [417] = {name = "Twinleaf Town"},
            [418] = {name = "Sandgem Town"},
            [419] = {name = "Sandgem Town"},
            [420] = {name = "Sandgem Town"},
            [421] = {name = "Sandgem Town"},
            [422] = {name = "Sandgem Town"},
            [423] = {name = "Sandgem Town"},
            [424] = {name = "Sandgem Town"},
            [425] = {name = "Sandgem Town"},
            [426] = {name = "Floaroma Town"},
            [427] = {name = "Floaroma Town"},
            [428] = {name = "Floaroma Town"},
            [429] = {name = "Floaroma Town"},
            [430] = {name = "Flower Shop"},
            [431] = {name = "Floaroma Town"},
            [432] = {name = "Floaroma Town"},
            [433] = {name = "Solaceon Town"},
            [434] = {name = "Solaceon Town"},
            [435] = {name = "Solaceon Town"},
            [436] = {name = "Solaceon Town"},
            [437] = {name = "Pok" .. Chars.accentedE .. "mon Day Care"},
            [438] = {name = "Solaceon Town"},
            [439] = {name = "Solaceon Town"},
            [440] = {name = "Solaceon Town"},
            [441] = {name = "Solaceon Town"},
            [442] = {name = "Celestic Town"},
            [443] = {name = "Celestic Town"},
            [444] = {name = "Celestic Town"},
            [445] = {name = "Celestic Town"},
            [446] = {name = "Celestic Town"},
            [447] = {name = "Celestic Town"},
            [448] = {name = "Celestic Town"},
            [449] = {name = "Celestic Town"},
            [450] = {name = "Survival Area"},
            [451] = {name = "Survival Area"},
            [452] = {name = "Survival Area"},
            [453] = {name = "Survival Area"},
            [454] = {name = "Battleground"},
            [455] = {name = "Survival Area"},
            [456] = {name = "Survival Area"},
            [457] = {name = "Resort Area"},
            [458] = {name = "Resort Area"},
            [459] = {name = "Resort Area"},
            [460] = {name = "Resort Area"},
            [461] = {name = "Resort Area"},
            [462] = {name = "Resort Area"},
            [463] = {name = "Resort Area"},
            [464] = {name = "Villa"},
            [465] = {name = "Resort Area"},
            [466] = {name = "Mystery Zone"},
            [467] = {name = "Route 220"},
            [468] = {name = "Route 223"},
            [469] = {name = "Route 226"},
            [470] = {name = "Mystery Zone"},
            [471] = {name = "Route 230"},
            [472] = {name = "Seabreak Path"},
            [473] = {name = "Mystery Zone"},
            [474] = {name = "Jubilife City"},
            [475] = {name = "Canalave City"},
            [476] = {name = "Oreburgh City"},
            [477] = {name = "Eterna City"},
            [478] = {name = "Hearthome City"},
            [479] = {name = "Pastoria City"},
            [480] = {name = "Veilstone City"},
            [481] = {name = "Sunyshore City"},
            [482] = {name = "Snowpoint City"},
            [483] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [484] = {name = "Fight Area"},
            [485] = {name = "Sandgem Town"},
            [486] = {name = "Floaroma Town"},
            [487] = {name = "Solaceon Town"},
            [488] = {name = "Celestic Town"},
            [489] = {name = "Survival Area"},
            [490] = {name = "Resort Area"},
            [491] = {name = "Canalave City"},
            [492] = {name = "Caf" .. Chars.accentedE},
            [493] = {name = "Battle Tower"},
            [494] = {name = "Galactic HQ"},
            [495] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [496] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [497] = {name = "Galactic HQ"},
            [498] = {name = "Route 225"},
            [499] = {name = "Route 226"},
            [500] = {name = "Route 227"},
            [501] = {name = "Route 228"},
            [502] = {name = "Route 228"},
            [503] = {name = "Route 228"},
            [504] = {name = "Great Marsh"},
            [505] = {name = "Great Marsh"},
            [506] = {name = "Great Marsh"},
            [507] = {name = "Great Marsh"},
            [508] = {name = "Great Marsh"},
            [509] = {name = "Great Marsh"},
            [510] = {name = "Hall of Origin"},
            [511] = {name = "Hall of Origin"},
            [512] = {name = "Ruin Maniac Cave"},
            [513] = {name = "Maniac Tunnel"},
            [514] = {name = "Iron Island"},
            [515] = {name = "Solaceon Ruins"},
            [516] = {name = "Vista Lighthouse"},
            [517] = {name = "Jubilife City"},
            [518] = {name = "Turnback Cave"},
            [519] = {name = "Turnback Cave"},
            [520] = {name = "Turnback Cave"},
            [521] = {name = "Turnback Cave"},
            [522] = {name = "Turnback Cave"},
            [523] = {name = "Turnback Cave"},
            [524] = {name = "Turnback Cave"},
            [525] = {name = "Turnback Cave"},
            [526] = {name = "Turnback Cave"},
            [527] = {name = "Turnback Cave"},
            [528] = {name = "Turnback Cave"},
            [529] = {name = "Turnback Cave"},
            [530] = {name = "Turnback Cave"},
            [531] = {name = "Turnback Cave"},
            [532] = {name = "Turnback Cave"},
            [533] = {name = "Turnback Cave"},
            [534] = {name = "Turnback Cave"},
            [535] = {name = "Turnback Cave"},
            [536] = {name = "Turnback Cave"},
            [537] = {name = "Turnback Cave"},
            [538] = {name = "Turnback Cave"},
            [539] = {name = "Turnback Cave"},
            [540] = {name = "Turnback Cave"},
            [541] = {name = "Turnback Cave"},
            [542] = {name = "Turnback Cave"},
            [543] = {name = "Turnback Cave"},
            [544] = {name = "Turnback Cave"},
            [545] = {name = "Turnback Cave"},
            [546] = {name = "Turnback Cave"},
            [547] = {name = "Turnback Cave"},
            [548] = {name = "Turnback Cave"},
            [549] = {name = "Turnback Cave"},
            [550] = {name = "Turnback Cave"},
            [551] = {name = "Turnback Cave"},
            [552] = {name = "Turnback Cave"},
            [553] = {name = "Turnback Cave"},
            [554] = {name = "Turnback Cave"},
            [555] = {name = "Turnback Cave"},
            [556] = {name = "Turnback Cave"},
            [557] = {name = "Turnback Cave"},
            [558] = {name = "Contest Hall"},
            [559] = {name = "Battle Frontier"},
            [560] = {name = "Battle Frontier"},
            [561] = {name = "Battle Tower"},
            [562] = {name = "Battle Factory"},
            [563] = {name = "Battle Hall"},
            [564] = {name = "Battle Castle"},
            [565] = {name = "Battle Arcade"},
            [566] = {name = "Veilstone Store"},
            [567] = {name = "Global Terminal"},
            [568] = {name = "Global Terminal"},
            [569] = {name = "Galactic HQ"},
            [570] = {name = "Distortion World"},
            [571] = {name = "Rotom's Room"},
            [572] = {name = "T.G. Eterna Bldg"},
            [573] = {name = "Distortion World"},
            [574] = {name = "Distortion World"},
            [575] = {name = "Distortion World"},
            [576] = {name = "Distortion World"},
            [577] = {name = "Distortion World"},
            [578] = {name = "Distortion World"},
            [579] = {name = "Distortion World"},
            [580] = {name = "Distortion World"},
            [581] = {name = "Distortion World"},
            [582] = {name = "Distortion World"},
            [583] = {name = "Distortion World"},
            [584] = {name = "Spear Pillar"},
            [585] = {name = "Spear Pillar"},
            [586] = {name = "Jubilife City"},
            [587] = {name = "Iron Island"},
            [588] = {name = "Iron Ruins"},
            [589] = {name = "Mt. Coronet"},
            [590] = {name = "Iceberg Ruins"},
            [591] = {name = "Route 228"},
            [592] = {name = "Rpck Peak Ruins"}
        },
        encounters = {
            ["Route 202"] = {
                totalPokemon = 4,
                vanillaData = {
                    {
                        {level = 3, percent = 5},
                        {level = 5, percent = 30},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 3, percent = 5},
                        {level = 6, percent = 15}
                    },
                    {
                        {level = 5, percent = 10}
                    },
                    {
                        {level = 5, percent = 20},
                        {level = 6, percent = 10}
                    }
                }
            },
            ["Route 201"] = {
                totalPokemon = 3,
                vanillaData = {
                    {
                        {level = 3, percent = 25},
                        {level = 5, percent = 25}
                    },
                    {
                        {level = 3, percent = 25},
                        {level = 5, percent = 15}
                    },
                    {
                        {level = 5, percent = 10}
                    }
                }
            },
            ["Lake Verity"] = {
                totalPokemon = 2,
                vanillaData = {
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 20},
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 20},
                        {level = 6, percent = 10}
                    }
                }
            },
            ["Route 203"] = {
                totalPokemon = 5,
                vanillaData = {
                    {
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 6, percent = 20},
                        {level = 8, percent = 5}
                    },
                    {
                        {level = 6, percent = 10},
                        {level = 8, percent = 5}
                    },
                    {
                        {level = 6, percent = 20},
                        {level = 8, percent = 10},
                        {level = 9, percent = 4},
                        {level = 11, percent = 1}
                    },
                    {
                        {level = 8, percent = 10},
                        {level = 9, percent = 4},
                        {level = 11, percent = 1}
                    }
                }
            },
            ["Route 204"] = {
                totalPokemon = 6,
                vanillaData = {
                    {
                        {level = 5, percent = 10}
                    },
                    {
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 6, percent = 10},
                        {level = 8, percent = 5}
                    },
                    {
                        {level = 6, percent = 10},
                        {level = 8, percent = 5}
                    },
                    {
                        {level = 6, percent = 20},
                        {level = 8, percent = 4},
                        {level = 9, percent = 1}
                    },
                    {
                        {level = 6, percent = 20},
                        {level = 8, percent = 4},
                        {level = 9, percent = 1}
                    }
                }
            }
        },
        encounterAreaOrder = {
            "Lake Verity",
            "Route 201",
            "Route 202",
            "Route 203",
            "Route 204",
            "Twinleaf Town",
            "Route 218",
            "Route 219"
        }
    },
    --heartgold/soulsilver
    [0x454B5049] = {
        locations = {
            [0] = {name = "Mystery Zone"},
            [1] = {name = "Mystery Zone"},
            [2] = {name = "Mystery Zone"},
            [3] = {name = "Mystery Zone"},
            [4] = {name = "Mystery Zone"},
            [5] = {name = "Mystery Zone"},
            [6] = {name = "Bellchime Trail"},
            [7] = {name = "Burned Tower"},
            [8] = {name = "Ruins of Alph"},
            [9] = {name = "Route 1"},
            [10] = {name = "Route 2"},
            [11] = {name = "Route 3"},
            [12] = {name = "Route 4"},
            [13] = {name = "Route 5"},
            [14] = {name = "Route 6"},
            [15] = {name = "Route 7"},
            [16] = {name = "Route 8"},
            [17] = {name = "Route 9"},
            [18] = {name = "Route 10"},
            [19] = {name = "Route 11"},
            [20] = {name = "Route 12"},
            [21] = {name = "Route 13"},
            [22] = {name = "Route 14"},
            [23] = {name = "Route 15"},
            [24] = {name = "Route 16"},
            [25] = {name = "Route 17"},
            [26] = {name = "Route 18"},
            [27] = {name = "Route 22"},
            [28] = {name = "Route 24"},
            [29] = {name = "Route 25"},
            [30] = {name = "Route 26"},
            [31] = {name = "Route 27"},
            [32] = {name = "Route 28"},
            [33] = {name = "Route 29"},
            [34] = {name = "Route 30"},
            [35] = {name = "Route 31"},
            [36] = {name = "Route 32"},
            [37] = {name = "Route 33"},
            [38] = {name = "Route 34"},
            [39] = {name = "Route 35"},
            [40] = {name = "Route 36"},
            [41] = {name = "Route 37"},
            [42] = {name = "Route 38"},
            [43] = {name = "Route 39"},
            [44] = {name = "Route 42"},
            [45] = {name = "Route 43"},
            [46] = {name = "Route 44"},
            [47] = {name = "Route 45"},
            [48] = {name = "Route 46"},
            [49] = {name = "Pallet Town"},
            [50] = {name = "Viridian City"},
            [51] = {name = "Pewter City"},
            [52] = {name = "Cerulean City"},
            [53] = {name = "Lavender Town"},
            [54] = {name = "Vermilion City"},
            [55] = {name = "Celadon City"},
            [56] = {name = "Fuchsia City"},
            [57] = {name = "Cinnarbar Island"},
            [58] = {name = "Indigo Plateau"},
            [59] = {name = "Saffron City"},
            [60] = {name = "New Bark Town"},
            [61] = {name = "Lab"},
            [62] = {name = "New Bark Town"},
            [63] = {name = "New Bark Town"},
            [64] = {name = "New Bark Town"},
            [65] = {name = "New Bark Town"},
            [66] = {name = "New Bark Town"},
            [67] = {name = "Cherrygrove City"},
            [68] = {name = "Cherrygrove City"},
            [69] = {name = "Cherrygrove City"},
            [70] = {name = "Cherrygrove City"},
            [71] = {name = "Cherrygrove City"},
            [72] = {name = "Cherrygrove City"},
            [73] = {name = "Violet City"},
            [74] = {name = "Azalea Town"},
            [75] = {name = "Cianwood City"},
            [76] = {name = "Goldenrod City"},
            [77] = {name = "Olivine City"},
            [78] = {name = "Ecruteak City"},
            [79] = {name = "Ecruteak City"},
            [80] = {name = "Ecruteak City's gym"},
            [81] = {name = "Ecruteak City"},
            [82] = {name = "Jubilife City"},
            [83] = {name = "Ecruteak City"},
            [84] = {name = "Ecruteak City"},
            [85] = {name = "Ecruteak City"},
            [86] = {name = "Ecruteak City"},
            [87] = {name = "Mahogany Town"},
            [88] = {name = "Lake of Rage"},
            [89] = {name = "Blackthorn City"},
            [90] = {name = "Mt. Silver"},
            [91] = {name = "Route 19"},
            [92] = {name = "Route 20"},
            [93] = {name = "Route 21"},
            [94] = {name = "Route 40"},
            [95] = {name = "Route 41"},
            [96] = {name = "National Park"},
            [97] = {name = "Route 31"},
            [98] = {name = "Route 32"},
            [99] = {name = "Union Cave"},
            [100] = {name = "Azalea Town"},
            [101] = {name = "Route 35"},
            [102] = {name = "Route 35"},
            [103] = {name = "Route 36"},
            [104] = {name = "Route 36"},
            [105] = {name = "Jubilife City"},
            [106] = {name = "Diglett Cave"},
            [107] = {name = "Mt. Moon"},
            [108] = {name = "Rock Tunnel"},
            [109] = {name = "Pal Park"},
            [110] = {name = "Sprout Tower"},
            [111] = {name = "Bell Tower"},
            [112] = {name = "Radio Tower"},
            [113] = {name = "Ruins of Alph"},
            [114] = {name = "Slowpoke Well"},
            [115] = {name = "Lighthouse"},
            [116] = {name = "Mahogany Town"},
            [117] = {name = "Ilex Forest"},
            [118] = {name = "Goldenrod Tunnel"},
            [119] = {name = "Mr. Mortar"},
            [120] = {name = "Ice Path"},
            [121] = {name = "Whirl Islands"},
            [122] = {name = "Mt. Silver Cave"},
            [123] = {name = "Dark Cave"},
            [124] = {name = "Victory Road"},
            [125] = {name = "Dragon's Den"},
            [126] = {name = "Tohjo Falls"},
            [127] = {name = "Route 30"},
            [128] = {name = "Ecruteak City"},
            [129] = {name = "Ecruteak City"},
            [130] = {name = "Ecruteak City"},
            [131] = {name = "Ecruteak City"},
            [132] = {name = "Route 42"},
            [133] = {name = "Mahogany Town"},
            [134] = {name = "Route 29"},
            [135] = {name = "Violet City's gym"},
            [136] = {name = "Azalea Town's gym"},
            [137] = {name = "Goldenrod City's gym"},
            [138] = {name = "Olivine City's gym"},
            [139] = {name = "Cianwood City's gym"},
            [140] = {name = "Mahogany Town's gym"},
            [141] = {name = "Blackthorn City's gym"},
            [142] = {name = "Route 43"},
            [143] = {name = "Route 30"},
            [144] = {name = "Cherrygrove City"},
            [145] = {name = "Cerulean Cave"},
            [146] = {name = "Seafoam Islands"},
            [147] = {name = "Viridian Forest"},
            [148] = {name = "Power Plant"},
            [149] = {name = "Route 36"},
            [150] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [151] = {name = "Route 47"},
            [152] = {name = "Route 48"},
            [153] = {name = "Union Cave"},
            [154] = {name = "Union Cave"},
            [155] = {name = "Sprout Tower 1F"},
            [156] = {name = "Sprout Tower 2F"},
            [157] = {name = "Violet City"},
            [158] = {name = "Violet City"},
            [159] = {name = "Violet City"},
            [160] = {name = "Violet City"},
            [161] = {name = "Jubilife City"},
            [162] = {name = "Violet City"},
            [163] = {name = "Azalea Town"},
            [164] = {name = "Azalea Town"},
            [165] = {name = "Azalea Town"},
            [166] = {name = "Azalea Town"},
            [167] = {name = "Violet City"},
            [168] = {name = "Azalea Town"},
            [169] = {name = "Route 32"},
            [170] = {name = "Route 32"},
            [171] = {name = "Route 34"},
            [172] = {name = "Route 38"},
            [173] = {name = "Safari Zone Gate"},
            [174] = {name = "Safari Zone Gate"},
            [175] = {name = "Jubilife City"},
            [176] = {name = "Dark Cave"},
            [177] = {name = "Slowpoke Well"},
            [178] = {name = "Victory Road"},
            [179] = {name = "Victory Road"},
            [180] = {name = "Azalea Town's gym"},
            [181] = {name = "Slowpoke Well"},
            [182] = {name = "Goldenrod City"},
            [183] = {name = "Goldenrod City"},
            [184] = {name = "Goldenrod City"},
            [185] = {name = "Goldenrod City"},
            [186] = {name = "Radio Tower"},
            [187] = {name = "Radio Tower"},
            [188] = {name = "Radio Tower"},
            [189] = {name = "Radio Tower"},
            [190] = {name = "Radio Tower"},
            [191] = {name = "Goldenrod City"},
            [192] = {name = "Goldenrod City"},
            [193] = {name = "Goldenrod City"},
            [194] = {name = "Goldenrod City"},
            [195] = {name = "Goldenrod City"},
            [196] = {name = "Goldenrod City"},
            [197] = {name = "Goldenrod City"},
            [198] = {name = "Goldenrod City"},
            [199] = {name = "Goldenrod Tunnel"},
            [200] = {name = "Goldenrod City"},
            [201] = {name = "Goldenrod City"},
            [202] = {name = "Goldenrod City"},
            [203] = {name = "Goldenrod City"},
            [204] = {name = "Goldenrod City"},
            [205] = {name = "Goldenrod City"},
            [206] = {name = "Goldenrod City"},
            [207] = {name = "Global Terminal"},
            [208] = {name = "Goldenrod City"},
            [209] = {name = "Goldenrod City"},
            [210] = {name = "Goldenrod City"},
            [211] = {name = "Goldenrod City"},
            [212] = {name = "Goldenrod City"},
            [213] = {name = "Goldenrod City"},
            [214] = {name = "Route 39"},
            [215] = {name = "Route 39"},
            [216] = {name = "Ecruteak City"},
            [217] = {name = "Burned Tower"},
            [218] = {name = "Ruins of Alph"},
            [219] = {name = "Goldenrod City"},
            [220] = {name = "Lighthouse"},
            [221] = {name = "Lighthouse"},
            [222] = {name = "Lighthouse"},
            [223] = {name = "Lighthouse"},
            [224] = {name = "Lighthouse"},
            [225] = {name = "Lighthouse"},
            [226] = {name = "Olivine City"},
            [227] = {name = "Olivine City"},
            [228] = {name = "Olivine City"},
            [229] = {name = "Olivine City"},
            [230] = {name = "Olivine City"},
            [231] = {name = "Olivine City"},
            [232] = {name = "Cianwood City"},
            [233] = {name = "Cianwood City"},
            [234] = {name = "Cianwood City"},
            [235] = {name = "Cianwood City"},
            [236] = {name = "Cianwood City"},
            [237] = {name = "Ice Path"},
            [238] = {name = "Ice Path"},
            [239] = {name = "Ice Path"},
            [240] = {name = "Olivine City"},
            [241] = {name = "Cianwood City"},
            [242] = {name = "Whirl Islands"},
            [243] = {name = "Whirl Islands"},
            [244] = {name = "Whirl Islands"},
            [245] = {name = "Route 43"},
            [246] = {name = "Mahogany Town"},
            [247] = {name = "Team Rocket HQ"},
            [248] = {name = "Team Rocket HQ"},
            [249] = {name = "Team Rocket HQ"},
            [250] = {name = "Mt. Mortar"},
            [251] = {name = "Mt. Mortar"},
            [252] = {name = "Mt. Mortar"},
            [253] = {name = "Dragon's Den"},
            [254] = {name = "Fight Area"},
            [255] = {name = "Fight Area"},
            [256] = {name = "Fight Area"},
            [257] = {name = "Fight Area"},
            [258] = {name = "Fight Area"},
            [259] = {name = "Fight Area"},
            [260] = {name = "Fight Area"},
            [261] = {name = "Fight Area"},
            [262] = {name = "Fight Area"},
            [263] = {name = "Battle Park"},
            [264] = {name = "Battle Park"},
            [265] = {name = "Battle Tower"},
            [266] = {name = "Battle Tower"},
            [267] = {name = "Battle Tower"},
            [268] = {name = "Battle Tower"},
            [269] = {name = "Battle Tower"},
            [270] = {name = "Battle Tower"},
            [271] = {name = "Battle Tower"},
            [272] = {name = "Battle Frontier"},
            [273] = {name = "Battle Frontier"},
            [274] = {name = "Battle Tower"},
            [275] = {name = "Battle Factory"},
            [276] = {name = "Battle Hall"},
            [277] = {name = "Battle Castle"},
            [278] = {name = "Battle Arcade"},
            [279] = {name = "Cliff Edge Gate"},
            [280] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [281] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [282] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [283] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [284] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [285] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [286] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [287] = {name = "Pok" .. Chars.accentedE .. "athlon Dome"},
            [288] = {name = "Dragon's Den"},
            [289] = {name = "Blackthorn City"},
            [290] = {name = "Blackthorn City"},
            [291] = {name = "Blackthorn City"},
            [292] = {name = "Blackthorn City"},
            [293] = {name = "Blackthorn City"},
            [294] = {name = "Lake of Rage"},
            [295] = {name = "Lake of Rage"},
            [296] = {name = "Route 26"},
            [297] = {name = "Route 26"},
            [298] = {name = "Tohjo Falls"},
            [299] = {name = "Route 26"},
            [300] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [301] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [302] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [303] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [304] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [305] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [306] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [307] = {name = "S.S. Aqua"},
            [308] = {name = "S.S. Aqua"},
            [309] = {name = "S.S. Aqua"},
            [310] = {name = "S.S. Aqua"},
            [311] = {name = "S.S. Aqua"},
            [312] = {name = "Ruins of Alph"},
            [313] = {name = "Ruins of Alph"},
            [314] = {name = "Ruins of Alph"},
            [315] = {name = "Ruins of Alph"},
            [316] = {name = "Ruins of Alph"},
            [317] = {name = "Ruins of Alph"},
            [318] = {name = "Ruins of Alph"},
            [319] = {name = "Ruins of Alph"},
            [320] = {name = "Ruins of Alph"},
            [321] = {name = "Ruins of Alph"},
            [322] = {name = "Route 27"},
            [323] = {name = "Ruins of Alph"},
            [324] = {name = "Ruins of Alph"},
            [325] = {name = "Ruins of Alph"},
            [326] = {name = "Ruins of Alph"},
            [327] = {name = "Ruins of Alph"},
            [328] = {name = "S.S. Aqua"},
            [329] = {name = "S.S. Aqua"},
            [330] = {name = "Olivine City"},
            [331] = {name = "Route 34"},
            [332] = {name = "Bell Tower"},
            [333] = {name = "Bell Tower"},
            [334] = {name = "Bell Tower"},
            [335] = {name = "Bell Tower"},
            [336] = {name = "Bell Tower"},
            [337] = {name = "Bell Tower"},
            [338] = {name = "Bell Tower"},
            [339] = {name = "Bell Tower"},
            [340] = {name = "Bell Tower"},
            [341] = {name = "Bell Tower"},
            [342] = {name = "Cliff Cave"},
            [343] = {name = "Safari Zone"},
            [344] = {name = "Safari Zone"},
            [345] = {name = "Safari Zone"},
            [346] = {name = "Safari Zone"},
            [347] = {name = "Safari Zone"},
            [348] = {name = "Safari Zone"},
            [349] = {name = "Safari Zone"},
            [350] = {name = "Safari Zone"},
            [351] = {name = "Safari Zone"},
            [352] = {name = "Safari Zone"},
            [353] = {name = "Safari Zone"},
            [354] = {name = "Safari Zone"},
            [355] = {name = "Safari Zone"},
            [356] = {name = "Safari Zone"},
            [357] = {name = "Safari Zone"},
            [358] = {name = "Vermilion City"},
            [359] = {name = "Vermilion City"},
            [360] = {name = "Vermilion City"},
            [361] = {name = "Vermilion City"},
            [362] = {name = "Vermilion City"},
            [363] = {name = "Vermilion City"},
            [364] = {name = "Vermilion City"},
            [365] = {name = "Vermilion City's gym"},
            [366] = {name = "Route 40"},
            [367] = {name = "Olivine City"},
            [368] = {name = "Mahogany Town"},
            [369] = {name = "Blackthorn City"},
            [370] = {name = "Celadon City"},
            [371] = {name = "Celadon City"},
            [372] = {name = "Celadon City"},
            [373] = {name = "Celadon City"},
            [374] = {name = "Celadon City"},
            [375] = {name = "Celadon City"},
            [376] = {name = "Celadon City"},
            [377] = {name = "Celadon City"},
            [378] = {name = "Celadon City"},
            [379] = {name = "Celadon City"},
            [380] = {name = "Celadon City"},
            [381] = {name = "Celadon City"},
            [382] = {name = "Celadon City"},
            [383] = {name = "Celadon City"},
            [384] = {name = "New Bark Town"},
            [385] = {name = "Cianwood City"},
            [386] = {name = "Vermilion City"},
            [387] = {name = "Vermilion City"},
            [388] = {name = "Route 10"},
            [389] = {name = "Route 6"},
            [390] = {name = "Route 8"},
            [391] = {name = "Route 5"},
            [392] = {name = "Route 15"},
            [393] = {name = "Celadon City"},
            [394] = {name = "Celadon City"},
            [395] = {name = "Celadon City's gym"},
            [396] = {name = "Mahogany Town's gym"},
            [397] = {name = "Mahogany Town's gym"},
            [398] = {name = "Saffron City"},
            [399] = {name = "Saffron City"},
            [400] = {name = "Saffron City"},
            [401] = {name = "Saffron City"},
            [402] = {name = "Saffron City"},
            [403] = {name = "Rotom Room"},
            [404] = {name = "Saffron City"},
            [405] = {name = "Saffron City"},
            [406] = {name = "Saffron City"},
            [407] = {name = "Saffron City"},
            [408] = {name = "Saffron City"},
            [409] = {name = "Saffron City"},
            [410] = {name = "Saffron City's gym"},
            [411] = {name = "Frontier Access"},
            [412] = {name = "Global Terminal"},
            [413] = {name = "Global Terminal"},
            [414] = {name = "Route 2"},
            [415] = {name = "Route 16"},
            [416] = {name = "Route 20"},
            [417] = {name = "Route 2"},
            [418] = {name = "Route 2"},
            [419] = {name = "Route 2"},
            [420] = {name = "Route 2"},
            [421] = {name = "Route 16"},
            [422] = {name = "Route 16"},
            [423] = {name = "Route 18"},
            [424] = {name = "Route 19"},
            [425] = {name = "Route 11"},
            [426] = {name = "Cerulean City"},
            [427] = {name = "Cerulean City's gym"},
            [428] = {name = "Cerulean City"},
            [429] = {name = "Cerulean City"},
            [430] = {name = "Cerulean City"},
            [431] = {name = "Cerulean City"},
            [432] = {name = "Cerulean City"},
            [433] = {name = "Lavender Town"},
            [434] = {name = "Lavender Town"},
            [435] = {name = "Lavender Town"},
            [436] = {name = "Lavender Town"},
            [437] = {name = "Lavender Town"},
            [438] = {name = "Lavender Town"},
            [439] = {name = "Lavender Town"},
            [440] = {name = "Route 25"},
            [441] = {name = "Goldenrod City"},
            [442] = {name = "Celadon City"},
            [443] = {name = "Celadon City"},
            [444] = {name = "Celadon City"},
            [445] = {name = "Saffron City"},
            [446] = {name = "Lighthouse"},
            [447] = {name = "Radio Tower"},
            [448] = {name = "Mt. Moon"},
            [449] = {name = "Mt. Moon"},
            [450] = {name = "Cerulean Cave"},
            [451] = {name = "Cerulean Cave"},
            [452] = {name = "Rock Tunnel"},
            [453] = {name = "Seafoam Islands"},
            [454] = {name = "Seafoam Islands"},
            [455] = {name = "Seafoam Islands"},
            [456] = {name = "Seafoam Islands"},
            [457] = {name = "Seafoam Islands"},
            [458] = {name = "Seafoam Islands"},
            [459] = {name = "Mt. Silver Cave"},
            [460] = {name = "Mt. Silver Cave"},
            [461] = {name = "Mt. Silver Cave"},
            [462] = {name = "Mt. Silver Cave"},
            [463] = {name = "Mt. Silver Cave"},
            [464] = {name = "Mt. Silver Cave"},
            [465] = {name = "Mt. Silver Cave"},
            [466] = {name = "Route 10"},
            [467] = {name = "Power Plant"},
            [468] = {name = "Route 5"},
            [469] = {name = "Route 5"},
            [470] = {name = "Route 6"},
            [471] = {name = "Pewter City"},
            [472] = {name = "Pewter City"},
            [473] = {name = "Pewter City's gym"},
            [474] = {name = "Pewter City"},
            [475] = {name = "Pewter City"},
            [476] = {name = "Pewter City"},
            [477] = {name = "Pewter City"},
            [478] = {name = "Fuchsia City"},
            [479] = {name = "Pal Park"},
            [480] = {name = "Fuchsia City's gym"},
            [481] = {name = "Fuchsia City"},
            [482] = {name = "Fuchsia City"},
            [483] = {name = "Fuchsia City"},
            [484] = {name = "Route 10"},
            [485] = {name = "Fuchsia City"},
            [486] = {name = "Whirl Islands"},
            [487] = {name = "National Park"},
            [488] = {name = "National Park"},
            [489] = {name = "Power Plant"},
            [490] = {name = "Ruins of Alph"},
            [491] = {name = "Ruins of Alph"},
            [492] = {name = "Ruins of Alph"},
            [493] = {name = "Route 7"},
            [494] = {name = "Lavender Town"},
            [495] = {name = "Cerulean City"},
            [496] = {name = "Viridian City's gym"},
            [497] = {name = "Viridian City"},
            [498] = {name = "Viridian City"},
            [499] = {name = "Viridian City"},
            [500] = {name = "Viridian City"},
            [501] = {name = "Viridian City"},
            [502] = {name = "Viridian City"},
            [503] = {name = "Pallet Town"},
            [504] = {name = "Pallet Town"},
            [505] = {name = "Pallet Town"},
            [506] = {name = "Pallet Town"},
            [507] = {name = "Pallet Town"},
            [508] = {name = "Cinnabar Island"},
            [509] = {name = "Cinnabar Island"},
            [510] = {name = "Route 28"},
            [511] = {name = "Route 3"},
            [512] = {name = "Route 3"},
            [513] = {name = "Mt. Moon"},
            [514] = {name = "Mt. Silver"},
            [515] = {name = "Mt. Silver"},
            [516] = {name = "Mystery Zone"},
            [517] = {name = "Route 5"},
            [518] = {name = "Mt. Moon"},
            [519] = {name = "Goldenrod City"},
            [520] = {name = "Saffron City"},
            [521] = {name = "Sinjoh Ruins"},
            [522] = {name = "Sinjoh Ruins"},
            [523] = {name = "Sinjoh Ruins"},
            [524] = {name = "Embedded Tower"},
            [525] = {name = "Embedded Tower"},
            [526] = {name = "Embedded Tower"},
            [527] = {name = "Route 1"},
            [528] = {name = "Frontier Access"},
            [529] = {name = "Frontier Access"},
            [530] = {name = "Frontier Access"},
            [531] = {name = "Frontier Access"},
            [532] = {name = "Route 5"},
            [533] = {name = "Route 12"},
            [534] = {name = "Safari Zone Gate"},
            [535] = {name = "Safari Zone Gate"},
            [536] = {name = "Goldenrod City"},
            [537] = {name = "Celadon City"},
            [538] = {name = "Mystery Zone"},
            [539] = {name = "Pok" .. Chars.accentedE .. "mon League"}
        },
        encounters = {
            ["Route 29"] = {
                totalPokemon = 3,
                vanillaData = {
                    {
                        {level = 3, percent = 30},
                        {level = 5, percent = 20},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 3, percent = 10},
                        {level = 5, percent = 30}
                    },
                    {
                        {level = 6, percent = 5}
                    }
                }
            },
            ["Route 46"] = {
                totalPokemon = 3,
                vanillaData = {
                    {
                        {level = 3, percent = 10},
                        {level = 5, percent = 30}
                    },
                    {
                        {level = 3, percent = 30},
                        {level = 5, percent = 5}
                    },
                    {
                        {level = 3, percent = 20},
                        {level = 6, percent = 5}
                    }
                }
            },
            ["Route 30"] = {
                totalPokemon = 3,
                vanillaData = {
                    {
                        {level = 3, percent = 30},
                        {level = 6, percent = 20}
                    },
                    {
                        {level = 5, percent = 30},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 6, percent = 15}
                    }
                }
            },
            ["Route 31"] = {
                totalPokemon = 4,
                vanillaData = {
                    {
                        {level = 6, percent = 30},
                        {level = 8, percent = 5}
                    },
                    {
                        {level = 5, percent = 30}
                    },
                    {
                        {level = 5, percent = 20}
                    },
                    {
                        {level = 8, percent = 15}
                    }
                }
            },
            ["Route 32"] = {
                totalPokemon = 4,
                vanillaData = {
                    {
                        {level = 6, percent = 35},
                        {level = 9, percent = 5}
                    },
                    {
                        {level = 9, percent = 30}
                    },
                    {
                        {level = 9, percent = 20}
                    },
                    {
                        {level = 9, percent = 10}
                    }
                }
            },
            ["Dark Cave"] = {
                totalPokemon = 3,
                vanillaData = {
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 30},
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 3, percent = 30},
                        {level = 5, percent = 5},
                        {level = 6, percent = 4}
                    },
                    {
                        {level = 6, percent = 1}
                    }
                }
            },
            ["Ruins of Alph"] = {
                totalPokemon = 1,
                vanillaData = {
                    {
                        {level = 8, percent = 100}
                    }
                }
            },
            ["Sprout Tower 1F"] = {
                totalPokemon = 1,
                vanillaData = {
                    {
                        {level = 5, percent = 40},
                        {level = 6, percent = 30},
                        {level = 8, percent = 25},
                        {level = 9, percent = 5}
                    }
                }
            },
            ["Sprout Tower 2F"] = {
                totalPokemon = 1,
                vanillaData = {
                    {
                        {level = 5, percent = 40},
                        {level = 6, percent = 30},
                        {level = 8, percent = 25},
                        {level = 9, percent = 5}
                    }
                }
            },
            ["Cherrygrove City"] = nil
        },
        encounterAreaOrder = {
            "Route 29",
            "Route 46",
            "Cherrygrove City",
            "Route 30",
            "Route 31",
            "Route 32",
            "Ruins of Alph",
            "Sprout Tower 1F",
            "Sprout Tower 2F"
            --"Dark Cave"
        }
    },
    --black/white
    [0x4F425249] = {
        locations = {
            [0] = {name = "Black City"},
            [6] = {name = "Striaton City"},
            [7] = {name = "Striaton City's gym"},
            [16] = {name = "Nacrene City"},
            [18] = {name = "Nacrene City's gym"},
            [19] = {name = "Nacrene City's gym"},
            [28] = {name = "Castelia City"},
            [29] = {name = "Castelia City's gym"},
            [62] = {name = "Nimbasa City"},
            [63] = {name = "Nimbasa City's gym"},
            [96] = {name = "Driftveil City"},
            [97] = {name = "Driftveil City's gym"},
            [107] = {name = "Mistralton City"},
            [108] = {name = "Mistralton City's gym"},
            [113] = {name = "Icirrus City"},
            [114] = {name = "Icirrus City's gym"},
            [120] = {name = "Opelucid City"},
            [121] = {name = "Opelucid City's gym"},
            [136] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [147] = {name = "Unity Tower"},
            [152] = {name = "Dreamyard"},
            [154] = {name = "Pinwheel Exterior"},
            [155] = {name = "Pinwheel Forest"},
            [157] = {name = "Desert Resort"},
            [160] = {name = "Relic Castle"},
            [191] = {name = "Cold Storage"},
            [194] = {name = "Chargestone Cave"},
            [198] = {name = "Twist Mountain"},
            [205] = {name = "Dragonspiral Tower"},
            [214] = {name = "Victory Road"},
            [230] = {name = "Giant Chasm"},
            [235] = {name = "Liberty Garden"},
            [238] = {name = "P2 Laboratory"},
            [240] = {name = "Undella Bay"},
            [241] = {name = "Abyssal Ruins"},
            [249] = {name = "Skyarrow Bridge"},
            [253] = {name = "Driftveil Drawbridge"},
            [254] = {name = "Tubeline Bridge"},
            [255] = {name = "Village Bridge"},
            [263] = {name = "Marvelous Bridge"},
            [264] = {name = "N's Castle"},
            [279] = {name = "Entree Forest"},
            [289] = {name = "Nimbasa City"},
            [290] = {name = "Driftveil City"},
            [291] = {name = "Mistralton City"},
            [292] = {name = "Icirrus City"},
            [293] = {name = "Opelucid City"},
            [294] = {name = "Black City"},
            [295] = {name = "White Forest"},
            [296] = {name = "Cold Storage"},
            [297] = {name = "Chargestone Cave"},
            [298] = {name = "Twist Mountain"},
            [299] = {name = "Dragonspiral Tower"},
            [300] = {name = "Giant Chasm"},
            [301] = {name = "Driftveil Drawbridge"},
            [302] = {name = "Tubeline Bridge"},
            [303] = {name = "Marvelous Bridge"},
            [304] = {name = "Route 5"},
            [305] = {name = "Route 6"},
            [306] = {name = "Route 7"},
            [307] = {name = "Route 8"},
            [308] = {name = "Route 9"},
            [309] = {name = "Route 11"},
            [310] = {name = "Route 12"},
            [311] = {name = "Route 13"},
            [312] = {name = "Route 14"},
            [313] = {name = "Route 15"},
            [314] = {name = "Route 16"},
            [315] = {name = "Lacunosa Town"},
            [316] = {name = "Undella Town"},
            [317] = {name = "Route 1"},
            [319] = {name = "Route 2"},
            [321] = {name = "Route 3"},
            [324] = {name = "Wellspring Cave"},
            [326] = {name = "Route 4"},
            [329] = {name = "Route 5"},
            [331] = {name = "Route 6"},
            [333] = {name = "Mistralton Cave"},
            [337] = {name = "Route 7"},
            [338] = {name = "Celestial Tower"},
            [345] = {name = "Route 8"},
            [346] = {name = "Moor of Icirrus"},
            [348] = {name = "Route 9"},
            [352] = {name = "Challenger's Cave"},
            [355] = {name = "Route 10"},
            [365] = {name = "Route 11"},
            [368] = {name = "Route 12"},
            [370] = {name = "Route 13"},
            [374] = {name = "Route 14"},
            [376] = {name = "Abundant Shrine"},
            [378] = {name = "Route 15"},
            [381] = {name = "Pok" .. Chars.accentedE .. " Transfer Lab"},
            [383] = {name = "Route 16"},
            [385] = {name = "Lostlorn Forest"},
            [387] = {name = "Route 18"},
            [389] = {name = "Nuvema Town"},
            [391] = {name = "Lab"},
            [397] = {name = "Accumula Town"},
            [406] = {name = "Lacunosa Town"},
            [412] = {name = "Undella Town"},
            [418] = {name = "Anville Town"},
            [423] = {name = "Route 17"},
            [424] = {name = "White Forest"}
        },
        encounters = {
            ["Route 1"] = {
                totalPokemon = 12,
                vanillaData = {
                    {
                        {level = 3, percent = 20}
                    },
                    {
                        {level = 3, percent = 20}
                    },
                    {
                        {level = 5, percent = 10}
                    },
                    {
                        {level = 5, percent = 10}
                    },
                    {
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 6, percent = 4}
                    },
                    {
                        {level = 6, percent = 4}
                    },
                    {
                        {level = 6, percent = 1}
                    },
                    {
                        {level = 6, percent = 1}
                    }
                }
            },
            ["Route 2"] = {
                totalPokemon = 12,
                vanillaData = {
                    {
                        {level = 6, percent = 20}
                    },
                    {
                        {level = 6, percent = 20}
                    },
                    {
                        {level = 6, percent = 10}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 9, percent = 5}
                    },
                    {
                        {level = 9, percent = 5}
                    },
                    {
                        {level = 11, percent = 4}
                    },
                    {
                        {level = 11, percent = 4}
                    },
                    {
                        {level = 11, percent = 1}
                    },
                    {
                        {level = 11, percent = 1}
                    }
                }
            },
            ["Dreamyard"] = {
                totalPokemon = 12,
                vanillaData = {
                    {
                        {level = 12, percent = 20}
                    },
                    {
                        {level = 12, percent = 20}
                    },
                    {
                        {level = 12, percent = 10}
                    },
                    {
                        {level = 14, percent = 10}
                    },
                    {
                        {level = 14, percent = 10}
                    },
                    {
                        {level = 15, percent = 10}
                    },
                    {
                        {level = 15, percent = 5}
                    },
                    {
                        {level = 15, percent = 5}
                    },
                    {
                        {level = 17, percent = 4}
                    },
                    {
                        {level = 17, percent = 4}
                    },
                    {
                        {level = 17, percent = 1}
                    },
                    {
                        {level = 17, percent = 1}
                    }
                }
            },
            ["Route 3"] = {
                totalPokemon = 12,
                vanillaData = {
                    {
                        {level = 12, percent = 20}
                    },
                    {
                        {level = 12, percent = 20}
                    },
                    {
                        {level = 12, percent = 10}
                    },
                    {
                        {level = 14, percent = 10}
                    },
                    {
                        {level = 14, percent = 10}
                    },
                    {
                        {level = 14, percent = 10}
                    },
                    {
                        {level = 14, percent = 5}
                    },
                    {
                        {level = 15, percent = 5}
                    },
                    {
                        {level = 15, percent = 4}
                    },
                    {
                        {level = 17, percent = 4}
                    },
                    {
                        {level = 17, percent = 1}
                    },
                    {
                        {level = 17, percent = 1}
                    }
                }
            }
        },
        encounterAreaOrder = {"Route 1", "Route 2", "Dreamyard", "Route 3"}
    },
    --black2/white2
    [0x4F455249] = {
        locations = {
            [0] = {name = "Black City"},
            [6] = {name = "Striaton City"},
            [16] = {name = "Nacrene City"},
            [28] = {name = "Castelia City"},
            [29] = {name = "Castelia City's gym"},
            [62] = {name = "Nimbasa City"},
            [67] = {name = "Nimbasa City's gym"},
            [96] = {name = "Driftveil City"},
            [102] = {name = "Driftveil City's gym"},
            [107] = {name = "Mistralton City"},
            [121] = {name = "Mistralton City's gym"},
            [113] = {name = "Icirrus City"},
            [120] = {name = "Opelucid City"},
            [134] = {name = "Opelucid City's gym"},
            [136] = {name = "Pok" .. Chars.accentedE .. "mon League"},
            [147] = {name = "Unity Tower"},
            [152] = {name = "Dreamyard"},
            [154] = {name = "Pinwheel Exterior"},
            [155] = {name = "Pinwheel Forest"},
            [157] = {name = "Desert Resort"},
            [160] = {name = "Relic Castle"},
            [191] = {name = "Cold Storage"},
            [194] = {name = "Chargestone Cave"},
            [198] = {name = "Twist Mountain"},
            [205] = {name = "Dragonspiral Tower"},
            [214] = {name = "Victory Road"},
            [230] = {name = "Giant Chasm"},
            [235] = {name = "Liberty Garden"},
            [238] = {name = "P2 Laboratory"},
            [240] = {name = "Undella Bay"},
            [241] = {name = "Abyssal Ruins"},
            [249] = {name = "Skyarrow Bridge"},
            [253] = {name = "Driftveil Drawbridge"},
            [254] = {name = "Tubeline Bridge"},
            [255] = {name = "Village Bridge"},
            [263] = {name = "Marvelous Bridge"},
            [264] = {name = "N's Castle"},
            [279] = {name = "Entree Forest"},
            [289] = {name = "Nimbasa City"},
            [290] = {name = "Driftveil City"},
            [291] = {name = "Mistralton City"},
            [292] = {name = "Icirrus City"},
            [293] = {name = "Opelucid City"},
            [294] = {name = "Black City"},
            [295] = {name = "White Forest"},
            [296] = {name = "Cold Storage"},
            [297] = {name = "Chargestone Cave"},
            [298] = {name = "Twist Mountain"},
            [299] = {name = "Dragonspiral Tower"},
            [300] = {name = "Giant Chasm"},
            [301] = {name = "Driftveil Drawbridge"},
            [302] = {name = "Tubeline Bridge"},
            [303] = {name = "Marvelous Bridge"},
            [304] = {name = "Route 5"},
            [305] = {name = "Route 6"},
            [306] = {name = "Route 7"},
            [307] = {name = "Route 8"},
            [308] = {name = "Route 9"},
            [309] = {name = "Route 11"},
            [310] = {name = "Route 12"},
            [311] = {name = "Route 13"},
            [312] = {name = "Route 14"},
            [313] = {name = "Route 15"},
            [314] = {name = "Route 16"},
            [315] = {name = "Lacunosa Town"},
            [316] = {name = "Undella Town"},
            [317] = {name = "Route 1"},
            [319] = {name = "Route 2"},
            [321] = {name = "Route 3"},
            [324] = {name = "Wellspring Cave"},
            [326] = {name = "Route 4"},
            [329] = {name = "Route 5"},
            [331] = {name = "Route 6"},
            [333] = {name = "Mistralton Cave"},
            [337] = {name = "Route 7"},
            [338] = {name = "Celestial Tower"},
            [345] = {name = "Route 8"},
            [346] = {name = "Moor of Icirrus"},
            [348] = {name = "Route 9"},
            [352] = {name = "Challenger's Cave"},
            [355] = {name = "Route 10"},
            [365] = {name = "Route 11"},
            [368] = {name = "Route 12"},
            [370] = {name = "Route 13"},
            [374] = {name = "Route 14"},
            [376] = {name = "Abundant Shrine"},
            [378] = {name = "Route 15"},
            [381] = {name = "Pok" .. Chars.accentedE .. " Transfer Lab"},
            [383] = {name = "Route 16"},
            [385] = {name = "Lostlorn Forest"},
            [387] = {name = "Route 18"},
            [389] = {name = "Nuvema Town"},
            [397] = {name = "Accumula Town"},
            [406] = {name = "Lacunosa Town"},
            [412] = {name = "Undella Town"},
            [418] = {name = "Anville Town"},
            [423] = {name = "Route 17"},
            [424] = {name = "White Forest"},
            [427] = {name = "Aspertia City"},
            [165] = {name = "Aspertia City's gym"},
            [437] = {name = "Route 19"},
            [439] = {name = "Floccesy Town"},
            [444] = {name = "Floccesy Ranch"},
            [446] = {name = "Route 20"},
            [448] = {name = "Virbank City"},
            [176] = {name = "Virbank City's gym"},
            [456] = {name = "Virbank Complex"},
            [458] = {name = "Lentimas Town"},
            [461] = {name = "Reversal Mountain"},
            [462] = {name = "Strange House"},
            [463] = {name = "Route 21"},
            [464] = {name = "Marine Tube"},
            [465] = {name = "Humilau City"},
            [184] = {name = "Humilau City's gym"},
            [474] = {name = "Route 22"},
            [475] = {name = "Route 23"},
            [30] = {name = "Castelia City's gym"},
            [490] = {name = "Join Avenue"},
            [495] = {name = "Castelia Sewers"},
            [503] = {name = "Relic Passage"},
            [506] = {name = "Clay Tunnel"},
            [515] = {name = "Seaside Cave"},
            [517] = {name = "Cave of Being"},
            [518] = {name = "Hidden Grotto"},
            [552] = {name = "Plasma Frigate"},
            [566] = {name = "Pok" .. Chars.accentedE .. "star Studios"},
            [584] = {name = "Nature Preserve"},
            [573] = {name = "Victory Road"}
        },
        encounterAreaOrder = {"Route 19", "Route 20", "Floccesy Ranch", "Virbank Complex"},
        encounters = {
            ["Route 19"] = {
                totalPokemon = 2,
                vanillaData = {
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 10},
                        {level = 6, percent = 20}
                    },
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 10},
                        {level = 6, percent = 20}
                    }
                }
            },
            ["Route 20"] = {
                totalPokemon = 5,
                vanillaData = {
                    {
                        {level = 3, percent = 20},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 3, percent = 20},
                        {level = 5, percent = 10},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 5, percent = 20}
                    },
                    {
                        {level = 5, percent = 10},
                        {level = 6, percent = 5}
                    },
                    {
                        {level = 6, percent = 5}
                    }
                }
            },
            ["Floccesy Ranch"] = {
                totalPokemon = 7,
                vanillaData = {
                    {
                        {level = 6, percent = 20},
                        {level = 8, percent = 10},
                        {level = 9, percent = 5},
                        {level = 11, percent = 5}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 8, percent = 10}
                    },
                    {
                        {level = 8, percent = 20}
                    },
                    {
                        {level = 8, percent = 4},
                        {level = 11, percent = 1}
                    },
                    {
                        {level = 11, percent = 5}
                    }
                }
            },
            ["Virbank Complex"] = {
                totalPokemon = 4,
                vanillaData = {
                    {
                        {level = 15, percent = 20},
                        {level = 18, percent = 5}
                    },
                    {
                        {level = 15, percent = 20},
                        {level = 18, percent = 5}
                    },
                    {
                        {level = 15, percent = 10},
                        {level = 18, percent = 4},
                        {level = 20, percent = 1}
                    },
                    {
                        {level = 15, percent = 10},
                        {level = 18, percent = 4},
                        {level = 20, percent = 1}
                    },
                    {
                        {level = 17, percent = 10},
                        {level = 20, percent = 10}
                    }
                }
            }
        }
    }
}
