MiscData.HEALING_TYPE = MiscUtils.readOnly({CONSTANT = 0, PERCENTAGE = 1})

MiscData.STATUS_TYPE =
	MiscUtils.readOnly(
	{
		POISON = 0,
		BURN = 1,
		FREEZE = 2,
		SLEEP = 3,
		PARALYZE = 4,
		CONFUSE = 5,
		All = 100
	}
)

MiscData.NATURES =
	MiscUtils.readOnly(
	{
		"Hardy",
		"Lonely",
		"Brave",
		"Adamant",
		"Naughty",
		"Bold",
		"Docile",
		"Relaxed",
		"Impish",
		"Lax",
		"Timid",
		"Hasty",
		"Serious",
		"Jolly",
		"Naive",
		"Modest",
		"Mild",
		"Quiet",
		"Bashful",
		"Rash",
		"Calm",
		"Gentle",
		"Sassy",
		"Careful",
		"Quirky"
	}
)

MiscData.ITEMS_GEN4 =
	MiscUtils.readOnly(
	{
		"---",
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb", -- 113 - 134 are "Unknown"
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Adamant Orb",
		"Lustrous Orb",
		"Grass Mail",
		"Flame Mail",
		"Bubble Mail",
		"Bloom Mail",
		"Tunnel Mail",
		"Steel Mail",
		"Heart Mail",
		"Snow Mail",
		"Space Mail",
		"Air Mail",
		"Mosaic Mail",
		"Brick Mail",
		"Chery Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebia Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"HM07",
		"HM08",
		"Explorer Kit",
		"Loot Sack",
		"Rule Book",
		"Poke Radar",
		"Point Card",
		"Journal",
		"Seal Case",
		"Fashion Case",
		"Seal Bag",
		"Pal Pad",
		"Works Key",
		"Old Charm",
		"Galactic Key",
		"Red Chain",
		"Town Map",
		"Vs. Seeker",
		"Coin Case",
		"Old Rod",
		"Good Rod",
		"Super Rod",
		"Sprayduck",
		"Poffin Case",
		"Bicycle",
		"Suite Key",
		"Oak's Letter",
		"Lunar Wing",
		"Member Card",
		"Azure Flute",
		"S.S. Ticket",
		"Contest Pass",
		"Magma Stone",
		"Parcel",
		"Coupon 1",
		"Coupon 2",
		"Coupon 3",
		"Storage Key",
		"SecretPotion",
		"Vs. Recorder",
		"Gracidea",
		"Secret Key",
		"Apricorn Box",
		"Unown Report",
		"Berry Pots",
		"Dowsing MCHN",
		"Blue Card",
		"SlowpokeTail",
		"Clear Bell",
		"Card Key",
		"Basement Key",
		"SquirtBottle",
		"Red Scale",
		"Lost Item",
		"Pass",
		"Machine Part",
		"Silver Wing",
		"Rainbow Wing",
		"Mystery Egg",
		"Red Apricorn",
		"Ylw Apricorn",
		"Blu Apricorn",
		"Grn Apricorn",
		"Pnk Apricorn",
		"Wht Apricorn",
		"Blk Apricorn",
		"Fast Ball",
		"Level Ball",
		"Lure Ball",
		"Heavy Ball",
		"Love Ball",
		"Friend Ball",
		"Moon Ball",
		"Sport Ball",
		"Park Ball",
		"Photo Album",
		"GB Sounds",
		"Tidal Bell",
		"RageCandyBar",
		"Data Card 01",
		"Data Card 02",
		"Data Card 03",
		"Data Card 04",
		"Data Card 05",
		"Data Card 06",
		"Data Card 07",
		"Data Card 08",
		"Data Card 09",
		"Data Card 10",
		"Data Card 11",
		"Data Card 12",
		"Data Card 13",
		"Data Card 14",
		"Data Card 15",
		"Data Card 16",
		"Data Card 17",
		"Data Card 18",
		"Data Card 19",
		"Data Card 20",
		"Data Card 21",
		"Data Card 22",
		"Data Card 23",
		"Data Card 24",
		"Data Card 25",
		"Data Card 26",
		"Data Card 27",
		"Jade Orb",
		"Lock Capsule",
		"Red Orb",
		"Blue Orb",
		"Enigma Stone"
	}
)
MiscData.ITEMS_GEN5 =
	MiscUtils.readOnly(
	{
		"---",
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb",
		"unknown",
		"unknown",
		"unknown",
		"Douse Drive",
		"Shock Drive",
		"Burn Drive",
		"Chill Drive",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Sweet Heart",
		"Adamant Orb",
		"Lustrous Orb",
		"Greet Mail",
		"Favored Mail",
		"RSVP Mail",
		"Thanks Mail",
		"Inquiry Mail",
		"Like Mail",
		"Reply Mail",
		"BridgeMail S",
		"BridgeMail D",
		"BridgeMail T",
		"BridgeMail V",
		"BridgeMail M",
		"Cheri Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebia Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"unknown",
		"unknown",
		"Explorer Kit",
		"Loot Sack",
		"Rule Book",
		"Poke Radar",
		"Point Card",
		"Journal",
		"Seal Case",
		"Fashion Case",
		"Seal Bag",
		"Pal Pad",
		"Works Key",
		"Old Charm",
		"Galactic Key",
		"Red Chain",
		"Town Map",
		"Vs. Seeker",
		"Coin Case",
		"Old Rod",
		"Good Rod",
		"Super Rod",
		"Sprayduck",
		"Poffin Case",
		"Bicycle",
		"Suite Key",
		"Oak's Letter",
		"Lunar Wing",
		"Member Card",
		"Azure Flute",
		"S.S. Ticket",
		"Contest Pass",
		"Magma Stone",
		"Parcel",
		"Coupon 1",
		"Coupon 2",
		"Coupon 3",
		"Storage Key",
		"SecretPotion",
		"Vs. Recorder",
		"Gracidea",
		"Secret Key",
		"Apricorn Box",
		"Unown Report",
		"Berry Pots",
		"Dowsing MCHN",
		"Blue Card",
		"SlowpokeTail",
		"Clear Bell",
		"Card Key",
		"Basement Key",
		"SquirtBottle",
		"Red Scale",
		"Lost Item",
		"Pass",
		"Machine Part",
		"Silver Wing",
		"Rainbow Wing",
		"Mystery Egg",
		"Red Apricorn",
		"Blu Apricorn",
		"Ylw Apricorn",
		"Grn Apricorn",
		"Pnk Apricorn",
		"Wht Apricorn",
		"Blk Apricorn",
		"Fast Ball",
		"Level Ball",
		"Lure Ball",
		"Heavy Ball",
		"Love Ball",
		"Friend Ball",
		"Moon Ball",
		"Sport Ball",
		"Park Ball",
		"Photo Album",
		"GB Sounds",
		"Tidal Bell",
		"RageCandyBar",
		"Data Card 01",
		"Data Card 02",
		"Data Card 03",
		"Data Card 04",
		"Data Card 05",
		"Data Card 06",
		"Data Card 07",
		"Data Card 08",
		"Data Card 09",
		"Data Card 10",
		"Data Card 11",
		"Data Card 12",
		"Data Card 13",
		"Data Card 14",
		"Data Card 15",
		"Data Card 16",
		"Data Card 17",
		"Data Card 18",
		"Data Card 19",
		"Data Card 20",
		"Data Card 21",
		"Data Card 22",
		"Data Card 23",
		"Data Card 24",
		"Data Card 25",
		"Data Card 26",
		"Data Card 27",
		"Jade Orb",
		"Lock Capsule",
		"Red Orb",
		"Blue Orb",
		"Enigma Stone",
		"Prism Scale",
		"Eviolite",
		"Float Stone",
		"Rocky Helmet",
		"Air Balloon",
		"Red Card",
		"Ring Target",
		"Binding Band",
		"Absorb Bulb",
		"Cell Battery",
		"Eject Button",
		"Fire Gem",
		"Water Gem",
		"Electric Gem",
		"Grass Gem",
		"Ice Gem",
		"Fighting Gem",
		"Poison Gem",
		"Ground Gem",
		"Flying Gem",
		"Psychic Gem",
		"Bug Gem",
		"Rock Gem",
		"Ghost Gem",
		"Dragon Gem",
		"Dark Gem",
		"Steel Gem",
		"Normal Gem",
		"Health Wing",
		"Muscle Wing",
		"Resist Wing",
		"Genius Wing",
		"Clever Wing",
		"Swift Wing",
		"Pretty Wing",
		"Cover Fossil",
		"Plume Fossil",
		"Liberty Pass",
		"Pass Orb",
		"Dream Ball",
		"Poke Toy",
		"Prop Case",
		"Dragon Skull",
		"BalmMushroom",
		"Big Nugget",
		"Pearl String",
		"Comet Shard",
		"Relic Copper",
		"Relic Silver",
		"Relic Gold",
		"Relic Vase",
		"Relic Band",
		"Relic Statue",
		"Relic Crown",
		"Casteliacone",
		"Dire Hit 2",
		"X Speed 2",
		"X Special 2",
		"X Sp. Def 2",
		"X Defend 2",
		"X Attack 2",
		"X Accuracy 2",
		"X Speed 3",
		"X Special 3",
		"X Sp. Def 3",
		"X Defend 3",
		"X Attack 3",
		"X Accuracy 3",
		"X Speed 6",
		"X Special 6",
		"X Sp. Def 6",
		"X Defend 6",
		"X Attack 6",
		"X Accuracy 6",
		"Ability Urge",
		"Item Drop",
		"Reset Urge",
		"Dire Hit 3",
		"Light Stone",
		"Dark Stone",
		"TM93",
		"TM94",
		"TM95"
	}
)
MiscData.HEALING_ITEMS_GEN4 =
	MiscUtils.readOnly(
	{
		[17] = {
			name = "Potion",
			amount = 20,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[23] = {
			name = "Full Restore",
			amount = 100,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[24] = {
			name = "Max Potion",
			amount = 100,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[25] = {
			name = "Hyper Potion",
			amount = 200,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[26] = {
			name = "Super Potion",
			amount = 60,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[30] = {
			name = "Fresh Water",
			amount = 50,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[31] = {
			name = "Soda Pop",
			amount = 60,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[32] = {
			name = "Lemonade",
			amount = 80,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[33] = {
			name = "Moomoo Milk",
			amount = 100,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[34] = {
			name = "EnergyPowder",
			amount = 50,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[35] = {
			name = "Energy Root",
			amount = 200,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[43] = {
			name = "Berry Juice",
			amount = 20,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[155] = {
			name = "Oran Berry",
			amount = 10,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[158] = {
			name = "Sitrus Berry",
			amount = 30,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[159] = {
			name = "Figy Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[160] = {
			name = "Wiki Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[161] = {
			name = "Mago Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[162] = {
			name = "Aguav Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[163] = {
			name = "Iapapa Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[208] = {
			name = "Enigma Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		}
	}
)
MiscData.ABILITIES =
	MiscUtils.readOnly(
	{
		"---",
		"Stench",
		"Drizzle",
		"Speed Boost",
		"Battle Armor",
		"Sturdy",
		"Damp",
		"Limber",
		"Sand Veil",
		"Static",
		"Volt Absorb",
		"Water Absorb",
		"Oblivious",
		"Cloud Nine",
		"Compound Eyes",
		"Insomnia",
		"Color Change",
		"Immunity",
		"Flash Fire",
		"Shield Dust",
		"Own Tempo",
		"Suction Cups",
		"Intimidate",
		"Shadow Tag",
		"Rough Skin",
		"Wonder Guard",
		"Levitate",
		"Effect Spore",
		"Synchronize",
		"Clear Body",
		"Natural Cure",
		"Lightning Rod",
		"Serene Grace",
		"Swift Swim",
		"Chlorophyll",
		"Illuminate",
		"Trace",
		"Huge Power",
		"Poison Point",
		"Inner Focus",
		"Magma Armor",
		"Water Veil",
		"Magnet Pull",
		"Soundproof",
		"Rain Dish",
		"Sand Stream",
		"Pressure",
		"Thick Fat",
		"Early Bird",
		"Flame Body",
		"Run Away",
		"Keen Eye",
		"Hyper Cutter",
		"Pickup",
		"Truant",
		"Hustle",
		"Cute Charm",
		"Plus",
		"Minus",
		"Forecast",
		"Sticky Hold",
		"Shed Skin",
		"Guts",
		"Marvel Scale",
		"Liquid Ooze",
		"Overgrow",
		"Blaze",
		"Torrent",
		"Swarm",
		"Rock Head",
		"Drought",
		"Arena Trap",
		"Vital Spirit",
		"White Smoke",
		"Pure Power",
		"Shell Armor",
		"Air Lock",
		"Tangled Feet",
		"Motor Drive",
		"Rivalry",
		"Steadfast",
		"Snow Cloak",
		"Gluttony",
		"Anger Point",
		"Unburden",
		"Heatproof",
		"Simple",
		"Dry Skin",
		"Download",
		"Iron Fist",
		"Poison Heal",
		"Adaptability",
		"Skill Link",
		"Hydration",
		"Solar Power",
		"Quick Feet",
		"Normalize",
		"Sniper",
		"Magic Guard",
		"No Guard",
		"Stall",
		"Technician",
		"Leaf Guard",
		"Klutz",
		"Mold Breaker",
		"Super Luck",
		"Aftermath",
		"Anticipation",
		"Forewarn",
		"Unaware",
		"Tinted Lens",
		"Filter",
		"Slow Start",
		"Scrappy",
		"Storm Drain",
		"Ice Body",
		"Solid Rock",
		"Snow Warning",
		"Honey Gather",
		"Frisk",
		"Reckless",
		"Multitype",
		"Flower Gift",
		"Bad Dreams",
		"Pickpocket",
		"Sheer Force",
		"Contrary",
		"Unnerve",
		"Defiant",
		"Defeatist",
		"Cursed Body",
		"Healer",
		"Friend Guard",
		"Weak Armor",
		"Heavy Metal",
		"Light Metal",
		"Multiscale",
		"Toxic Boost",
		"Flare Boost",
		"Harvest",
		"Telepathy",
		"Moody",
		"Overcoat",
		"Poison Touch",
		"Regenerator",
		"Big Pecks",
		"Sand Rush",
		"Wonder Skin",
		"Analytic",
		"Illusion",
		"Imposter",
		"Infiltrator",
		"Mummy",
		"Moxie",
		"Justified",
		"Rattled",
		"Magic Bounce",
		"Sap Sipper",
		"Prankster",
		"Sand Force",
		"Iron Barbs",
		"Zen Mode",
		"Victory Star",
		"Turboblaze",
		"Teravolt"
	}
)
