MiscData.HEALING_TYPE = MiscUtils.readOnly({CONSTANT = 0, PERCENTAGE = 1})

MiscData.STATUS_TYPE =
	MiscUtils.readOnly(
	{
		POISON = 0,
		BURN = 1,
		FREEZE = 2,
		SLEEP = 3,
		PARALYZE = 4,
		CONFUSE = 5,
		All = 100
	}
)

MiscData.NATURES =
	MiscUtils.readOnly(
	{
		"Hardy",
		"Lonely",
		"Brave",
		"Adamant",
		"Naughty",
		"Bold",
		"Docile",
		"Relaxed",
		"Impish",
		"Lax",
		"Timid",
		"Hasty",
		"Serious",
		"Jolly",
		"Naive",
		"Modest",
		"Mild",
		"Quiet",
		"Bashful",
		"Rash",
		"Calm",
		"Gentle",
		"Sassy",
		"Careful",
		"Quirky"
	}
)

MiscData.ITEMS_GEN4 =
	MiscUtils.readOnly(
	{
		"---",
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb", -- 113 - 134 are "Unknown"
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Adamant Orb",
		"Lustrous Orb",
		"Grass Mail",
		"Flame Mail",
		"Bubble Mail",
		"Bloom Mail",
		"Tunnel Mail",
		"Steel Mail",
		"Heart Mail",
		"Snow Mail",
		"Space Mail",
		"Air Mail",
		"Mosaic Mail",
		"Brick Mail",
		"Chery Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebia Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"HM07",
		"HM08",
		"Explorer Kit",
		"Loot Sack",
		"Rule Book",
		"Poke Radar",
		"Point Card",
		"Journal",
		"Seal Case",
		"Fashion Case",
		"Seal Bag",
		"Pal Pad",
		"Works Key",
		"Old Charm",
		"Galactic Key",
		"Red Chain",
		"Town Map",
		"Vs. Seeker",
		"Coin Case",
		"Old Rod",
		"Good Rod",
		"Super Rod",
		"Sprayduck",
		"Poffin Case",
		"Bicycle",
		"Suite Key",
		"Oak's Letter",
		"Lunar Wing",
		"Member Card",
		"Azure Flute",
		"S.S. Ticket",
		"Contest Pass",
		"Magma Stone",
		"Parcel",
		"Coupon 1",
		"Coupon 2",
		"Coupon 3",
		"Storage Key",
		"SecretPotion",
		"Vs. Recorder",
		"Gracidea",
		"Secret Key",
		"Apricorn Box",
		"Unown Report",
		"Berry Pots",
		"Dowsing MCHN",
		"Blue Card",
		"SlowpokeTail",
		"Clear Bell",
		"Card Key",
		"Basement Key",
		"SquirtBottle",
		"Red Scale",
		"Lost Item",
		"Pass",
		"Machine Part",
		"Silver Wing",
		"Rainbow Wing",
		"Mystery Egg",
		"Red Apricorn",
		"Ylw Apricorn",
		"Blu Apricorn",
		"Grn Apricorn",
		"Pnk Apricorn",
		"Wht Apricorn",
		"Blk Apricorn",
		"Fast Ball",
		"Level Ball",
		"Lure Ball",
		"Heavy Ball",
		"Love Ball",
		"Friend Ball",
		"Moon Ball",
		"Sport Ball",
		"Park Ball",
		"Photo Album",
		"GB Sounds",
		"Tidal Bell",
		"RageCandyBar",
		"Data Card 01",
		"Data Card 02",
		"Data Card 03",
		"Data Card 04",
		"Data Card 05",
		"Data Card 06",
		"Data Card 07",
		"Data Card 08",
		"Data Card 09",
		"Data Card 10",
		"Data Card 11",
		"Data Card 12",
		"Data Card 13",
		"Data Card 14",
		"Data Card 15",
		"Data Card 16",
		"Data Card 17",
		"Data Card 18",
		"Data Card 19",
		"Data Card 20",
		"Data Card 21",
		"Data Card 22",
		"Data Card 23",
		"Data Card 24",
		"Data Card 25",
		"Data Card 26",
		"Data Card 27",
		"Jade Orb",
		"Lock Capsule",
		"Red Orb",
		"Blue Orb",
		"Enigma Stone"
	}
)
MiscData.ITEMS_GEN5 =
	MiscUtils.readOnly(
	{
		"---",
		"Master Ball",
		"Ultra Ball",
		"Great Ball",
		"Poke Ball",
		"Safari Ball",
		"Net Ball",
		"Dive Ball",
		"Nest Ball",
		"Repeat Ball",
		"Timer Ball",
		"Luxury Ball",
		"Premier Ball",
		"Dusk Ball",
		"Heal Ball",
		"Quick Ball",
		"Cherish Ball",
		"Potion",
		"Antidote",
		"Burn Heal",
		"Ice Heal",
		"Awakening",
		"Parlyz Heal",
		"Full Restore",
		"Max Potion",
		"Hyper Potion",
		"Super Potion",
		"Full Heal",
		"Revive",
		"Max Revive",
		"Fresh Water",
		"Soda Pop",
		"Lemonade",
		"Moomoo Milk",
		"EnergyPowder",
		"Energy Root",
		"Heal Powder",
		"Revival Herb",
		"Ether",
		"Max Ether",
		"Elixir",
		"Max Elixir",
		"Lava Cookie",
		"Berry Juice",
		"Sacred Ash",
		"HP Up",
		"Protein",
		"Iron",
		"Carbos",
		"Calcium",
		"Rare Candy",
		"PP Up",
		"Zinc",
		"PP Max",
		"Old Gateau",
		"Guard Spec.",
		"Dire Hit",
		"X Attack",
		"X Defend",
		"X Speed",
		"X Accuracy",
		"X Special",
		"X Sp. Def",
		"Poke Doll",
		"Fluffy Tail",
		"Blue Flute",
		"Yellow Flute",
		"Red Flute",
		"Black Flute",
		"White Flute",
		"Shoal Salt",
		"Shoal Shell",
		"Red Shard",
		"Blue Shard",
		"Yellow Shard",
		"Green Shard",
		"Super Repel",
		"Max Repel",
		"Escape Rope",
		"Repel",
		"Sun Stone",
		"Moon Stone",
		"Fire Stone",
		"Thunderstone",
		"Water Stone",
		"Leaf Stone",
		"TinyMushroom",
		"Big Mushroom",
		"Pearl",
		"Big Pearl",
		"Stardust",
		"Star Piece",
		"Nugget",
		"Heart Scale",
		"Honey",
		"Growth Mulch",
		"Damp Mulch",
		"Stable Mulch",
		"Gooey Mulch",
		"Root Fossil",
		"Claw Fossil",
		"Helix Fossil",
		"Dome Fossil",
		"Old Amber",
		"Armor Fossil",
		"Skull Fossil",
		"Rare Bone",
		"Shiny Stone",
		"Dusk Stone",
		"Dawn Stone",
		"Oval Stone",
		"Odd Keystone",
		"Griseous Orb",
		"unknown",
		"unknown",
		"unknown",
		"Douse Drive",
		"Shock Drive",
		"Burn Drive",
		"Chill Drive",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"unknown",
		"Sweet Heart",
		"Adamant Orb",
		"Lustrous Orb",
		"Greet Mail",
		"Favored Mail",
		"RSVP Mail",
		"Thanks Mail",
		"Inquiry Mail",
		"Like Mail",
		"Reply Mail",
		"BridgeMail S",
		"BridgeMail D",
		"BridgeMail T",
		"BridgeMail V",
		"BridgeMail M",
		"Cheri Berry",
		"Chesto Berry",
		"Pecha Berry",
		"Rawst Berry",
		"Aspear Berry",
		"Leppa Berry",
		"Oran Berry",
		"Persim Berry",
		"Lum Berry",
		"Sitrus Berry",
		"Figy Berry",
		"Wiki Berry",
		"Mago Berry",
		"Aguav Berry",
		"Iapapa Berry",
		"Razz Berry",
		"Bluk Berry",
		"Nanab Berry",
		"Wepear Berry",
		"Pinap Berry",
		"Pomeg Berry",
		"Kelpsy Berry",
		"Qualot Berry",
		"Hondew Berry",
		"Grepa Berry",
		"Tamato Berry",
		"Cornn Berry",
		"Magost Berry",
		"Rabuta Berry",
		"Nomel Berry",
		"Spelon Berry",
		"Pamtre Berry",
		"Watmel Berry",
		"Durin Berry",
		"Belue Berry",
		"Occa Berry",
		"Passho Berry",
		"Wacan Berry",
		"Rindo Berry",
		"Yache Berry",
		"Chople Berry",
		"Kebia Berry",
		"Shuca Berry",
		"Coba Berry",
		"Payapa Berry",
		"Tanga Berry",
		"Charti Berry",
		"Kasib Berry",
		"Haban Berry",
		"Colbur Berry",
		"Babiri Berry",
		"Chilan Berry",
		"Liechi Berry",
		"Ganlon Berry",
		"Salac Berry",
		"Petaya Berry",
		"Apicot Berry",
		"Lansat Berry",
		"Starf Berry",
		"Enigma Berry",
		"Micle Berry",
		"Custap Berry",
		"Jaboca Berry",
		"Rowap Berry",
		"BrightPowder",
		"White Herb",
		"Macho Brace",
		"Exp. Share",
		"Quick Claw",
		"Soothe Bell",
		"Mental Herb",
		"Choice Band",
		"King's Rock",
		"SilverPowder",
		"Amulet Coin",
		"Cleanse Tag",
		"Soul Dew",
		"DeepSeaTooth",
		"DeepSeaScale",
		"Smoke Ball",
		"Everstone",
		"Focus Band",
		"Lucky Egg",
		"Scope Lens",
		"Metal Coat",
		"Leftovers",
		"Dragon Scale",
		"Light Ball",
		"Soft Sand",
		"Hard Stone",
		"Miracle Seed",
		"BlackGlasses",
		"Black Belt",
		"Magnet",
		"Mystic Water",
		"Sharp Beak",
		"Poison Barb",
		"NeverMeltIce",
		"Spell Tag",
		"TwistedSpoon",
		"Charcoal",
		"Dragon Fang",
		"Silk Scarf",
		"Up-Grade",
		"Shell Bell",
		"Sea Incense",
		"Lax Incense",
		"Lucky Punch",
		"Metal Powder",
		"Thick Club",
		"Stick",
		"Red Scarf",
		"Blue Scarf",
		"Pink Scarf",
		"Green Scarf",
		"Yellow Scarf",
		"Wide Lens",
		"Muscle Band",
		"Wise Glasses",
		"Expert Belt",
		"Light Clay",
		"Life Orb",
		"Power Herb",
		"Toxic Orb",
		"Flame Orb",
		"Quick Powder",
		"Focus Sash",
		"Zoom Lens",
		"Metronome",
		"Iron Ball",
		"Lagging Tail",
		"Destiny Knot",
		"Black Sludge",
		"Icy Rock",
		"Smooth Rock",
		"Heat Rock",
		"Damp Rock",
		"Grip Claw",
		"Choice Scarf",
		"Sticky Barb",
		"Power Bracer",
		"Power Belt",
		"Power Lens",
		"Power Band",
		"Power Anklet",
		"Power Weight",
		"Shed Shell",
		"Big Root",
		"Choice Specs",
		"Flame Plate",
		"Splash Plate",
		"Zap PLate",
		"Meadow Plate",
		"Icicle Plate",
		"Fist Plate",
		"Toxic Plate",
		"Earth Plate",
		"Sky Plate",
		"Mind Plate",
		"Insect Plate",
		"Stone Plate",
		"Spooky Plate",
		"Draco Plate",
		"Dread Plate",
		"Iron Plate",
		"Odd Incense",
		"Rock Incense",
		"Full Incense",
		"Wave Incense",
		"Rose Incense",
		"Luck Incense",
		"Pure Incense",
		"Protector",
		"Electirizer",
		"Magmarizer",
		"Dubious Disc",
		"Reaper Cloth",
		"Razor Claw",
		"Razor Fang",
		"TM01",
		"TM02",
		"TM03",
		"TM04",
		"TM05",
		"TM06",
		"TM07",
		"TM08",
		"TM09",
		"TM10",
		"TM11",
		"TM12",
		"TM13",
		"TM14",
		"TM15",
		"TM16",
		"TM17",
		"TM18",
		"TM19",
		"TM20",
		"TM21",
		"TM22",
		"TM23",
		"TM24",
		"TM25",
		"TM26",
		"TM27",
		"TM28",
		"TM29",
		"TM30",
		"TM31",
		"TM32",
		"TM33",
		"TM34",
		"TM35",
		"TM36",
		"TM37",
		"TM38",
		"TM39",
		"TM40",
		"TM41",
		"TM42",
		"TM43",
		"TM44",
		"TM45",
		"TM46",
		"TM47",
		"TM48",
		"TM49",
		"TM50",
		"TM51",
		"TM52",
		"TM53",
		"TM54",
		"TM55",
		"TM56",
		"TM57",
		"TM58",
		"TM59",
		"TM60",
		"TM61",
		"TM62",
		"TM63",
		"TM64",
		"TM65",
		"TM66",
		"TM67",
		"TM68",
		"TM69",
		"TM70",
		"TM71",
		"TM72",
		"TM73",
		"TM74",
		"TM75",
		"TM76",
		"TM77",
		"TM78",
		"TM79",
		"TM80",
		"TM81",
		"TM82",
		"TM83",
		"TM84",
		"TM85",
		"TM86",
		"TM87",
		"TM88",
		"TM89",
		"TM90",
		"TM91",
		"TM92",
		"HM01",
		"HM02",
		"HM03",
		"HM04",
		"HM05",
		"HM06",
		"unknown",
		"unknown",
		"Explorer Kit",
		"Loot Sack",
		"Rule Book",
		"Poke Radar",
		"Point Card",
		"Journal",
		"Seal Case",
		"Fashion Case",
		"Seal Bag",
		"Pal Pad",
		"Works Key",
		"Old Charm",
		"Galactic Key",
		"Red Chain",
		"Town Map",
		"Vs. Seeker",
		"Coin Case",
		"Old Rod",
		"Good Rod",
		"Super Rod",
		"Sprayduck",
		"Poffin Case",
		"Bicycle",
		"Suite Key",
		"Oak's Letter",
		"Lunar Wing",
		"Member Card",
		"Azure Flute",
		"S.S. Ticket",
		"Contest Pass",
		"Magma Stone",
		"Parcel",
		"Coupon 1",
		"Coupon 2",
		"Coupon 3",
		"Storage Key",
		"SecretPotion",
		"Vs. Recorder",
		"Gracidea",
		"Secret Key",
		"Apricorn Box",
		"Unown Report",
		"Berry Pots",
		"Dowsing MCHN",
		"Blue Card",
		"SlowpokeTail",
		"Clear Bell",
		"Card Key",
		"Basement Key",
		"SquirtBottle",
		"Red Scale",
		"Lost Item",
		"Pass",
		"Machine Part",
		"Silver Wing",
		"Rainbow Wing",
		"Mystery Egg",
		"Red Apricorn",
		"Blu Apricorn",
		"Ylw Apricorn",
		"Grn Apricorn",
		"Pnk Apricorn",
		"Wht Apricorn",
		"Blk Apricorn",
		"Fast Ball",
		"Level Ball",
		"Lure Ball",
		"Heavy Ball",
		"Love Ball",
		"Friend Ball",
		"Moon Ball",
		"Sport Ball",
		"Park Ball",
		"Photo Album",
		"GB Sounds",
		"Tidal Bell",
		"RageCandyBar",
		"Data Card 01",
		"Data Card 02",
		"Data Card 03",
		"Data Card 04",
		"Data Card 05",
		"Data Card 06",
		"Data Card 07",
		"Data Card 08",
		"Data Card 09",
		"Data Card 10",
		"Data Card 11",
		"Data Card 12",
		"Data Card 13",
		"Data Card 14",
		"Data Card 15",
		"Data Card 16",
		"Data Card 17",
		"Data Card 18",
		"Data Card 19",
		"Data Card 20",
		"Data Card 21",
		"Data Card 22",
		"Data Card 23",
		"Data Card 24",
		"Data Card 25",
		"Data Card 26",
		"Data Card 27",
		"Jade Orb",
		"Lock Capsule",
		"Red Orb",
		"Blue Orb",
		"Enigma Stone",
		"Prism Scale",
		"Eviolite",
		"Float Stone",
		"Rocky Helmet",
		"Air Balloon",
		"Red Card",
		"Ring Target",
		"Binding Band",
		"Absorb Bulb",
		"Cell Battery",
		"Eject Button",
		"Fire Gem",
		"Water Gem",
		"Electric Gem",
		"Grass Gem",
		"Ice Gem",
		"Fighting Gem",
		"Poison Gem",
		"Ground Gem",
		"Flying Gem",
		"Psychic Gem",
		"Bug Gem",
		"Rock Gem",
		"Ghost Gem",
		"Dragon Gem",
		"Dark Gem",
		"Steel Gem",
		"Normal Gem",
		"Health Wing",
		"Muscle Wing",
		"Resist Wing",
		"Genius Wing",
		"Clever Wing",
		"Swift Wing",
		"Pretty Wing",
		"Cover Fossil",
		"Plume Fossil",
		"Liberty Pass",
		"Pass Orb",
		"Dream Ball",
		"Poke Toy",
		"Prop Case",
		"Dragon Skull",
		"BalmMushroom",
		"Big Nugget",
		"Pearl String",
		"Comet Shard",
		"Relic Copper",
		"Relic Silver",
		"Relic Gold",
		"Relic Vase",
		"Relic Band",
		"Relic Statue",
		"Relic Crown",
		"Casteliacone",
		"Dire Hit 2",
		"X Speed 2",
		"X Special 2",
		"X Sp. Def 2",
		"X Defend 2",
		"X Attack 2",
		"X Accuracy 2",
		"X Speed 3",
		"X Special 3",
		"X Sp. Def 3",
		"X Defend 3",
		"X Attack 3",
		"X Accuracy 3",
		"X Speed 6",
		"X Special 6",
		"X Sp. Def 6",
		"X Defend 6",
		"X Attack 6",
		"X Accuracy 6",
		"Ability Urge",
		"Item Drop",
		"Reset Urge",
		"Dire Hit 3",
		"Light Stone",
		"Dark Stone",
		"TM93",
		"TM94",
		"TM95"
	}
)
MiscData.HEALING_ITEMS_GEN4 =
	MiscUtils.readOnly(
	{
		[17] = {
			name = "Potion",
			amount = 20,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[23] = {
			name = "Full Restore",
			amount = 100,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[24] = {
			name = "Max Potion",
			amount = 100,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[25] = {
			name = "Hyper Potion",
			amount = 200,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[26] = {
			name = "Super Potion",
			amount = 60,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[30] = {
			name = "Fresh Water",
			amount = 50,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[31] = {
			name = "Soda Pop",
			amount = 60,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[32] = {
			name = "Lemonade",
			amount = 80,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[33] = {
			name = "Moomoo Milk",
			amount = 100,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[34] = {
			name = "EnergyPowder",
			amount = 50,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[35] = {
			name = "Energy Root",
			amount = 200,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[43] = {
			name = "Berry Juice",
			amount = 20,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[155] = {
			name = "Oran Berry",
			amount = 10,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[158] = {
			name = "Sitrus Berry",
			amount = 30,
			type = MiscData.HEALING_TYPE.CONSTANT
		},
		[159] = {
			name = "Figy Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[160] = {
			name = "Wiki Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[161] = {
			name = "Mago Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[162] = {
			name = "Aguav Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[163] = {
			name = "Iapapa Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		},
		[208] = {
			name = "Enigma Berry",
			amount = 12.5,
			type = MiscData.HEALING_TYPE.PERCENTAGE
		}
	}
)
MiscData.ABILITIES =
	MiscUtils.readOnly(
	{
		{
			id = 1,
			name = "Stench",
			description = "Has a 10% chance of making target Pokémon flinch with each hit."
		},
		{
			id = 2,
			name = "Drizzle",
			description = "Summons rain that lasts indefinitely upon entering battle."
		},
		{
			id = 3,
			name = "Speed Boost",
			description = "Raises Speed one stage after each turn."
		},
		{
			id = 4,
			name = "Battle Armor",
			description = "Protects against critical hits."
		},
		{
			id = 5,
			name = "Sturdy",
			description = {
				"Prevents OHKO moves like Guillotine from working.",
				"Prevents being KOed from full HP, and this includes moves such as Guillotine and Sheer Cold."
			}
		},
		{
			id = 6,
			name = "Damp",
			description = "Prevents self destruct, explosion, and aftermath from working while the Pokémon is in battle."
		},
		{
			id = 7,
			name = "Limber",
			description = "Prevents paralysis."
		},
		{
			id = 8,
			name = "Sand Veil",
			description = "Increases evasion to 1.25x during a sandstorm. Protects against sandstorm damage."
		},
		{
			id = 9,
			name = "Static",
			description = "Has a 30% chance of paralyzing attacking Pokémon on contact."
		},
		{
			id = 10,
			name = "Volt Absorb",
			description = "Absorbs electric moves, healing for 1/4 max HP."
		},
		{
			id = 11,
			name = "Water Absorb",
			description = "Absorbs water moves, healing for 1/4 max HP."
		},
		{
			id = 12,
			name = "Oblivious",
			description = "Prevents infatuation and protects against captivate."
		},
		{
			id = 13,
			name = "Cloud Nine",
			description = "Negates all effects of weather, but does not prevent the weather itself."
		},
		{
			id = 14,
			name = "Compoundeyes",
			description = "Increases moves' accuracy to 1.3x."
		},
		{
			id = 15,
			name = "Insomnia",
			description = "Prevents sleep."
		},
		{
			id = 16,
			name = "Color Change",
			description = "Changes type to match when hit by a damaging move."
		},
		{
			id = 17,
			name = "Immunity",
			description = "Prevents poison."
		},
		{
			id = 18,
			name = "Flash Fire",
			description = "Protects against fire moves. Once one has been blocked, the Pokémon's own Fire moves inflict 1.5x damage until it leaves battle."
		},
		{
			id = 19,
			name = "Shield Dust",
			description = "Protects against incoming moves' extra effects."
		},
		{
			id = 20,
			name = "Own Tempo",
			description = "Prevents confusion."
		},
		{
			id = 21,
			name = "Suction Cups",
			description = "Prevents being forced out of battle by other Pokémon's moves."
		},
		{
			id = 22,
			name = "Intimidate",
			description = "Lowers opponents' Attack one stage upon entering battle."
		},
		{
			id = 23,
			name = "Shadow Tag",
			description = "Prevents opponents from fleeing or switching out."
		},
		{
			id = 24,
			name = "Rough Skin",
			description = "Damages attacking Pokémon for 1/8 their max HP on contact."
		},
		{
			id = 25,
			name = "Wonder Guard",
			description = "Protects against damaging moves that are not super effective."
		},
		{
			id = 26,
			name = "Levitate",
			description = "Evades ground moves."
		},
		{
			id = 27,
			name = "Effect Spore",
			description = "Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pokémon on contact."
		},
		{
			id = 28,
			name = "Synchronize",
			description = "Copies burns, paralysis, and poison received onto the Pokémon that inflicted them."
		},
		{
			id = 29,
			name = "Clear Body",
			description = "Prevents stats from being lowered by other Pokémon."
		},
		{
			id = 30,
			name = "Natural Cure",
			description = "Cures any major status ailment upon switching out or completing a battle."
		},
		{
			id = 31,
			name = "Lightning Rod",
			description = {
				"Redirects single-target electric moves to this Pokémon where possible.",
				"Redirects electric moves to this Pokémon and absorbs them, raising Special Attack one stage."
			}
		},
		{
			id = 32,
			name = "Serene Grace",
			description = "Doubles the chance of moves' extra effects occurring."
		},
		{
			id = 33,
			name = "Swift Swim",
			description = "Doubles Speed during rain."
		},
		{
			id = 34,
			name = "Chlorophyll",
			description = "Doubles Speed during strong sunlight."
		},
		{
			id = 35,
			name = "Illuminate",
			description = "Doubles the wild encounter rate."
		},
		{
			id = 36,
			name = "Trace",
			description = "Copies an opponent's ability upon entering battle."
		},
		{
			id = 37,
			name = "Huge Power",
			description = "Doubles Attack in battle."
		},
		{
			id = 38,
			name = "Poison Point",
			description = "Has a 30% chance of poisoning attacking Pokémon on contact."
		},
		{
			id = 39,
			name = "Inner Focus",
			description = "Prevents flinching."
		},
		{
			id = 40,
			name = "Magma Armor",
			description = "Prevents freezing."
		},
		{
			id = 41,
			name = "Water Veil",
			description = "Prevents burns."
		},
		{
			id = 42,
			name = "Magnet Pull",
			description = "Prevents steel opponents from fleeing or switching out."
		},
		{
			id = 43,
			name = "Soundproof",
			description = "Protects against sound-based moves."
		},
		{
			id = 44,
			name = "Rain Dish",
			description = "Heals for 1/16 max HP after each turn during rain."
		},
		{
			id = 45,
			name = "Sand Stream",
			description = "Summons a sandstorm that lasts indefinitely upon entering battle."
		},
		{
			id = 46,
			name = "Pressure",
			description = "Increases the PP cost of moves targetting the Pokémon by one."
		},
		{
			id = 47,
			name = "Thick Fat",
			description = "Halves damage from fire and ice moves."
		},
		{
			id = 48,
			name = "Early Bird",
			description = "Makes sleep pass twice as quickly."
		},
		{
			id = 49,
			name = "Flame Body",
			description = "Has a 30% chance of burning attacking Pokémon on contact."
		},
		{
			id = 50,
			name = "Run Away",
			description = "Ensures success fleeing from wild battles."
		},
		{
			id = 51,
			name = "Keen Eye",
			description = "Prevents accuracy from being lowered."
		},
		{
			id = 52,
			name = "Hyper Cutter",
			description = "Prevents Attack from being lowered by other Pokémon."
		},
		{
			id = 53,
			name = "Pickup",
			description = "Picks up other Pokémon's used and Flung held items. May also pick up an item after battle."
		},
		{
			id = 54,
			name = "Truant",
			description = "Skips every second turn."
		},
		{
			id = 55,
			name = "Hustle",
			description = "Strengthens physical moves to inflict 1.5x damage, but decreases their accuracy to 0.8x."
		},
		{
			id = 56,
			name = "Cute Charm",
			description = "Has a 30% chance of infatuating attacking Pokémon on contact."
		},
		{
			id = 57,
			name = "Plus",
			description = "Increases Special Attack to 1.5x when a friendly Pokémon has plus or minus."
		},
		{
			id = 58,
			name = "Minus",
			description = "Increases Special Attack to 1.5x when a friendly Pokémon has plus or minus."
		},
		{
			id = 59,
			name = "Forecast",
			description = "Changes Castform's type and form to match the weather."
		},
		{
			id = 60,
			name = "Sticky Hold",
			description = "Prevents a held item from being removed by other Pokémon."
		},
		{
			id = 61,
			name = "Shed Skin",
			description = "Has a 33% chance of curing any major status ailment after each turn."
		},
		{
			id = 62,
			name = "Guts",
			description = "Increases Attack to 1.5x with a major status ailment."
		},
		{
			id = 63,
			name = "Marvel Scale",
			description = "Increases Defense to 1.5x with a major status ailment."
		},
		{
			id = 64,
			name = "Liquid Ooze",
			description = "Damages opponents using leeching moves for as much as they would heal."
		},
		{
			id = 65,
			name = "Overgrow",
			description = "Strengthens grass moves to inflict 1.5x damage at 1/3 max HP or less."
		},
		{
			id = 66,
			name = "Blaze",
			description = "Strengthens fire moves to inflict 1.5x damage at 1/3 max HP or less."
		},
		{
			id = 67,
			name = "Torrent",
			description = "Strengthens water moves to inflict 1.5x damage at 1/3 max HP or less."
		},
		{
			id = 68,
			name = "Swarm",
			description = "Strengthens bug moves to inflict 1.5x damage at 1/3 max HP or less."
		},
		{
			id = 69,
			name = "Rock Head",
			description = "Protects against recoil damage."
		},
		{
			id = 70,
			name = "Drought",
			description = "Summons strong sunlight that lasts indefinitely upon entering battle."
		},
		{
			id = 71,
			name = "Arena Trap",
			description = "Prevents opponents from fleeing or switching out. Eluded by flying-types and Pokémon in the air."
		},
		{
			id = 72,
			name = "Vital Spirit",
			description = "Prevents sleep."
		},
		{
			id = 73,
			name = "White Smoke",
			description = "Prevents stats from being lowered by other Pokémon."
		},
		{
			id = 74,
			name = "Pure Power",
			description = "Doubles Attack in battle."
		},
		{
			id = 75,
			name = "Shell Armor",
			description = "Protects against critical hits."
		},
		{
			id = 76,
			name = "Air Lock",
			description = "Negates all effects of weather, but does not prevent the weather itself."
		},
		{
			id = 77,
			name = "Tangled Feet",
			description = "Doubles evasion when confused."
		},
		{
			id = 78,
			name = "Motor Drive",
			description = "Absorbs electric moves, raising Speed one stage."
		},
		{
			id = 79,
			name = "Rivalry",
			description = "Increases damage inflicted to 1.25x against Pokémon of the same gender, but decreases damage to 0.75x against the opposite gender."
		},
		{
			id = 80,
			name = "Steadfast",
			description = "Raises Speed one stage upon flinching."
		},
		{
			id = 81,
			name = "Snow Cloak",
			description = "Increases evasion to 1.25x during hail. Protects against hail damage."
		},
		{
			id = 82,
			name = "Gluttony",
			description = "Makes the Pokémon eat any held Berry triggered by low HP below 1/2 its max HP."
		},
		{
			id = 83,
			name = "Anger point",
			description = "Raises Attack to the maximum of six stages upon receiving a critical hit."
		},
		{
			id = 84,
			name = "Unburden",
			description = "Doubles Speed upon using or losing a held item."
		},
		{
			id = 85,
			name = "Heatproof",
			description = "Halves damage from fire moves and burns."
		},
		{
			id = 86,
			name = "Simple",
			description = "Doubles the Pokémon's stat modifiers. These doubled modifiers are still capped at -6 or 6 stages."
		},
		{
			id = 87,
			name = "Dry Skin",
			description = "Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain. Increases damage from fire moves to 1.25x, but absorbs water moves, healing for 1/4 max HP."
		},
		{
			id = 88,
			name = "Download",
			description = "Raises the attack stat corresponding to the opponents' weaker defense one stage upon entering battle."
		},
		{
			id = 89,
			name = "Iron Fist",
			description = "Strengthens punch-based moves to 1.2x their power."
		},
		{
			id = 90,
			name = "Poison Heal",
			description = "Heals for 1/8 max HP after each turn when poisoned in place of damage."
		},
		{
			id = 91,
			name = "Adaptability",
			description = "Increases the same-type attack bonus from 1.5x to 2x."
		},
		{
			id = 92,
			name = "Skill Link",
			description = "Extends two-to-five-hit moves and triple kick to their full length every time."
		},
		{
			id = 93,
			name = "Hydration",
			description = "Cures any major status ailment after each turn during rain."
		},
		{
			id = 94,
			name = "Solar Power",
			description = "Increases Special Attack to 1.5x but costs 1/8 max HP after each turn during strong sunlight."
		},
		{
			id = 95,
			name = "Quick Feet",
			description = "Increases Speed to 1.5x with a major status ailment."
		},
		{
			id = 96,
			name = "Normalize",
			description = "Makes the Pokémon's moves all act normal-type."
		},
		{
			id = 97,
			name = "Sniper",
			description = "Strengthens critical hits to inflict 3x damage rather than 2x."
		},
		{
			id = 98,
			name = "Magic Guard",
			description = "Protects against damage not directly caused by a move."
		},
		{
			id = 99,
			name = "No Guard",
			description = "Ensures all moves used by and against the Pokémon hit."
		},
		{
			id = 100,
			name = "Stall",
			description = "Makes the Pokémon move last within its move's priority bracket."
		},
		{
			id = 101,
			name = "Technician",
			description = "Strengthens moves of 60 base power or less to 1.5x their power."
		},
		{
			id = 102,
			name = "Leaf Guard",
			description = "Protects against major status ailments during strong sunlight."
		},
		{
			id = 103,
			name = "Klutz",
			description = "Verhindert, dass das Pokémon ein getragenes Item im Kampf einsetzt."
		},
		{
			id = 104,
			name = "Mold Breaker",
			description = "Bypasses targets' abilities if they could hinder or prevent a move."
		},
		{
			id = 105,
			name = "Super Luck",
			description = "Raises moves' critical hit rates one stage."
		},
		{
			id = 106,
			name = "Aftermath",
			description = "Damages the attacker for 1/4 its max HP when knocked out by a contact move."
		},
		{
			id = 107,
			name = "Anticipation",
			description = "Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move."
		},
		{
			id = 108,
			name = "Forewarn",
			description = "Reveals the opponents' strongest move upon entering battle."
		},
		{
			id = 109,
			name = "Unaware",
			description = "Ignores other Pokémon's stat modifiers for damage and accuracy calculation."
		},
		{
			id = 110,
			name = "Tinted Lens",
			description = "Doubles damage inflicted with not-very-effective moves."
		},
		{
			id = 111,
			name = "Filter",
			description = "Decreases damage taken from super-effective moves by 1/4."
		},
		{
			id = 112,
			name = "Slow Start",
			description = "Halves Attack and Speed for five turns upon entering battle."
		},
		{
			id = 113,
			name = "Scrappy",
			description = "Lets the Pokémon's normal and fighting moves hit ghost Pokémon."
		},
		{
			id = 114,
			name = "Storm Drain",
			description = {
				"Redirects single-target water moves to this Pokémon.",
				"Redirects single-target water moves to this Pokémon and absorbs them, raising Special Attack one stage."
			}
		},
		{
			id = 115,
			name = "Ice Body",
			description = "Heals for 1/16 max HP after each turn during hail. Protects against hail damage."
		},
		{
			id = 116,
			name = "Solid Rock",
			description = "Decreases damage taken from super-effective moves by 1/4."
		},
		{
			id = 117,
			name = "Snow Warning",
			description = "Summons hail that lasts indefinitely upon entering battle."
		},
		{
			id = 118,
			name = "Honey Gather",
			description = "The Pokémon may pick up honey after battle."
		},
		{
			id = 119,
			name = "Frisk",
			description = "Enthüllt bei Kampfantritt das getragene Item des Gegners."
		},
		{
			id = 120,
			name = "Reckless",
			description = "Strengthens recoil moves to 1.2x their power."
		},
		{
			id = 121,
			name = "Multitype",
			description = "Changes arceus's type and form to match its held Plate."
		},
		{
			id = 122,
			name = "Flower Gift",
			description = "Increases friendly Pokémon's Attack and Special Defense to 1.5x during strong sunlight."
		},
		{
			id = 123,
			name = "Bad Dreams",
			description = "Damages sleeping opponents for 1/8 their max HP after each turn."
		},
		{
			id = 124,
			name = "Pickpocket",
			description = "Steals attacking Pokémon's held items on contact."
		},
		{
			id = 125,
			name = "Sheer Force",
			description = "Strengthens moves with extra effects to 1.3x their power, but prevents their extra effects."
		},
		{
			id = 126,
			name = "Contrary",
			description = "Inverts stat changes."
		},
		{
			id = 127,
			name = "Unnerve",
			description = "Prevents opposing Pokémon from eating held Berries."
		},
		{
			id = 128,
			name = "Defiant",
			description = "Raises Attack two stages upon having any stat lowered."
		},
		{
			id = 129,
			name = "Defeatist",
			description = "Halves Attack and Special Attack at 50% max HP or less."
		},
		{
			id = 130,
			name = "Cursed Body",
			description = "Has a 30% chance of Disabling any move that hits the Pokémon."
		},
		{
			id = 131,
			name = "Healer",
			description = "Has a 30% chance of curing each adjacent ally of any major status ailment after each turn."
		},
		{
			id = 132,
			name = "Friend Guard",
			description = "Decreases all direct damage taken by friendly Pokémon to 0.75x."
		},
		{
			id = 133,
			name = "Weak Armor",
			description = "Raises Speed and lowers Defense by one stage each upon being hit by a physical move."
		},
		{
			id = 134,
			name = "Heavy Metal",
			description = "Doubles the Pokémon's weight."
		},
		{
			id = 135,
			name = "Light Metal",
			description = "Halves the Pokémon's weight."
		},
		{
			id = 136,
			name = "Multiscale",
			description = "Halves damage taken from full HP."
		},
		{
			id = 137,
			name = "Toxic Boost",
			description = "Increases Attack to 1.5x when poisoned."
		},
		{
			id = 138,
			name = "Flare Boost",
			description = "Increases Special Attack to 1.5x when burned."
		},
		{
			id = 139,
			name = "Harvest",
			description = "Has a 50% chance of restoring a used Berry after each turn if the Pokémon has held no items in the meantime."
		},
		{
			id = 140,
			name = "Telepathy",
			description = "Protects against friendly Pokémon's damaging moves."
		},
		{
			id = 141,
			name = "Moody",
			description = "Raises a random stat two stages and lowers another one stage after each turn."
		},
		{
			id = 142,
			name = "Overcoat",
			description = "Protects against damage from weather."
		},
		{
			id = 143,
			name = "Poison Touch",
			description = "Has a 30% chance of poisoning target Pokémon upon contact."
		},
		{
			id = 144,
			name = "Regenerator",
			description = "Heals for 1/3 max HP upon switching out."
		},
		{
			id = 145,
			name = "Big pecks",
			description = "Schützt vor dem Absenken der defense."
		},
		{
			id = 146,
			name = "Sand Rush",
			description = "Doubles Speed during a sandstorm. Protects against sandstorm damage."
		},
		{
			id = 147,
			name = "Wonder Skin",
			description = "Lowers incoming non-damaging moves' base accuracy to exactly 50%."
		},
		{
			id = 148,
			name = "Analytic",
			description = "Strengthens moves to 1.3x their power when moving last."
		},
		{
			id = 149,
			name = "Illusion",
			description = "Takes the appearance of the last conscious party Pokémon upon being sent out until hit by a damaging move."
		},
		{
			id = 150,
			name = "Imposter",
			description = "Transforms upon entering battle."
		},
		{
			id = 151,
			name = "Infiltrator",
			description = "Bypasses light screen, reflect, and safeguard."
		},
		{
			id = 152,
			name = "Mummy",
			description = "Changes attacking Pokémon's abilities to Mummy on contact."
		},
		{
			id = 153,
			name = "Moxie",
			description = "Raises Attack one stage upon KOing a Pokémon."
		},
		{
			id = 154,
			name = "Justified",
			description = "Raises Attack one stage upon taking damage from a dark move."
		},
		{
			id = 155,
			name = "Rattled",
			description = "Raises Speed one stage upon being hit by a dark, ghost, or bug move."
		},
		{
			id = 156,
			name = "Magic Bounce",
			description = "Reflects most non-damaging moves back at their user."
		},
		{
			id = 157,
			name = "Sap Sipper",
			description = "Absorbs grass moves, raising Attack one stage."
		},
		{
			id = 158,
			name = "Prankster",
			description = "Raises non-damaging moves' priority by one stage."
		},
		{
			id = 159,
			name = "Sand Force",
			description = "Strengthens rock, ground, and steel moves to 1.3x their power during a sandstorm. Protects against sandstorm damage."
		},
		{
			id = 160,
			name = "Iron Barbs",
			description = "Damages attacking Pokémon for 1/8 their max HP on contact."
		},
		{
			id = 161,
			name = "Zen Mode",
			description = "Changes darmanitan's form after each turn depending on its HP: Zen Mode below 50% max HP, and Standard Mode otherwise."
		},
		{
			id = 162,
			name = "Victory Star",
			description = "Increases moves' accuracy to 1.1x for friendly Pokémon."
		},
		{
			id = 163,
			name = "Turboblaze",
			description = "Bypasses targets' abilities if they could hinder or prevent moves."
		},
		{
			id = 164,
			name = "Teravolt",
			description = "Bypasses targets' abilities if they could hinder or prevent moves."
		}
	}
)
